### ISSUE TITLE
GenerateAssemblyInfo set to false disables EnablePreviewFeatures, then CA2252

### ISSUE THREAD

**Issue by ChrisBertrandIndus** [dotnet/roslyn-analyzers#5939] opened 2022-03-30 06:52 UTC
### Analyzer

CA2252

### Analyzer source

- Visual Studio 17.1.2
- C#   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f

.NET SDKs installed:
  5.0.405
  6.0.200
  6.0.201

Also tried (with same error) NuGet package :
Microsoft.CodeAnalysis.NetAnalyzers Version=6.0.0

### Describe the bug

Setting both `EnablePreviewFeatures` to True and `GenerateAssemblyInfo` to False in the csproj file disables `EnablePreviewFeatures` (compilation works as if it was not defined, or set to False).

### Steps To Reproduce

1. Create a .NET 6 library.
2. Create an interface in the project.
3. Add a function to the interface : `static abstract void A();`
4. Add `<EnablePreviewFeatures>True</EnablePreviewFeatures>` to the csproj.
5. Compile. That should be OK.
6. Add `<GenerateAssemblyInfo>False</GenerateAssemblyInfo>` to the csproj.
7. Compilation fails with error CA2252. 

Code:

        internal interface ITest
        {
	        static abstract void A();
        }

### Expected behavior

No compilation error.

### Actual behavior

Compilation fails with error CA2252.

**Comment by buyaa-n** [comment] 2022-03-30 17:51
This is by design, Assembly generation should be enabled in order to MSBuild could add the `[assembly: System.Runtime.Versioning.RequiresPreviewFeaturesAttribute()]` attribute into the assembly, which would tell the analyzer that the assembly is opted in to Preview feature, if you disabled `AssemblyInfo.cs` file generation with `<GenerateAssemblyInfo>False</GenerateAssemblyInfo>` you need to add the attribute manually somewhere, probably you have a custom `AssemblyInfo` file which is the perfect place to add the attribute

**Comment by ChrisBertrandIndus** [comment] 2022-03-31 06:31
@buyaa-n 

When I add `[assembly: System.Runtime.Versioning.RequiresPreviewFeaturesAttribute()]` to AssemblyInfo.cs, compilation fails with the error CS8703 (translation: _The abstract modifier is invalid for that item in C# 10.0. Use the preview version of the language or a later version_).

I ensured the AssemblyInfo.cs is taken into account (using AssemblyVersion), so RequiresPreviewFeaturesAttribute is too. Except it seems not to help here.

**Comment by buyaa-n** [comment] 2022-03-31 17:09
Yes, as you are using a preview feature of the language you are also need to use preview version of the language, if you don't know how to do that you can just use the fixer of that CS8703 error, click on `Show potential fixes` => `Upgrade this project to C# language version 'preview'`
![image](https://user-images.githubusercontent.com/45579687/161110955-16231080-0b61-41ca-82cf-7aba77a7ce07.png)

**Comment by ChrisBertrandIndus** [comment] 2022-04-01 06:10
Thank you for this detailed explanation.

I suggest to add a rule that makes a warning when both EnablePreviewFeatures is true and GenerateAssemblyInfo is false.

**Comment by buyaa-n** [comment] 2022-04-01 21:08
> I suggest to add a rule that makes a warning when both EnablePreviewFeatures is true and GenerateAssemblyInfo is false.

That is probably should be MSBuild analyzer not a roslyn analyzer

**Comment by ChrisBertrandIndus** [comment] 2022-04-04 07:27
@buyaa-n 

I opened a ticket at msbuild as suggested:
[https://github.com/dotnet/msbuild/issues/7515](https://github.com/dotnet/msbuild/issues/7515)

**Comment by buyaa-n** [comment] 2022-04-04 17:17
Thanks @ChrisBertrandIndus, closing this issue as by design

**Closed by buyaa-n** 2022-04-04 17:17 UTC
