### ISSUE TITLE
Analyzers stopped working after upgrade to VS2022 17.4.0

### ISSUE THREAD

**Issue by MarcelVersteeg** [dotnet/roslyn-analyzers#6263] opened 2022-11-14 07:54 UTC
**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 6.0.0

### Describe the bug

Code Analysis was working fine with VS2022 version 17.3.4. After I upgraded to VS2022 version 17.4.0, CodeAnalysis stopped working completely, and I am not able to get it working again.

### Steps To Reproduce

1. Have Visual Studio 2022 version 17.3.4 installed
2. Have a C# project that has the following in the project file (left out certain parts for brevity):
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net481</TargetFrameworks>
    <RootNamespace>MyRootNamespace</RootNamespace>
    <AssemblyName>MyAssembly</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <AnalysisMode>All</AnalysisMode>
  </PropertyGroup>
  <!-- Left out additional properties -->
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
3. Make sure there are some code analysis issues in the code and build the project.
4. Upgrade to VS2022 version 17.4
5. Rebuild the project and notice none of the existing issues are reported anymore (though a warning is emitted indicating a newer version of the analyzers are available with the SDK).

### Expected behavior
The code analysis keeps working, even after the upgrade.

### Actual behavior
The code analysis is no longer performed.

## Additional context
I have also tried the following to get the analysis working again, but all to no avail:
- Completely remove the package reference to the Microsoft.CodeAnalysis.NetAnalyzers package. This removes the warning that a newer version is present in the SDK, but the code analysis is still not executed (at least no warnings/errors are emitted)
- Replace the `<AnalysisMode>` property with the following: `<EnableNETAnalyzers>True</EnableNETAnalyzers><AnalysisLevel>latest-all</AnalysisLevel>`. This also does not make the code analysis emit any warnings/errors.
- Replace the `<PackageReference>` with the latest version on NuGet (version 7.0.0-preview1.22518.1). This removes the warning that a newer version is present in the SDK, but the code analysis is still not executed (at least no warnings/errors are emitted)

**Comment by mavasani** [comment] 2022-11-14 08:48
This is likely a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/6245. Can you try upgrading your NuGet package reference to https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet7/NuGet/Microsoft.CodeAnalysis.NetAnalyzers/versions/7.0.0-preview1.22559.1 and check if you get code analysis back again?

**Comment by MarcelVersteeg** [comment] 2022-11-14 10:16
Unfortunately, that doesn't solve the issue.

**Comment by sk-pub** [comment] 2022-12-08 15:47
Our target framework is .NET 6, but VisualStudio 17.4.2 does not show errors from analyzers. Solved by reverting back to VS 17.3.0.

**Comment by MarcelVersteeg** [comment] 2022-12-09 09:31
@mavasani Is there any progress on this issue? I do not want to revert back to 17.3.0 just for this.

**Comment by mavasani** [comment] 2022-12-09 09:37
@MarcelVersteeg can you please share a small repro project to help investigations?

**Comment by mavasani** [comment] 2022-12-12 03:50
@MarcelVersteeg I am unable to see a CA1303 warning emitted in your attached project even in 17.3.

`CA1303` has always been a _disabled by default_ rule in the .NET SDK: https://github.com/dotnet/roslyn-analyzers/blob/f016189fe1769889f8b247863ef809f12a6c1996/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotPassLiteralsAsLocalizedParameters.cs#L35-L45

So, it is not expected to fire by default in any version of VS. I added a `.editorconfig` at the root of the solution with the following contents and see the warning fires as expected:

```
[*.cs]

# CA1303: Do not pass literals as localized parameters
dotnet_diagnostic.CA1303.severity = warning
```

**Comment by MarcelVersteeg** [comment] 2022-12-12 07:08
@mavasani I am sorry that the previous example did not reproduce it. I must admit that I just copied a project of mine and made some minor adjustments and dit not check it on version 17.3 of VS2022.

Now I have installed the older version in a virtual machine, updated the project and now it emits CA1303 on VS2022 version 17.3, but not on VS2022 version 17.4.

I added the following properties to the project (compared to the previous sample):
```
<WarningLevel>4</WarningLevel>
<AnalysisMode>All</AnalysisMode>
<AnalysisLevel>latest-all</AnalysisLevel>
<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
<_SkipUpgradeNetAnalyzersNuGetWarning>True</_SkipUpgradeNetAnalyzersNuGetWarning>
<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
```

This also means that the build will actually fail when a CA warning is emitted. This makes it more obvious when it is not emitted.

[NetAnalyzersBugFixed.zip](https://github.com/dotnet/roslyn-analyzers/files/10205359/NetAnalyzersBugFixed.zip)

**Comment by mavasani** [comment] 2022-12-12 08:06
Thank you so much @MarcelVersteeg - I can reproduce the issue now. This is indeed a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/6245. 

Tagging @jmarolf - Jon, your comment https://github.com/dotnet/roslyn-analyzers/pull/6246#issuecomment-1315825057 indicating that #6246 made it into .NET 7.0.100 SDK (and hence https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/7.0.0) does not seem to be correct. I can confirm that by looking at the config files that ship inside the .NET 7.0.100 SDK, as well as 7.0.0 released NuGet package. The configs folder should have `analysislevel_7_*.editorconfig` files, but these are only present in `7.0.0-preview1.22559.1` package, not in the release 7.0.0 version or the SDK.

### Config files in .NET 7.0.100 SDK
![image](https://user-images.githubusercontent.com/10605811/206992605-145d2423-a2e0-4c0c-85d1-86d28996be7b.png)

### Config files in https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/7.0.0
![image](https://user-images.githubusercontent.com/10605811/206990048-29d7afc8-fe18-497c-bed1-8c3670802997.png)

### Config files in https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet7/NuGet/Microsoft.CodeAnalysis.NetAnalyzers/versions/7.0.0-preview1.22559.1
![image](https://user-images.githubusercontent.com/10605811/206993025-74c8cd13-81f0-4352-94a7-bb655401d4ee.png)


Adding an explicit NuGet package reference to latest 7.x.x preview package from this feed: `https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet7/NuGet/Microsoft.CodeAnalysis.NetAnalyzers/versions/7.0.0-preview1.22559.1` as below fixes the issue: `<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="7.0.0-preview1.22559.1">`

**Comment by MarcelVersteeg** [comment] 2022-12-30 10:05
I just updated to Visual Studio 17.4.3 and .NET analyzers version 7.0.0 and that combination works: code analysis is performed again.

**Comment by mavasani** [comment] 2022-12-30 12:35
Thanks for the confirmation

**Closed by mavasani** 2022-12-30 12:35 UTC

**Comment by AroglDarthu** [comment] 2023-03-10 13:31
This seems to have regressed into 17.5.x (see #6503 )
Perhaps because the SDK shipped with a preview version of MSBuild?
Is there a version 17.5.2 underway (soon)? Or do we have to revert to 17.4.5?

**Comment by olstakh** [comment] 2024-09-05 21:11
@mavasani , i created a console project with the only dependency to `Microsoft.Extensions.Logging` package, introduced violation of CA2254 in the code and see it being reported on.
Then i add `Microsoft.Azure.Workflows.Client` package reference - and violation reporting disappears. Im assuming it might be related to multitargeting also, but do you have suggestions what to do in this case?
