### ISSUE TITLE
Could not load file or assembly 'System.Runtime.Analyzers, Version=1.0.0.0'. Strong name validation failed

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [dotnet/roslyn-analyzers#1275] opened 2017-07-31 17:52 UTC
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers version 1.1.0

#### Repro steps

1. Install the package to a .NET core library project 
2. Build

#### Expected behavior
No warnings or errors as long as there is no code breaking rules

#### Actual behavior
```
8>CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\husun\.nuget\packages\system.runtime.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.Analyzers.dll : Could not load file or assembly 'System.Runtime.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
8>CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\husun\.nuget\packages\system.runtime.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.CSharp.Analyzers.dll : Could not load file or assembly 'System.Runtime.CSharp.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
8>CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\husun\.nuget\packages\system.runtime.interopservices.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.InteropServices.Analyzers.dll : Could not load file or assembly 'System.Runtime.InteropServices.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

**Comment by thomaslevesque** [comment] 2017-09-16 11:55
I'm seeing this too.

**Comment by mavasani** [comment] 2017-11-10 17:44
This was fixed in subsequent versions of this package. Can you please try later versions as per https://github.com/dotnet/roslyn-analyzers#recommended-version-of-analyzer-packages?

**Closed by mavasani** 2017-11-10 17:44 UTC

**Comment by tokatm** [comment] 2020-03-20 13:43
I encountered this problem during using Unity3D. I haven't been found the solution. Visual Studio was looking for to folder 'AnalyzingAssmeblyLoader'. I didn't see when looked to '...Local>Temp>VS>'. I guess i deleted somethings wrong. I reinstalled to Visual Studio and the problem is solved.
