### ISSUE TITLE
'BasicDoNotUseCountWhenAnyCanBeUsedFixer' encountered an error

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3749] opened 2020-06-14 12:54 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

[CA1827](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1827)

#### Repro steps

![image](https://user-images.githubusercontent.com/31348972/84593882-ec198900-ae4e-11ea-96ce-a968d633a992.png)

#### StackTrace

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.WithTrailingTrivia[TSyntax](TSyntax node,IEnumerable`1 trivia)
   at async Microsoft.NetCore.Analyzers.Performance.DoNotUseCountWhenAnyCanBeUsedFixer.DoNotUseCountWhenAnyCanBeUsedCodeAction.GetChangedDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Note: The fix message mentioned AnyAsync and CountAsync, while my method isn't async at all.

![image](https://user-images.githubusercontent.com/31348972/84593920-313dbb00-ae4f-11ea-94e8-ada37b179bfc.png)

Note2: I haven't tested with the latest master.

**Comment by Evangelink** [comment] 2020-06-15 09:48
@Youssef1313 As far as I can see when looking at the StackTrace and at the fixer implementation (and history) this seems to be an issue on roslyn's side.

**Comment by Youssef1313** [comment] 2020-06-15 09:59
If that's the case, @mavasani can move this to Roslyn repo.

**Comment by Youssef1313** [comment] 2020-06-15 10:00
I just remembered this part:

> Note: The fix message mentioned AnyAsync and CountAsync, while my method isn't async at all.

@Evangelink, I think this should be issue on roslyn-analyzers side, and the exception on roslyn side, right?

**Comment by Evangelink** [comment] 2020-06-15 10:07
Oh yes! I also forgot about the other part of the issue!

**Comment by Youssef1313** [comment] 2020-06-15 10:53
I'll keep this open here for the other part, and open another issue in Roslyn now.

**Comment by CyrusNajmabadi** [comment] 2020-06-16 19:42
> SyntaxNodeExtensions.WithTrailingTrivia[TSyntax](TSyntax node,IEnumerable`1 trivia) is just:

```c#
        public static TSyntax WithTrailingTrivia<TSyntax>(
            this TSyntax node,
            IEnumerable<SyntaxTrivia>? trivia) where TSyntax : SyntaxNode
        {
            var last = node.GetLastToken(includeZeroWidth: true);
            var newLast = last.WithTrailingTrivia(trivia);
            return node.ReplaceToken(last, newLast);
        }
```

A null ref here is just either that `node` was null (caller error). or `node.GetLastToken()` returned null.  Feels *extremely* unlikely for the latter to be true.  Absent a repro, we woudl not be able to fix this.

**Comment by CyrusNajmabadi** [comment] 2020-06-16 19:44
@mavasani says this was fixed in https://github.com/dotnet/roslyn-analyzers/commit/2404ec0009697e2f85bc903343bc15cbe6030165#diff-3d9e4124e9d936082db4831148dac9ca here: https://github.com/dotnet/roslyn-analyzers/issues/3087

I'm going to close this out.

**Comment by CyrusNajmabadi** [comment] 2020-06-16 19:44
Dupe of https://github.com/dotnet/roslyn-analyzers/issues/3087

**Comment by CyrusNajmabadi** [comment] 2020-06-16 19:45
Hrmm.. reopening.  other issue says it's fixed for 2.9.9, but this reported against 3.0

**Comment by CyrusNajmabadi** [comment] 2020-06-16 19:45
In the future, if you can please supply a repro source case, that would be very useful.

**Comment by Youssef1313** [comment] 2020-06-16 21:40
Here is the repro steps

1. Create a new .NET Core VB Console App
1. Install version 3.0 of FxCopAnalyzers
1. Use the following code:


    ```vb
    Imports System

    Module Program
        Sub Main(args As String())
            Console.WriteLine("Hello World!")
        End Sub

        Sub TestSub(x As IEnumerable(Of Integer))
            If x.Count = 0 Then Return
        End Sub
    End Module
    ```

1. Put the cursor on `Count`.

1. Press <kbd>CTRL</kbd>+<kbd>.</kbd>

1. The exception is thrown with the stack trace:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.WithTrailingTrivia[TSyntax](TSyntax node,IEnumerable`1 trivia)
   at async Microsoft.NetCore.Analyzers.Performance.DoNotUseCountWhenAnyCanBeUsedFixer.DoNotUseCountWhenAnyCanBeUsedCodeAction.GetChangedDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by CyrusNajmabadi** [comment] 2020-06-16 22:11
Thanks.  super super helpful!

**Comment by Evangelink** [comment] 2020-08-07 15:52
@Youssef1313 Do you know if the issues is fixed or not?

**Comment by Youssef1313** [comment] 2020-08-07 18:37
@Evangelink I'll test and tell you shortly.

**Comment by Youssef1313** [comment] 2020-08-07 18:54
It still repro with `3.3.0-beta2.final`

**Comment by Youssef1313** [comment] 2020-08-07 18:56
**Note:** This doesn't repro **if** I added parenthesis after `Count`.

**Comment by Youssef1313** [comment] 2020-08-07 19:08
The VB version of the fixer wasn't updated with the same changes in 2404ec0. I suspect this could be the problem.

**Closed** 2020-09-23 21:17 UTC
Labels: Bug, Verified, in progress
