### ISSUE TITLE
Public API checker crashes when there's duplicate symbols in the txt file

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#829] opened 2016-02-03 18:50 UTC
```
CSC : error AD0001: Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An item with the same key has already been added.'. [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Compilers\Core\Portable\CodeAnalysis.csproj]
```

**Comment by mavasani** [comment] 2016-02-19 00:57
This seems like a dupe of https://github.com/dotnet/roslyn-analyzers/issues/312, which was fixed after we last upgraded our Roslyn diagnostics nuget dependency in Roslyn.sln. We just need to update Roslyn.sln to consume newer analyzers - this is currently in progress.

**Closed by mavasani** 2016-02-19 00:57 UTC
Labels: Area-Roslyn.Diagnostics.Analyzers, Bug
