### ISSUE TITLE
String Interpolation Padding Issue

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/roslyn-analyzers#3395] opened 2020-03-18 18:43 UTC
Using intellisense to simplify a string interpolation, the following code:

`{myObject.ToString().PadRight(11)}`

changes to 

`{myObject,11}`

when it should change to

`{myObject,-11}`

**Comment by sharwell** [comment] 2020-03-18 18:48
Duplicate of dotnet/roslyn#41826

**Closed by sharwell** 2020-03-18 18:48 UTC
