### ISSUE TITLE
Write code fix for DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#961] opened 2016-05-06 17:30 UTC
#### Analyzer package

System.Runtime.Analyzers
#### Analyzer

DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyAnalyzer

https://github.com/dotnet/roslyn-analyzers/pull/956 adds the analyzer, Fixer is NYI

**Comment by Youssef1313** [comment] 2021-02-10 15:15
Related to (or dupe of) https://github.com/dotnet/roslyn-analyzers/issues/1932)

**Comment by Youssef1313** [comment] 2022-12-13 17:11
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/1932

**Comment by Youssef1313** [comment] 2022-12-13 17:12
Note, fixer is already implemented, but only for `Enumerable.First`, `Enumerable.Last`, and `Enumerable.Count`.

**Closed by Youssef1313** 2022-12-13 17:11 UTC
Labels: FxCop-Port, Needs-Fixer
