### ISSUE TITLE
CA1801 Review Unused Parameters triggers on NotImplementedException methods when an argument has default value

### ISSUE THREAD

**Issue by corruptmem** [dotnet/roslyn-analyzers#1545] opened 2018-01-22 21:05 UTC
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version 2.6.1-beta1-62512-01

#### Analyzer

ReviewUnusedParameters (CA1801)

#### Repro

Method that throws NotImplementedException and at least one of the parameters has a default value. 

For example:

```csharp
using System;

namespace CodeAnalysisTest
{
    public static class Program
    {
        public static void Foo(string bar, string baz = null)
        {
            throw new NotImplementedException();
        }

        public static void Main()
        {
            Console.WriteLine("Hello World!");
        }
    }
}

```

#### Expected behavior

No error. 

There is no check triggered if the method signature is:

```csharp
public static void Foo(string bar, string baz) 
```

Setting a default parameter value should not cause a check to be triggered.

#### Actual behavior

Check fails.

````
1>Program.cs(7,39,7,42): warning CA1801: Parameter bar of method Foo is never used. Remove the parameter or use it in the method body.
1>Program.cs(7,51,7,54): warning CA1801: Parameter baz of method Foo is never used. Remove the parameter or use it in the method body.
````

**Comment by 333fred** [comment] 2018-01-22 22:16
Very likely that this is a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/1394. All of the errors @mavasani listed in that bug have a default value.

**Comment by 333fred** [comment] 2018-01-22 22:30
Yeah, this is a dupe of #1394.

**Comment by 333fred** [comment] 2018-01-22 22:32
Actually, they have similar reasons, but not quite the same fix. The issue here is that we check to see if the body of the function is just a throw operation, but we don't account for the `IParameterInitializerOperation` if its present.

**Closed** 2018-01-23 23:09 UTC
Labels: 4 - In Review, Area-Microsoft.CodeQuality.Analyzers, Bug, Noise
