### ISSUE TITLE
Adding Microsoft.Net.Compilers breaks global suppressions

### ISSUE THREAD

**Issue by yohny** [dotnet/roslyn-analyzers#3108] opened 2019-12-11 15:38 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8

#### Repro steps

1. Build a project that does not use compiler nuget and uses fxcop nuget in VS 2019. The project has some suppressed rule in GlobalSuppressions.cs.
2. Add Microsoft.Net.Compilers v2.10.0
3. Build again

#### Expected behavior

warnings remain suppressed as they were before adding Microsoft.Net.Compilers nuget

#### Actual behavior

warnings are not suppressed anymore

#### Details:
There is a minimal repro project [ConsoleApp.zip](https://github.com/dotnet/roslyn-analyzers/files/3950761/ConsoleApp.zip) attached (targeting .NET 4.6.1). This project uses FxCop nuget to perform code analysis and there is GlobalSuppressions.cs file that suppresses `CA2007` using new scope `namespaceanddescendants`. Suppression worked fine (VS2019 - 16.4.1) before I added Microsoft.Net.Compilers nuget version 2.10.0 - since then the suppressed rule warning is produced during build. Interesting think is that online source code analysis seems to remain suppressed (aka. if I navigate to the source code with the warning, it disappears)
If Microsoft.Net.Compilers is updated to 3.4.0 the warning suppression works again.

**Comment by mavasani** [comment] 2019-12-11 15:41
Can you trying moving to latest 3.x version of `Microsoft.Net.Compilers`? `namespaceanddescendants` was likely added in 3.x compiler toolset.

**Comment by yohny** [comment] 2019-12-11 16:08
With `Microsoft.Net.Compilers` 3.4.0 it works, as I stated in original issue.
The problem is that is is not documented/mentioned anywhere, that you need certain version of compiler for this to work. Its only stated that this scope is new in VS2019, which is not sufficient, because it does not work in VS2019 if you use pre-3.x compilers nuget (which is common scenario, the whole point is to decouple compiler and VS version)

**Comment by mavasani** [comment] 2019-12-11 16:13
@yohny Feel free to file a documentation bug on https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2019 to add more clarity between compiler and VS versions.

Closing this issue as this is by design.

**Closed by mavasani** 2019-12-11 16:13 UTC
