### ISSUE TITLE
Errors when using Analyzers with VS2019 for Mac

### ISSUE THREAD

**Issue by curtisconner** [dotnet/roslyn-analyzers#2503] opened 2019-05-30 10:05 UTC
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version
v2.9.2
This is what i see in my directory under packages

#### Diagnostic ID

    CSC : warning CA9999: Version mismatch between the analyzer package '2.9.0' and Microsoft.CodeAnalysis '2.8.0.0'. Certain analyzers in this package will not run until the version mismatch is fixed. Refer to https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2017#fxcopanalyzers-package-versions to install the correct analyzer version.

    CSC : warning CA9999: Version mismatch between the analyzer package '2.9.0' and Microsoft.CodeAnalysis '2.8.0.0'. Certain analyzers in this package will not run until the version mismatch is fixed. Refer to https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2017#fxcopanalyzers-package-versions to install the correct analyzer version.

#### Repro steps

1. 
VS2019 - Create new Xamarin.Forms Project.  Add the Analyzers compile on windows all is well. 
2. Open VS2019 on a mac, open the previous project, compile and see the errors

**Comment by mavasani** [comment] 2019-05-30 22:15
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2289

**Closed by mavasani** 2019-05-30 22:15 UTC
