### ISSUE TITLE
[C#] Warn for strings using $ prefix without any actual {} code.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#6680] opened 2023-06-08 22:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/369389/c-warn-for-strings-using-prefix-without-any-actual.html)._

---
The new functionality for including code inside a string to implement string formatting is exceptionally clean to read and work with. However, occasionally a developer might intend to include code inside the string, and accidentally use the wrong notation. For example, the following code has an error.var msg1 = $"Size has not been specified for (Name)!";
var msg2 = $"No size specified for Name!";These should have beenvar msg1 = $"Size has not been specified for {Name}!";
var msg2 = $"No size specified for {Name}!";Whilst a simple example from my own typos when working late at night, I imagine this could happen to anyone.

---
#### Fiona Niu [MSFT] on 10/29/2018, 02:55 AM: 

(private comment, text removed)
#### Jinu Joseph [MSFT] on 11/1/2018, 03:13 AM: 

(private comment, text removed)
#### Jorge Morales Vidal on 3/20/2020, 11:52 PM: 

(private comment, text removed)
#### Matthew Beck on 1/15/2022, 02:23 AM: 

(private comment, text removed)
#### emmabrianen@gmail.com on 5/3/2023, 01:32 AM: 

(private comment, text removed)
#### Feedback Bot on 5/4/2023, 04:50 AM: 

(private comment, text removed)

**Comment by Youssef1313** [comment] 2023-06-09 18:15
Duplicate of https://github.com/dotnet/roslyn/issues/53226

FYI @sharwell, I originally opened the above issue in dotnet/roslyn, then it was moved to roslyn-analyzers then moved back to roslyn for the compiler team as a warning wave candidate.

**Closed** 2023-06-09 18:15 UTC
