### ISSUE TITLE
AD0001: Analyzer 'Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An element with the same key but a different value already exists. Key: 'Microsoft.CodeAnalysis.Operations.LocalReferenceOperation''.

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn-analyzers#4730] opened 2021-01-22 14:46 UTC
**Version Used**:
.Net 5 SDK 5.0.102
Visual Studio Build Tools 2019 16.8.4

**Steps to Reproduce**:
Updating the code base of our program from .net core 3 to 5.
When compiling a clean build the compiler throws this warning when running exact same build.
We run the compilation using the command line and the build tools for visual studio.
However when building the program with the Visual Studio IDE this issue never happens.

**Expected Behavior**:
After trying forced package references to the newest analyzers NuGet, the problem was not solved.

**Actual Behavior**:
 AD0001: Analyzer 'Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An element with the same key but a different value already exists. Key: 'Microsoft.CodeAnalysis.Operations.LocalReferenceOperation''.

**Comment by mavasani** [comment] 2021-01-22 16:19
@ohgrad Would you be able to share either a repro project or the exception stack trace (you can get the stack trace by expanding the error in the error list)?

**Comment by mavasani** [comment] 2021-01-22 16:20
@ohgrad Can you also try installing https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/5.0.3 and see if that fixes your issue?

**Comment by neilcawse** [comment] 2021-01-24 05:03
We have the same problem and using the very latest 5.0.3 version. It reproduces with this:
if (OperatingSystem.IsWindows())
{
    new FileSecurity(fileInfo.FullName, AccessControlSections.Access).
        SetAccessRule(new FileSystemAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null), FileSystemRights.FullControl, AccessControlType.Allow));
}

CSC : error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An element with the same key but a different value already exists. Key: 'Microsoft.CodeAnalysis.Operations.FlowCaptureReferenceOperation''.

**Comment by ohgrad** [comment] 2021-01-25 09:42
@mavasani 
[stacktrace.txt](https://github.com/dotnet/roslyn-analyzers/files/5865589/stacktrace.txt)

**Comment by ohgrad** [comment] 2021-01-25 09:58
@mavasani using the package reference that you have mentioned did not solve the problem, same .csproj still throws the same problem.

**Comment by ohgrad** [comment] 2021-01-25 10:32
like @neilcawse we also use the `OperatingSystem.IsOSPlatform()` check for windows in the exact .csproj that throws the compiler warning.

**Comment by lakeman** [comment] 2021-01-27 02:02
I can reproduce the FlowCaptureReferenceOperation exception by wrapping the test in a loop;

```c#
private void Exception(IEnumerable<int> values)
{
    foreach(var v in values)
    {
        if (OperatingSystem.IsWindows())
            WindowsIdentity.GetCurrent();
    }
}
```

In this case, moving the loop body into another method may be a viable workaround.

**Comment by mavasani** [comment] 2021-01-27 04:34
Thank you, that helps! I'll investigate.

**Comment by mavasani** [comment] 2021-01-27 18:41
So I verified this issue does not repro on the latest bits. https://github.com/dotnet/roslyn-analyzers/commit/20676de948ac550979776914f5fdff0a850cf527 should have resolved this exception, we replaced the `Add` call on the dictionary with an explicit overwrite, so the exception in the given stack trace is no longer possible.

This fix first went into `release/5.0.2xx` branch, so if your analyzer assembly or SDK has this or a higher version, you shouldn't be seeing this.

Can you check the properties of the Analyzer node and verify the path of the analyzer assembly either points to an SDK path with version 5.0.2 or greater OR points to nuget package for Microsoft.CodeAnalysis.NetAnalyzers with version 5.0.3? I can confirm the following for my case:

![image](https://user-images.githubusercontent.com/10605811/106037795-fe69cf80-608b-11eb-8ef9-afc0e46db821.png)

**Comment by ohgrad** [comment] 2021-02-03 08:56
do you know when it will be officially released ? we cant use preview atm.

**Comment by Youssef1313** [comment] 2022-02-08 11:06
@lakeman Can you confirm if you're still seeing the error?

**Comment by lakeman** [comment] 2022-02-08 11:21
Since I found a workaround, I didn't commit any code sample that I can retry.
If my above reduced test case works, then it's probably fine.

**Comment by mavasani** [comment] 2022-02-08 11:23
Thanks @lakeman @Youssef1313. I am going to close this issue, please re-open if you hit this again.

**Closed by mavasani** 2022-02-08 11:23 UTC
Labels: Bug, Urgency-Soon, Area-Microsoft.NetCore.Analyzers
