### ISSUE TITLE
An instance of analyzer Microsoft.NetCore.Analyzers.Runtime.TestForNaNCorrectlyAnalyzer cannot be created

### ISSUE THREAD

**Issue by blowdart** [dotnet/roslyn-analyzers#1686] opened 2018-05-11 18:07 UTC
#### Analyzer package

Microsoft.CodeQuality.FxCopAnalyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.FxCopAnalyzers/2.6.0)

#### Analyzer

Example: TestForNaNCorrectlyAnalyzer 

#### Repro steps

1. Build from command line with dotnet build
1. Watch error appear
1. Sob

#### Expected behavior

1. Command line builds work

#### Actual behavior

1. Command line builds don't work (but building within VS *does*)

#### More info
.NET Command Line Tools (15.5.0-preview-007044)

Shared Framework Host 2.0.0

**Comment by blowdart** [comment] 2018-05-11 18:33
Which comment? The link failed :) Did you mean -

Add a NuGet package reference to https://www.nuget.org/packages/Microsoft.Net.Compilers/2.6.0 to your projects, so regardless of the Visual Studio version used for development, an explicit build (within VS or command line) will always use the 2.6.0 toolset compiler

I do have the 2.1.200 CLI installed. I went and installed 2.1.300-rc1 (15.5.0-preview-007044) and that didn't help.

**Comment by mavasani** [comment] 2018-05-11 18:50
Yes, can you please confirm the version of the compiler that you are running against? We have seen quite a few reports of this issue when an older compiler is used with 2.6.0 version of the analyzer package. The fact that analyzers work for you in VS also confirm that the issue is with a lower version compiler being used on command line.

**Comment by blowdart** [comment] 2018-05-11 19:06
How do I confirm the compiler version? :)

**Comment by blowdart** [comment] 2018-05-11 20:57
The build agent on the machine it works on is a little ahead too;

Works - 15.7.11.29948
Fails - 15.5.153.2799

But both have VS 15.7.1 and 15.8.0 dogfood on them.

**Comment by mavasani** [comment] 2018-08-07 19:01
Closing this issue as it is unrelated to analyzers package. The error is due to a lower version of compiler somehow getting invoked.

**Closed by mavasani** 2018-08-07 19:01 UTC
