### ISSUE TITLE
AD0001 in ReviewUnusedParametersAnalyzer with new test framework

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#2996] opened 2019-11-01 16:14 UTC
Moving the tests to the new test framework as shown some AD0001 errors: 

```
error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.Maintainability.ReviewUnusedParametersAnalyzer' threw an exception of type 'System.ArgumentException' with message 'The key already existed in the dictionary.'.
```

for the following tests:

- `public async Task DiagnosticForUnusedLocalFunctionParameters_01()`

- `public async Task DiagnosticForUnusedLocalFunctionParameters_02()`

- `public async Task NoDiagnosticUsedLocalFunctionParameters()`

**Comment by mavasani** [comment] 2019-11-01 17:10
Are we executing the analyzer multiple times for same compilation? If so, this needs to be fixed in the test framework to not do so.

**Comment by Evangelink** [comment] 2019-11-05 12:07
@mavasani The line raising the exception is https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs#L247

Doing a debug through the test I can confirm that the `OperationBlockEndAction` method is entered twice but I am not really sure if the new test framework is causing this double evaluation.

**Comment by sharwell** [comment] 2019-11-06 23:53
@mavasani The test framework doesn't directly invoke analyzers. It uses public APIs on the compilation.

**Comment by sharwell** [comment] 2019-11-07 00:10
The duplicate call occurs from this sequence:

https://github.com/dotnet/roslyn-sdk/blob/499b0e859144e752cb47afa3afa14b63afdc613a/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest%601.cs#L512-L513

**Comment by mavasani** [comment] 2019-11-07 00:17
Ah, thanks. I think this is likely a dupe of https://github.com/dotnet/roslyn/issues/35149, which @dotpaul filed for the same sequence of public API calls. We did not prioritize that bugs at it doesn't seem to happen from IDE or command line, but seems like we should.

**Comment by dotpaul** [comment] 2019-11-07 00:32
FWIW, I worked around that issue by only calling GetAllDiagnosticsAsync(), and filtering for diagnostics from the analyzer.

https://github.com/dotnet/roslyn-analyzers/blob/115ded2bd8c61a3b51de5c2f657e1ece26e865d1/src/Test.Utilities/DiagnosticExtensions.cs#L35

**Comment by sharwell** [comment] 2019-11-07 01:12
@dotpaul I did something similar in the test SDK. All of the tests will soon be consolidated to that implementation so we won't need to manage dual workarounds.

**Comment by Evangelink** [comment] 2019-11-07 10:30
@mavasani @sharwell In addition to the fix on Roslyn side, don't you think that might be worth updating the code to prevent the error in case such scenario does happen in "real life"?

**Closed** 2019-11-07 15:26 UTC
