### ISSUE TITLE
NuGet package claims Apache-2.0 license but contains EULA.rtf with different terms

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/roslyn-analyzers#3347] opened 2020-03-05 09:09 UTC
#### Analyzer package

[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

v2.9.8 (Latest)

#### Diagnostic ID

N/A

#### Repro steps

1. Open <https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.9.8> in a browser and see that it says "License: Apache-2.0".
2. Download `microsoft.codequality.analyzers.2.9.8.nupkg` from <https://www.nuget.org/api/v2/package/Microsoft.CodeQuality.Analyzers/2.9.8>.
3. Unzip `microsoft.codequality.analyzers.2.9.8.nupkg`.
4. Note that the unzipped `Microsoft.CodeQuality.Analyzers.nuspec` likewise contains `<license type="expression">Apache-2.0</license>` and `<licenseUrl>https://licenses.nuget.org/Apache-2.0</licenseUrl>`.
5. Look at the other extracted files.

#### Expected behavior

The NuGet package can be used and redistributed under the terms of the Apache-2.0 license, although the package could contain third-party dependencies with other compatible licenses.

#### Actual behavior

The package also contains `EULA.rtf` with "MICROSOFT PRE-RELEASE SOFTWARE LICENSE TERMS", "MICROSOFT CODE ANALYSIS 2017". These terms appear to forbid distributing the software as is, without adding primary functionality.

It is not clear which license terms I have to comply with if I redistribute the NuGet package. Was `EULA.rtf` intended to apply to VSIX packages only?

On a related note, the source repository contains both `THIRD-PARTY-NOTICES.txt` and `assets/ThirdPartyNotices.rtf`, the latter of which is also in the NuGet package. It is not entirely clear which of these is the "NOTICE" text file referenced by clause 4. (d) of the Apache-2.0 license.

**Comment by KalleOlaviNiemitalo** [comment] 2020-03-05 09:21
I noticed this issue while upgrading the analyzer packages in a project of ours. We keep track of license terms of NuGet packages used by that project. In v2.9.4, the license URL was <http://go.microsoft.com/fwlink/?LinkId=529443>, which redirects to [MICROSOFT SOFTWARE LICENSE TERMS MICROSOFT .NET LIBRARY](https://dotnet.microsoft.com/en/dotnet_library_license.htm). In v2.9.5, the license URL was changed to <https://licenses.nuget.org/Apache-2.0>, but at the same time, `EULA.rtf` was added into the package.

**Comment by KalleOlaviNiemitalo** [comment] 2020-03-09 10:24
If the source code is relicensed under the MIT license as requested in #3334, then this `EULA.rtf` issue might get fixed as part of that. It will have to be verified separately, though.

**Comment by Evangelink** [comment] 2020-04-20 12:24
@mavasani What shall be the license type?

**Comment by KalleOlaviNiemitalo** [comment] 2020-05-29 18:06
This issue also applies to [Microsoft.CodeQuality.Analyzers 3.0.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/3.0.0) and [Microsoft.CodeAnalysis.FxCopAnalyzers 3.0.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/3.0.0).

**Comment by sharwell** [comment] 2020-07-24 15:33
I will request verification of the license in the NuGet package. Keep in mind that these will not necessarily match the license that appears in the source code, e.g. https://github.com/dotnet/roslyn/issues/20169.

**Comment by Evangelink** [comment] 2020-08-06 10:22
@sharwell any update on this?

**Comment by sharwell** [comment] 2020-08-06 15:04
No update yet.

**Comment by Evangelink** [comment] 2020-11-26 09:16
Hey @sharwell sorry again for the ping, I know and understand that's not your only task but the ticket is now quite old. I feel like the priority should be raised to either make the change or close as won't fix with some explanation.

**Comment by KalleOlaviNiemitalo** [comment] 2021-04-15 07:52
This issue also applies to [Microsoft.CodeAnalysis.NetAnalyzers 5.0.3](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/5.0.3).

(EULA.rtf still says "MICROSOFT CODE ANALYSIS 2017", but according to [README.md](https://github.com/dotnet/roslyn-analyzers/blob/86736870dfee998f055c37b82bda77e5699c8cea/README.md), this package no longer supports Visual Studio 2017 and instead requires "Visual Studio 2019 16.9 RTW or later".)

**Comment by Evangelink** [comment] 2021-06-28 09:30
@mavasani @sharwell The issue is open for quite some time, would it be possible to somehow increase the priority of discussion in the matter?

**Comment by sharwell** [comment] 2021-06-30 17:57
I finally heard back on this. Sounds like the conclusion is we should remove the EULA.rtf file and allow the license metadata to be the single link to a consistent license.

**Closed** 2021-09-15 17:28 UTC
Labels: Bug, help wanted
