### ISSUE TITLE
'CompareSymbolsCorrectlyFix' encountered an error and has been disabled

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#3389] opened 2020-03-18 15:36 UTC
Hit when updating dotnet/roslyn-analyzers to Microsoft.CodeAnalysis 3.3.1.

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax'.
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SeparatedList[TNode](IEnumerable`1 nodes)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsParameterList(IEnumerable`1 parameters)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.InsertParameters(SyntaxNode declaration,Int32 index,IEnumerable`1 parameters)
   at Microsoft.CodeAnalysis.Editing.SyntaxGenerator.AddParameters(SyntaxNode declaration,IEnumerable`1 parameters)
   at async Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.Fixers.CompareSymbolsCorrectlyFix.EnsureEqualsCorrectAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.Fixers.CompareSymbolsCorrectlyFix.ConvertToEqualsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by mavasani** [comment] 2020-03-18 15:44
Tag @ryzngard

**Comment by sharwell** [comment] 2020-05-12 23:39
I just hit this again.

**Comment by sharwell** [comment] 2020-05-12 23:43
@ryzngard this occurs for any attempt to fix code of the form `x.Equals(y)`.

**Comment by Youssef1313** [comment] 2020-05-28 16:08
The exception is thrown at the `generator.AddParameters` call in the private method `EnsureEqualsCorrectAsync`.

I don't know the exact problem but I think of **only** two possibilities:

1. `generator.AddParameter` is given some wrong input, in that case, there is another problem that the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.editing.syntaxgenerator.addparameters?view=roslyn-dotnet#Microsoft_CodeAnalysis_Editing_SyntaxGenerator_AddParameters_Microsoft_CodeAnalysis_SyntaxNode_System_Collections_Generic_IEnumerable_Microsoft_CodeAnalysis_SyntaxNode__) is missing specifying that the method can throw exception.

2. `generator.AddParameters` should never throw, in that case, the problem is in [dotnet/roslyn 's SyntaxGenerator](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L1058).

**Comment by Youssef1313** [comment] 2020-10-14 20:38
@sharwell @mavasani This is already fixed in https://github.com/dotnet/roslyn-analyzers/pull/3979

**Comment by Evangelink** [comment] 2020-12-09 18:03
@sharwell could you confirm that's ok?

**Comment by Evangelink** [comment] 2020-12-16 16:57
Ping @sharwell

**Comment by Evangelink** [comment] 2021-07-22 13:05
Ping @sharwell @mavasani

**Comment by Youssef1313** [comment] 2022-12-10 19:26
Closing as already fixed.

**Closed by Youssef1313** 2022-12-10 19:26 UTC
Labels: Bug, Area-Microsoft.CodeAnalysis.Analyzers, Urgency-Soon
