### ISSUE TITLE
Rules enable using AnalysisMode.All don't respect severity from dotnet_analyzer_diagnostic

### ISSUE THREAD

**Issue by leoniDEV** [dotnet/roslyn-analyzers#6018] opened 2022-06-04 22:50 UTC
**Version Used**: 
VisualStudio.17.Preview/17.3.0-pre.1.1+32519.111
.net 7.0.100-preview.4.22252.9

**Steps to Reproduce**:

1. create a C# project
2. add the property `<AnalysisMode>all</AnalysisMode>` to the .csproj file
3. add a `.globalconfig` file with `dotnet_analyzer_diagnostic.severity = error`

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)

**Expected Behavior**:
According to the docs [here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#scope), the severity for all rules need to be `error`, even the ones disabled by default

**Actual Behavior**:
The rules enabled by default honor the key `dotnet_analyzer_diagnostic.severity`, the ones which aren't enabled by default don't
![image](https://user-images.githubusercontent.com/11667486/172027695-cdeb64b8-8a9f-4473-be65-2a627ba4d2e7.png)

**Comment by mavasani** [comment] 2022-06-05 00:23
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5077

**Closed by mavasani** 2022-06-05 00:23 UTC
