### ISSUE TITLE
An instance of analyzer Microsoft.CodeQuality.Analyzers.QualityGuidelines.AvoidDuplicateElementInitialization cannot be created from...

### ISSUE THREAD

**Issue by osudude** [dotnet/roslyn-analyzers#3346] opened 2020-03-05 00:00 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.6 

#### Repro steps

Turned on code analyzer in visual studio for C# project : Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.6
Turned off Binary analyzers.  

#### Expected behavior
Works fine in VS2019.
Encounters errors on TFS 2017 build server.  What version of TFS is required for Microsoft.CodeAnalysis.FxCopAnalyzers support?

#### Actual behavior
TFS Build error
CSC (0, 0)
CSC(0,0): Warning CS8032: An instance of analyzer Microsoft.CodeQuality.Analyzers.QualityGuidelines.AvoidDuplicateElementInitialization cannot be created from C:\TFS2017BuildAgent\_work\232\s\packages\Microsoft.CodeQuality.Analyzers.2.9.6\analyzers\dotnet\cs\Microsoft.CodeQuality.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by mavasani** [comment] 2020-03-05 00:02
You need at least VS2017 15.9

**Comment by osudude** [comment] 2020-03-05 00:13
Just checked and we are currently running TFS Version 15.117.27414.0

**Comment by mavasani** [comment] 2020-05-05 18:30
Thanks for confirming. Closing this as by design. Please move to version 15.9 at least

**Closed by mavasani** 2020-05-05 18:30 UTC
