### ISSUE TITLE
Ability to provide diagnostics and code fixes for project files

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-analyzers#1273] opened 2017-07-29 21:22 UTC
Has this been considered?

One use case I have is a NuGet MSBuild task which adds `<KnownUnreferencedAssembly Include="OutputFilename.dll" Keep="true|false" />` metadata to the project and trims the build output. I'd like to provide a diagnostic that takes you to the lines in the .csproj with a quick fix to add required elements and remove or correct invalid elements.

Another use case is to fail the build if the .csproj contains a reference to license.licx with the ability to navigate to the csproj line from the error list and use a quick fix to remove it.

It would be super cool to be able to register actions with access to the project rather than the compilation. I don't even need access to the syntax or semantic model.

**Comment by sharwell** [comment] 2017-07-30 03:32
:bulb: This is closely related to dotnet/roslyn#11097. Several additional issues are linked to the first comment there.

**Comment by mavasani** [comment] 2017-11-10 17:45
Closing as dupe of dotnet/roslyn#11097. Kindly follow/comment on that issue.

**Closed by mavasani** 2017-11-10 17:45 UTC
