### ISSUE TITLE
CA1811: AvoidUncalledPrivateCode, not working if class contains a typeof() call

### ISSUE THREAD

**Issue by nicorac** [dotnet/roslyn-analyzers#2193] opened 2019-03-12 08:54 UTC
I've seen other issues mentioning rule CA1811, so I suppose this is the right place to post this one.

The rule stops working if the source code contains a call to typeof(), either in class code or in a class attribute (like `[ToolboxBitmap]`). The argument of `typeof()` must be the class itself.

#### VisualStudio version
Microsoft Visual Studio Community 2017 
Version 15.9.8

#### Repro steps

1. Enable rule CA1811
2. Add the following source code to project
```
namespace TestNamespace
{
    // ========================================================
    // Uncomment the line below and the CA1811 rule won't trigger anymore...
    // ========================================================
    //[System.Drawing.ToolboxBitmap(typeof(TestClass), "image.bmp")]
    public class TestClass
    {
        private void TestMethod()
        {
            // ========================================================
            // Uncomment the line below and the CA1811 rule won't trigger anymore...
            // ========================================================
            //System.Console.WriteLine(typeof(TestClass).ToString());
        }

        private void UncalledMethod()
        {
            System.Console.WriteLine("This method is not called...");
        }
    }
}
```
3. run code analysis on the code and it will trigger two CA1811 warnings on the 2 class methods
4. uncomment the `[ToolboxBitmap]` class attribute
5. run code analysis again and now the warnings do not trigger
6. comment back the attribute and uncomment the body of `TestMethod()` method
7. run code analysis again and the warnings do not trigger again

#### Expected behavior
CA1811 triggering should be unrelated to `typeof()` calls...

#### Actual behavior
Adding a call to `typeof()` anywhere in a class brokes CA1811 rule.

#### Note
Update: the argument of `typeof()` must be the class itself for the rule to break.

**Comment by mavasani** [comment] 2019-07-01 23:37
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/464

This rule has not yet been implemented in FxCop analyzers package. We have an equivalent implementation in VS IDE that flags unused private members.

**Closed by mavasani** 2019-07-01 23:37 UTC
