### ISSUE TITLE
Handle whitespaces in Microsoft.CodeAnalysis.Metrics.targets

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3732] opened 2020-06-09 18:06 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.Metrics](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Metrics)

#### Package Version

3.3.0 (Latest)

#### Behavior

Hi!
The command line invocation of the package fails for project- or out-parameters containing white-spaces. I was able to solve the problem by surrounding the parameters with quotation marks in the Microsoft.CodeAnalysis.Metrics.targets file accordingly:

```xml
<Exec Command='&quot;$(MetricsExeFolder)$(MetricsExeName).exe&quot; /project:"$(MSBuildProjectFullPath)" /out:"$(MetricsOutputFile)"' WorkingDirectory="$(MSBuildProjectDirectory)">
 </Exec>
```
I hope you will be able to include a fix for this issue in future releases.
Best regards Alexander Penner

**Comment by Youssef1313** [comment] 2022-12-13 18:01
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5477

**Closed by Youssef1313** 2022-12-13 18:01 UTC
Labels: Bug, help wanted, Area-CodeMetrics
