### ISSUE TITLE
CA1031 incorrectly fires on derived exceptions if no variable is assigned

### ISSUE THREAD

**Issue by fschlaef** [dotnet/roslyn-analyzers#2854] opened 2019-09-17 09:16 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

[2.9.5-beta1.final](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.5-beta1.final)

#### Diagnostic ID

[CA1031](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1031-do-not-catch-general-exception-types?view=vs-2019)

#### Repro steps

```csharp
try
{
    //something
}
catch (CustomException)
{

}
```

#### Expected behavior

No warning

#### Actual behavior

Warning	CA1031	Modify 'MyFunction' to catch a more specific exception type, or rethrow the exception.

#### Workaround

```csharp
try
{
    //something
}
catch (CustomException e)
{

}
```

Alternative

```csharp
try
{
    //something
}
catch (CustomException)
{
    //something
    throw;
}
```

**Comment by mavasani** [comment] 2019-09-17 11:32
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2518. Verified this does not repro on 2.9.4 or 2.9.5-beta1.final packages.

**Closed by mavasani** 2019-09-17 11:32 UTC

**Comment by fschlaef** [comment] 2019-09-17 11:53
@mavasani I don't know how you verified this but this is trivial to reproduce.

[CA1031Repro.zip](https://github.com/dotnet/roslyn-analyzers/files/3621096/CA1031Repro.zip)

.Net Core 3, VS 2019 Preview 4

![ca1031](https://user-images.githubusercontent.com/29452252/65039412-80070480-d952-11e9-883e-b1bc0cf9620a.png)

**Comment by mavasani** [comment] 2019-09-17 12:00
@fschlaef I opened your project in latest VS2019 16.3 preview drop and I don't see this:

![image](https://user-images.githubusercontent.com/10605811/65039705-b23f4480-d907-11e9-8151-d2f7a0c9c0df.png)

Additionally, your screenshot shows the CA1031 squiggle spans the entire catch block, which was explicitly fixed to only span the catch keyword prior to version 2.9.4 of the analyzer package with https://github.com/dotnet/roslyn-analyzers/pull/2519. So you are almost certainly on an older package. Have you installed https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MicrosoftCodeAnalysis2019 by any chance?

**Comment by fschlaef** [comment] 2019-09-17 12:04
@mavasani spot on ! I had indeed installed this extension. After removal, no more warning.

Thank you very much ! 👍
