### ISSUE TITLE
CA1063 and CA1821 when finalizer is an expression-bodied method

### ISSUE THREAD

**Issue by pharring** [dotnet/roslyn-analyzers#1702] opened 2018-05-22 20:26 UTC
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

Microsoft.CodeQuality.Analyzers (CA1063) Implement IDisposable correctly
Microosft.CodeQuality.CSharp.Analyzers (CA1821) Remove empty Finalizers

#### Repro steps

Compile this with the default ruleset:

```C#
using System;
using System.IO;

public class YourClass : IDisposable
{
    private readonly IDisposable disposable = new MemoryStream();

    ~YourClass() => Dispose(false);

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (disposing)
        {
            disposable.Dispose();
        }
    }
}
```

#### Expected behavior
No analyzer errors.

#### Actual behavior
```
1>C:\Throwaway\ClassLibrary3\ClassLibrary3\Class1.cs(8,6,8,15): warning CA1063: Modify YourClass.Finalize so that it calls Dispose(false) and then returns.
1>C:\Throwaway\ClassLibrary3\ClassLibrary3\Class1.cs(8,6,8,15): warning CA1821: Remove empty Finalizers
```

**Comment by mavasani** [comment] 2018-05-22 20:30
This is a dupe of https://github.com/dotnet/roslyn-analyzers/issues/1607, which was dupe of Roslyn bug https://github.com/dotnet/roslyn/issues/26520, the latter just got fixed recently in Roslyn and should be part of next VS update (15.8)

**Closed by mavasani** 2018-05-22 20:30 UTC
Labels: Resolution-External

**Comment by pharring** [comment] 2018-05-22 20:48
OK. Sorry for the noise.

**Comment by mavasani** [comment] 2018-05-22 21:07
@pharring No worries at all. Always appreciate your feedback, please keep those coming!
