### ISSUE TITLE
CA1801 doesn't recognize if a parameter is used in an interpolated string

### ISSUE THREAD

**Issue by dpaoliello** [dotnet/roslyn-analyzers#1029] opened 2016-05-25 20:58 UTC
#### Analyzer package

Microsoft.Maintainability.Analyzers

#### Analyzer

ReviewUnusedParameters

#### Repro steps

Compile the following code with the Maintainability analyzer enabled:

```csharp
public static class Foo
{
    public static string Transform(int someData)
    {
        return $"Hello {someData}";
    }
}
```
#### Expected behavior
No errors

#### Actual behavior
`warning CA1801: Parameter someData of method Transform is never used. Remove the parameter or use it in the method body.`

**Comment by mavasani** [comment] 2016-06-10 22:51
This is dupe of https://github.com/dotnet/roslyn/issues/8884#issuecomment-217131239

**Closed by mavasani** 2016-06-10 22:51 UTC
