### ISSUE TITLE
CA1801 warning shown on build/analysis, disappears when source file is opened

### ISSUE THREAD

**Issue by markashleybell** [dotnet/roslyn-analyzers#1713] opened 2018-06-06 09:54 UTC
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers, version [2.6.1](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.1)

#### Analyzer

ReviewUnusedParameters

#### Repro steps

I have several custom error types in my project, all derived from a base type:

    public class Error
    {
        public Error(string description)
            : this(description, null) { }

        public Error(Exception exception)
            : this(exception?.Message, exception) { }

        public Error(string description, Exception exception)
        {
            Description = description;
            Exception = exception;
        }

        public virtual string Description { get; }

        public virtual Exception Exception { get; }
    }

    public class PathNotFoundError : Error
    {
        public PathNotFoundError(string path, Exception exception)
            : base(exception) => Description = $"{path} was not found";

        public override string Description { get; }
    }

When I run code analysis in VS2017 (`ALT+F11`) or build the solution, I get a bunch of CA1801 warnings in the Error List referring to the subclassed error types. For the example above the error is:

    Warning CA1801 Parameter path of method .ctor is never used. Remove the parameter or use it in the method body.

However, that parameter _is_ used, and indeed when I double-click the warning in the error list, as soon as the source file opens in VS the warning disappears.

#### Expected behavior

CA1801 warning should not appear in this case.

#### Actual behavior

CA1801 warnings are added to error list when Code Analysis is run or on solution build, but disappear on opening the source file.

**Comment by mavasani** [comment] 2018-06-06 12:30
Dupe of https://github.com/dotnet/roslyn-analyzers/issues/1713 and https://github.com/dotnet/roslyn-analyzers/issues/1559.

FYI @jinujoseph @heejaechang, error list behavior is due to compilation end action bug.

**Comment by sharwell** [comment] 2018-06-06 12:30
> Parameter path of method .ctor is never used.

@mavasani do we have a bug that this should have included quotes, like this?

> Parameter 'path' of method '.ctor' is never used.

**Closed** 2018-06-06 12:31 UTC
Labels: Bug, Resolution-Duplicate

**Comment by mavasani** [comment] 2018-06-06 12:32
@sharwell I do not believe so. I think quite a few of our diagnostic messages were created by an automated tool that ported messages from old FxCop implementation. I will file an issue to audit the messages.

**Comment by markashleybell** [comment] 2018-06-06 13:33
Thanks for taking a look; however, I don't think this is a duplicate. 

After enabling full solution analysis (which I _think_ seems to be the suggested fix from reading through some other referenced issues), the inconsistency with the disappearing messages is gone. So that part, I would agree, is covered by the other issue.

But the real issue is that I shouldn't see the `CA1801` warning _at all_ in this case, as the parameter _is_ used in the constructor. Should I create a separate issue for that, or edit this one?

**Comment by mavasani** [comment] 2018-06-06 13:37
@markashleybell Sorry, my bad that I put a wrong dupe ID in https://github.com/dotnet/roslyn-analyzers/issues/1713#issuecomment-395051399. The other issue is dupe of #1606, which was recently fixed in Roslyn and should not repro in VS15.8
