### ISSUE TITLE
CA1062: false positive on `is null`

### ISSUE THREAD

**Issue by SebastianSchumann** [dotnet/roslyn-analyzers#3899] opened 2020-07-23 13:56 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

Example: [CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062)

#### Repro steps

    public void Foo(object instance)
    {
        if (instance is { })
        {
            _ = instance.GetHashCode();
        }
    }

I found #2692 that told me that this should be fixed right now - but it's still there.

#### Expected behavior

No CA1062 should be reported.

#### Actual behavior

CA1062 is reported.

**Comment by Youssef1313** [comment] 2020-07-25 12:55
@Evangelink Not familiar with DFA, do you know if the problem is relying in [this file](https://github.com/dotnet/roslyn-analyzers/blob/44e730f45726ad7ef7716aa901d66036ffd2eb2c/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs)?

**Comment by Evangelink** [comment] 2020-07-25 19:37
@Youssef1313 I don't know, I will try to do a little debugging session to see if I can find some pointers to help on this.

**Comment by Evangelink** [comment] 2020-09-30 12:05
Looks like the bug was fixed in between, I have added some tests.

**Closed** 2020-09-30 12:05 UTC
Labels: False_Positive, Resolution-Fixed
