### ISSUE TITLE
In web api, if I call a post or put method inside a get method, it should give an error or warning

### ISSUE THREAD

**Issue by vibhu12345** [dotnet/roslyn-analyzers#3144] opened 2020-01-04 09:10 UTC

**Comment by carlossanlop** [comment] 2020-10-28 20:20
Can you please add a more detailed description?

We need usage examples of the APIs that would be affected by this rule.

**Comment by Youssef1313** [comment] 2022-12-31 08:58
dotnet/aspnetcore maintains their own set of analyzers.

@captainsafia Is the request here clear enough for you to move forward in dotnet/aspnetcore?

**Comment by captainsafia** [comment] 2023-01-03 04:07
@Youssef1313 I believe what is proposed here is a duplicate of the issue that is filed in https://github.com/dotnet/aspnetcore/issues/35727

**Comment by Youssef1313** [comment] 2023-01-03 04:53
Thanks @captainsafia

Closing as a duplicate of dotnet/aspnetcore#35727

**Closed by Youssef1313** 2023-01-03 04:53 UTC
Labels: Feature Request, Need More Info, Needs-Review, Area-Microsoft.NetCore.Analyzers
