### ISSUE TITLE
Can you please update extension in marketplace?

### ISSUE THREAD

**Issue by Krakean** [dotnet/roslyn-analyzers#2147] opened 2019-02-23 16:01 UTC
Subj.
Currently, on visual studio marketplace this extension has 2.6.0 version. Can you please update it to 2.6.3? Or may be release 2.6.4 (its ~200 commits since 2.6.3, after all) and update it on marketplace?

**Comment by mavasani** [comment] 2019-07-01 23:18
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2034

**Closed by mavasani** 2019-07-01 23:18 UTC
