### ISSUE TITLE
CA2101 false positive

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#5711] opened 2021-11-09 20:29 UTC
### Analyzer

**Diagnostic ID**: [CA2013](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2101): `Specify marshaling for P/Invoke string arguments`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 6.0.0 (Latest)

### Describe the bug

CA2101 fires for the Win32 API that expects ANSI strings as an input.

### Steps To Reproduce

Provide the steps to reproduce the behavior:
1. Create a simple C# console application project.
2. Configure CA2101.
3. Add DllImport of a Win32 API that expects ANSI string as an input.
4. Compile.

### Expected behavior

CA2101 fires.

### Actual behavior

CA2101 should not fire.

## Additional context

See attached sample project.
[CA2101.ZIP](https://github.com/dotnet/roslyn-analyzers/files/7507775/CA2101.ZIP)

**Comment by Youssef1313** [comment] 2022-07-17 11:27
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5479

**Closed** 2022-07-17 11:35 UTC
