### ISSUE TITLE
Wrong wordin an error message

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#5752] opened 2021-12-01 18:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Wrong-wordin-an-error-message/1599340)._

---
When using Visual Basic, the bolded word should be "Shared"

Member '<Some Member>' does not access instance data and can be marked as **static**

---
#### Feedback Bot on 11/30/2021, 10:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2021-12-01 19:59
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5704.

**Closed** 2022-01-24 17:36 UTC
Labels: Resolution-Duplicate
