### ISSUE TITLE
dotnet build doesn't terminate in 5.0.200, same code compiles in previous version.

### ISSUE THREAD

**Issue by emmisberger** [dotnet/roslyn-analyzers#4920] opened 2021-03-03 16:27 UTC
**Version Used**: 5.0.200

**Steps to Reproduce**:

1.  Create an empty C# project (dotnet new console)
2.  Run ` dotnet add package Microsoft.Win32.Registry`
3.  Replace Program.cs with the following code:
```cs
using System.Runtime.InteropServices;
using Microsoft.Win32;

if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && Registry.GetValue("", "", null) != null)
{
    foreach (var x in new string[0])
    {
        if ("".ToString() == "")
        {
            try
            {
            }
            catch
            {
            }
        }
    }
}
```

**Expected Behavior**:
`dotnet build` compiles the project

**Actual Behavior**:
`dotnet build` hangs indefinitely.

**Comment by jaredpar** [comment] 2021-03-03 16:39
This looks to be handing in the platform compatibility analyzer. Confirmed that disabling analyzers causes the build to succeed. 

It's possible that there is a bug in the underlying data flow APIs that is the root here. If so please kick back to compilers.

@mavasani, @jmarolf, @sharwell

**Comment by sharwell** [comment] 2021-03-03 16:58
What version of the compiler is included with 5.0.200? I'm not able to reproduce this in the Platform Compatibility Analyzer tests with either 3.8.0 or 3.9.0.

**Comment by sharwell** [comment] 2021-03-03 16:59
Here's the test I wrote:

```
        [Fact]
        [WorkItem(4920, "https://github.com/dotnet/roslyn-analyzers/issues/4920")]
        public async Task FailureToTerminate()
        {
            var source = @"
using System.Runtime.InteropServices;
using Microsoft.Win32;

if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && Registry.GetValue("""", """", null) != null)
{
    foreach (var x in new string[0])
    {
        if ("""".ToString() == """")
        {
            try
            {
            }
            catch
            {
            }
        }
    }
}";

            await new VerifyCS.Test
            {
                ReferenceAssemblies = ReferenceAssemblies.Net.Net50.AddPackages(
                    ImmutableArray.Create(new PackageIdentity("Microsoft.Win32.Registry", "5.0.0"))),
                LanguageVersion = CSharpLanguageVersion.CSharp9,
                TestState =
                {
                    OutputKind = OutputKind.ConsoleApplication,
                    Sources = { source },
                    AnalyzerConfigFiles = { ("/.editorconfig", s_msBuildPlatforms) },
                }
            }.RunAsync();
        }
```

**Comment by mavasani** [comment] 2021-03-03 17:01
Tagging @buyaa-n as well in case she is aware of this issue or a fix that was done.

**Comment by emmisberger** [comment] 2021-03-03 17:04
@sharwell `dotnet csc.dll -v` shows me the following:
Microsoft (R) Visual C# Compiler version 3.9.0-5.21120.8 (accdcb77)

**Comment by jaredpar** [comment] 2021-03-03 17:06
Here is the project file that I'm using + the global.json 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RunAnalyzers>true</RunAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>

</Project>

```

```json
{
  "sdk": {
    "version": "5.0.200"
  }
}
```

Confirmed that this does use 5.0.200 on my machine 

```cmd
C:\Users\jaredpar\temp\console> dotnet --version
5.0.200
```

**Comment by buyaa-n** [comment] 2021-03-03 17:57
Hm, I was not aware of this issue, i can repro with a sample console app. There is something related to `Registry.GetValue("""", """", null) != null` condition, if I use any other condition it builds just fine

**Comment by sharwell** [comment] 2021-03-03 19:24
I wasn't able to reproduce this on 3.8.0, 3.9.0-5.final, or 3.9.0. I'm going to submit a regression test. I'm guessing one of the following occurred:

1. The non-termination was in a different analyzer than PlatformCompatibilityAnalyzer
1. This was fixed in the analyzers since the last time it was inserted for the .NET 5.0 SDK
1. There is a difference in the value for `build_property._SupportedPlatformList` between the test above and my regression test, and that somehow makes a difference
1. Somehow there is a bug between 3.9.0-5.final and the version in 5.0.200? This one seems unlikely.

**Comment by sharwell** [comment] 2021-03-03 19:25
@jaredpar Can you add a copy of the **.globalconfig** produced during your test build above?

**Comment by sharwell** [comment] 2021-03-03 19:27
Oh, I was finally able to reproduce this by changing the **.globalconfig**.

**Comment by buyaa-n** [comment] 2021-03-04 00:23
Thanks, @sharwell i was able to repro with a similar unit test, it is a very strange edge case, if remove the guard method it builds just fine
```cs
// Builds fine
if (Registry.GetValue("", "", null) != null)
{
    foreach (var x in new string[0])
    {
        if ("""".ToString() == """")
        {
            try
            {
            }
            catch
            {
            }
        }
    }
}
```
If remove any of the blocks inside it also builds (loop or try catch or if condition)
```cs
// Builds fine
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && Registry.GetValue("", "", null) != null)
{
    foreach (var x in new string[0])
    {
        if ("""".ToString() == """")
        {
        }
    }
}
```
When debug the flow analysis result is not returning, seems flow analysis bug

**Comment by buyaa-n** [comment] 2021-03-04 00:27
> I'm guessing one of the following occurred:
> 
> 1. The non-termination was in a different analyzer than PlatformCompatibilityAnalyzer
> 2. This was fixed in the analyzers since the last time it was inserted for the .NET 5.0 SDK
> 3. There is a difference in the value for build_property._SupportedPlatformList between the test above and my regression test, and that somehow makes a difference
> 4. Somehow there is a bug between 3.9.0-5.final and the version in 5.0.200? This one seems unlikely.

After debugging, it is happening in PlatformCompatibilityAnalyzer, doesn't seem fixed as i used the latest from master

**Comment by sharwell** [comment] 2021-03-04 00:37
@buyaa-n Yeah that comment was outdated. Once I fixed the **.globalconfig** file I was able to reproduce this and submitted #4923 with the test.

Yes, I also commented today to @mavasani that we need analyzer callbacks for AnalyzerConfig documents in the compiler. Too many cases where lines get silently ignored due problems that could be easily detected and reported by analyzers.

**Comment by sharwell** [comment] 2021-03-04 00:38
The test is now merged. The issue is not fixed, but writing the test is tricky so this will hopefully same someone time when they go to investigate this.

**Comment by buyaa-n** [comment] 2021-03-04 00:47
@sharwell got it, thanks for the tests

**Comment by jaredpar** [comment] 2021-03-04 04:22
Seen at least two instances of this bug pretty much immediately after release. This seems very likely to need to go through servicing.

**Comment by Youssef1313** [comment] 2021-03-04 05:34
In `DataFlowOperationVisitor` I see the test stuck at `VisitInvocation`. It's called, and finishes executing, then called again, then called again, etc.

**Comment by Youssef1313** [comment] 2021-03-04 05:51
And finally, here is the infinite loop:

https://github.com/dotnet/roslyn-analyzers/blob/3fb878177fb161344a57784957485450544e0f84/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs#L197

**Comment by nickwhaley** [comment] 2021-03-04 14:23
Worth looking at duplicate dotnet/roslyn#51652 . It fails in older versions also, but with a warning instead of a lockup. In case that helps diagnosis:

`Warning AD0001 Analyzer 'Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An element with the same key but a different value already exists. Key: 'Microsoft.CodeAnalysis.Operations.LiteralOperation''.`

**Comment by mavasani** [comment] 2021-03-05 10:12
I have a fix for this issue: https://github.com/dotnet/roslyn-analyzers/pull/4928

@jaredpar @terrajobst @jeffhandley @vatsalyaagrawal would this be a candidate for .NET5 servicing fix?

**Comment by jaredpar** [comment] 2021-03-05 14:54
There were two reports within the first few days of the SDK being released which speaks a bit about impact to me. 

How corner case is the scenario though? It's hard to tell from the bug. If it's decently mainstream I'd vote for pushing through servicing at this point.

**Comment by mavasani** [comment] 2021-03-05 16:17
Apparently my fix does not fix the second hang: https://github.com/dotnet/roslyn/issues/51652. I'll continue investigating.

> How corner case is the scenario though

Both cases are when there are platform guard checks inside/outside a loop with a try/catch inside a loop.

**Comment by mavasani** [comment] 2021-03-06 22:54
> Apparently my fix does not fix the second hang: dotnet/roslyn#51652. I'll continue investigating.

Latest commit https://github.com/dotnet/roslyn-analyzers/pull/4928/commits/44fb5c42eaa4e75901c15175aa2175cb5c78d9f6 for https://github.com/dotnet/roslyn-analyzers/pull/4928 fixes dotnet/roslyn#51652.

**Closed** 2021-03-09 02:29 UTC
Labels: Area-Microsoft.NetCore.Analyzers, Bug, Urgency-Soon

**Comment by nickwhaley** [comment] 2021-11-19 15:36
This problem has reappeared in SDK 5.0.403.

Problem does not exist however in SDK 6.0.100.

**Comment by buyaa-n** [comment] 2021-11-19 18:09
There is something wrong with the latest `SDK 5.0.403`, [another bug also reported](https://github.com/dotnet/roslyn-analyzers/issues/5728) @jmarolf @mavasani PTAL
