### ISSUE TITLE
CA1062 raised if Contract.Requires uses TException 

### ISSUE THREAD

**Issue by azegallo** [dotnet/roslyn-analyzers#3030] opened 2019-11-09 23:24 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.7 (Latest)

#### Diagnostic ID

[CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019)

#### Repro steps

1. Inside a method use `Contract.Requires<ArgumentNullException>(param != null)`

#### Expected behavior
Nothing.

#### Actual behavior
CA1062 raised

CA1062 not raised if the TException is not used.

**Comment by Evangelink** [comment] 2020-01-08 13:05
@mavasani My understanding is that CodeContracts is deprecated so I am wondering whether we should add this exception.

**Comment by Evangelink** [comment] 2020-12-18 09:25
Is there something we want to do on this rule? I see it is disabled and meant to be replaced by a compiler warning.

Do we want to deprecate this rule and remove it on the `release/6.0.1xx-preview1` branch?

cc @mavasani

**Comment by mavasani** [comment] 2020-12-18 16:45
> Do we want to deprecate this rule and remove it on the release/6.0.1xx-preview1 branch?

I do not think we want to deprecate CA1062. I am also not sure if it is planned to be replaced with a compiler warning. It is disabled by default as it uses dataflow analysis, and hence can be noisy + expensive to be enabled by default.

I think we certainly want to update CA1062 messaging to remove the words that recommend use of Code contracts.

**Comment by Evangelink** [comment] 2020-12-21 09:15
> I do not think we want to deprecate CA1062. I am also not sure if it is planned to be replaced with a compiler warning. It is disabled by default as it uses dataflow analysis, and hence can be noisy + expensive to be enabled by default.

My comment was based on the comment left next to the `Disabled` state of the rule (see
https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ValidateArgumentsOfPublicMethods.cs#L27)

> I think we certainly want to update CA1062 messaging to remove the words that recommend use of Code contracts.

Do we want to simply remove this mention or change it to recommend [System.Diagnostics.Contracts.Contract](https://docs.microsoft.com/dotnet/api/system.diagnostics.contracts.contract?view=net-5.0)?

**Comment by Youssef1313** [comment] 2022-12-10 17:49
> I think we certainly want to update CA1062 messaging to remove the words that recommend use of Code contracts.

Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/3134

**Closed by Youssef1313** 2022-12-10 17:49 UTC
Labels: Needs-Review, False_Positive
