### ISSUE TITLE
PublicApiAnalyzer RS0016 no quick action for forwarded types

### ISSUE THREAD

**Issue by RussKie** [dotnet/roslyn-analyzers#3228] opened 2020-01-21 00:58 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.PublicApiAnalyzer](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzer)

#### Package Version

v2.9.8 (Latest)

#### Diagnostic ID

RS0016

#### Repro steps

1. Clone https://github.com/RussKie/winforms.git @ c0ff9f0549d5c95bee6dc3d421ad9f660ff4ea12
2. Open in VS
3. Compile in Release mode
4. Hover the squeegees and observe no quick actions for fixing RS0016, though tooltips contain information.

#### Expected behavior

Quick actions are available.

#### Actual behavior

![quick-action-missing](https://user-images.githubusercontent.com/4403806/72766736-49fdc800-3c45-11ea-9b2e-6500fd2e7318.gif)

**Comment by mavasani** [comment] 2020-04-24 23:15
@RussKie Couple of things to note:

1. The core issue here is that type forwarded are assembly level attributes, hence the public API analyzer processes them after the entire compilation/project has been analyzed (compilation end actions). This in turn means they are not analyzed for active file analysis - you would have noticed that you do not get squiggles by just opening the file, but you have to build the project to see them.
2. You can workaround this issue by doing the following:
   1. Define a dummy type, say `public class C { }` at the end of this file.
   2. When you put your cursor on this type definition, you should see a code fix to add 'C' to public API file
   3. Instead of invoking this code fix, invoke "Fix All" in "Project":
![FixAllInProject](https://user-images.githubusercontent.com/10605811/80263580-e8833600-8645-11ea-879b-f2e5a9742552.png)
   4. In the "Preview Changes" dialog that comes up, uncheck the first check box for "C" and hit enter to apply rest of the changes      
![FixAllInProject_PreviewChanges](https://user-images.githubusercontent.com/10605811/80263708-56c7f880-8646-11ea-8fcc-e631b695da3b.png)

   5. Remove the dummy type 'C' added in step 1.

I verified that the above steps work fine.

I am proposing that we won't fix/by design this issue unless:
1. We get more customer requests that this is a very common feature that needs to work by default.
2. The workaround provided above does not work

**Comment by mavasani** [comment] 2020-04-27 15:55
Closing this as by design. This can be re-considered if we have enough end user requests where the above workaround does not work or is not acceptable.

**Closed by mavasani** 2020-04-27 15:55 UTC
Labels: Area-DotNetAnalyzers.PublicApiAnalyzer, Resolution-By Design
