### ISSUE TITLE
Support nullable reference types with CA1602

### ISSUE THREAD

**Issue by chriskuech** [dotnet/roslyn-analyzers#4989] opened 2021-03-31 21:40 UTC
### Analyzer

**Diagnostic ID**: [CA1602](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1062)

### Describe the improvement
CA1602 ensures that callers cannot pass `null` to public methods unexpectedly.  If a parameter is a nullable reference type, then this rule should not be raised because `null` is expected and will be handled safely in accordance with CA8602.

### Describe suggestions on how to achieve the rule
Check if the parameter target of this rule is a nullable reference type.  If it is a nullable reference type, then do not flag the parameter.

### Additional context
Due to C#/dotnet's implementation of nullable reference types, public methods cannot trust that their parameters are not null, even if nullable reference types are enabled and the parameter is declared not null.  This causes the static and dynamic type systems to fall out of sync.  CA1602 solves this for the case where the parameter is declared not null and the caller passes null, but CA1602 still raises if parameter is declared nullable.  The motivation behind CA1602 should be maintaining an accurate static type system (such that the CA8602 can catch null dereferences), and therefore changing the parameter type to a nullable reference type should be a permissible solution to this rule.

**Comment by mavasani** [comment] 2021-05-06 18:04
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/3218

**Closed by mavasani** 2021-05-06 18:04 UTC
