### ISSUE TITLE
RS1025 (Configure generated code analysis) false positive for empty Initialize method

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#4101] opened 2020-08-31 14:25 UTC
### Analyzer

**Diagnostic ID**: [RS1025](https://docs.microsoft.com/visualstudio/code-quality/rs1025): **Configure generated code analysis**

### Analyzer source

**Version**: v3.3.0 (Latest)

### Describe the bug

RS1025 should not be reported for empty `Initialize` methods, e.g.:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/441ef9728ef0ffc529b784fbde51b5ea7be98ecf/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1603DocumentationMustContainValidXml.cs#L41-L46

**Comment by mavasani** [comment] 2020-09-15 16:13
@Evangelink @sharwell I am not sure this is an issue that should be fixed. An analyzer should ideally never have stub implementation that returns non-empty descriptors, but has an empty Initialize method.  For the above cited analyzer, a better approach seems to be just delete the analyzer completely - why are we adding a stub analyzer that adds performance overhead with no user value add.

**Comment by Evangelink** [comment] 2020-09-18 07:31
@mavasani Same comment here, any reason to keep the ticket open?

**Comment by Evangelink** [comment] 2020-12-09 23:23
@sharwell Could you confirm this can be closed?

**Comment by sharwell** [comment] 2020-12-10 00:19
This seems like a low priority but reasonable change to make. It's certainly a false positive, but unlikely to apply to most code. I'd leave it open in case someone decides to eventually fix it.

**Comment by Evangelink** [comment] 2020-12-10 09:20
It seems like a few minutes tweak to the rule so I will do a PR today.

**Comment by mavasani** [comment] 2020-12-10 17:06
As mentioned in https://github.com/dotnet/roslyn-analyzers/issues/4101#issuecomment-692820153 this is actually by design and helps avoid stub analyzers which return non-zero descriptors but have an empty Initialize method. This incurs an unnecessary performance cost of instantiating a no-op analyzer. Please fix the analyzer package or add a source suppression.

**Closed** 2020-12-10 17:06 UTC
Labels: False_Positive, Resolution-By Design, help wanted
