### ISSUE TITLE
.NET Core project ignores custom ruleset

### ISSUE THREAD

**Issue by istvan-dolgozik** [dotnet/roslyn-analyzers#2859] opened 2019-09-19 12:02 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.4 (Latest)

#### Repro steps

 - Add nuget package to a .NET Core project (see attached image)
 - Create a custom ruleset file
 - Add this custom ruleset file to the project (see attached image)
 - Right click on Solution --> Analyze: Run Code Analysis on Solution
 - Check warnings tab: a lot of other types of warnings appear not just the ones specified in the custom ruleset file.

This option is also checked (Visual Studio 2017):
Tools/Options/Text Editor/C#/Advanced: Enable full solution analysis

#### Expected behavior
.NET Core project doesn't ignore .rulest file and only the warning types that I set in the ruleset file are present in the Error List tab.

#### Actual behavior
.NET Core project ignores .ruleset file.

![image](https://user-images.githubusercontent.com/55540636/65242077-7530a900-dae5-11e9-900c-ad42420a5d59.png)

**Comment by mavasani** [comment] 2019-09-19 12:08
This is by design - majority of rules in the FxCopAnalyzers package are enabled by default. This is different from legacy binary-based static analysis where all the rules were disabled by default. This is to improve discoverability of rules in the NuGet package. We have a feature request https://github.com/dotnet/roslyn/issues/38674 which would allow you to change these semantics back to the old analysis model by specifying a bulk configuration entry that turns off all the rules by default, and you can selectively turn them on with individual diagnostic ID entries.

**Comment by istvan-dolgozik** [comment] 2019-09-19 12:16
Thank you. Is there a list somewhere of these enabled-by-default rules?

**Comment by mavasani** [comment] 2019-09-19 12:22
Repo has a checked in file that has the current set of implemented rules in the branch: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md

Additionally, each NuGet package embeds this documentation file which contains the same information pertaining to rules shipped in that package. For example, `C:\Users\<%user%>\.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.5-beta1.final\documentation\Microsoft.CodeAnalysis.FxCopAnalyzers.md`

Finally, I remembered that each NuGet package also packages a bunch of helper rulesets at `C:\Users\<%user%>\.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.5-beta1.final\rulesets` and one of them is `AllRulesDisabled.ruleset` which disables all rules by default. So you should be able to copy it over, and then add a ruleset include for that in your main ruleset and you should get back the old behavior.

**Comment by mavasani** [comment] 2019-09-19 12:24
Closing this issue as by design. Hopefully the configuration to make all rules disabled by default would be much easier once https://github.com/dotnet/roslyn/issues/38674 is implemented.

**Closed by mavasani** 2019-09-19 12:24 UTC

**Comment by istvan-dolgozik** [comment] 2019-09-19 12:25
Thank you for mentioning AllRulesDisabled.ruleset, I'll give it a try.

**Comment by MelbourneDeveloper** [comment] 2020-03-19 06:20
@mavasani so what's the deal here? Can we use rulesets? My project compiles fine in Visual Studio but with `dotnet` I just get errors. I can't build my app in the pipeline. What am I supposed to do?
