### ISSUE TITLE
Warning for [DataTestMethod]

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1703] opened 2018-05-25 07:00 UTC
Affected Branch: [27705.2000.d15.8]
Affected Build: 15.8.0 Preview 1.1
Affected Product Language: C#

Steps to reproduce:

1. Create new  MSTest Test Project (.NET Core) 
2. Add following data test method to test class: 
[DataTestMethod] 

[DataRow(0)] 

public void TestMethod(int n) { } 

3. Add Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.0 to project

Expected: there are no warnings for TestMethod
Actual: warning for TestMethod "Member TestMethod does not access instance data and can be marked as static (Shared in VisualBasic)

Note: there are no warnings for the same method with [TestMethod] attribute.

Repro Gif

Copied from [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/614242)

**Comment by sharwell** [comment] 2018-05-25 16:28
Duplicate of #1678

**Closed by sharwell** 2018-05-25 16:28 UTC
Labels: Bug
