### ISSUE TITLE
AvoidZeroLengthArrayAllocationsFixer throws an exception

### ISSUE THREAD

**Issue by dfederm** [dotnet/roslyn-analyzers#1330] opened 2017-10-26 04:16 UTC
#### Analyzer package
Microsoft.NetCore.Analyzers

#### Analyzer
AvoidZeroLengthArrayAllocations

#### Repro steps
I had the following code snippet:
```
var model = new RecomputeRequest
{
    UploadIds = new int[0],
    Priority = UploadProcessingMessagePriority.High,
};
```

A red squiggle appears under the `new int[0]`, so try quick fixing it.

#### Expected behavior
The code is fixed.

#### Actual behavior
![image](https://user-images.githubusercontent.com/6445614/32034737-3e9608a2-b9c9-11e7-8985-525e379f975f.png)

Stack trace:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.ConvertToArrayEmpty(<Unknown Parameters>)
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.<>c__DisplayClass3_0.<RegisterCodeFixesAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by dfederm** [comment] 2017-10-26 04:20
It looks like it works if I extract it to a local.

```
var uploadIds = new int[0];
var model = new RecomputeRequest
{
    UploadIds = uploadIds,
    Priority = UploadProcessingMessagePriority.High,
};
```

So there seems to be something wrong specificalyl when using an object initializer.

**Comment by mavasani** [comment] 2017-11-10 17:07
Dupe of https://github.com/dotnet/roslyn-analyzers/issues/1298

**Closed by mavasani** 2017-11-10 17:07 UTC
Labels: Bug
