### ISSUE TITLE
BannedApiAnalyzer should not flag references in XML API docs

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn-analyzers#6825] opened 2023-08-01 01:00 UTC
Reported by @jaredpar internally.

> An unexpected side effect of adding an API to the banned list is that I could no longer reference the API in doc comments. That was a bit unexpected. I wanted to be able to say in the doc comments items like 
>
>> This API is a replacement for the banned API <see cref="Path.GetTempPath()" />
>
> But the banned API analyzer flagged that as a violation cause I was using the API. Is that behavior intended? 
>
> Generally I think of the analyzer as a way to prevent us from using an API and a ref in a doc comment doesn't seem like a use, more a note. It's not a deal breaker but is a bit annoying.

**Comment by mavasani** [comment] 2023-08-01 04:30
Duplicate of #6069

**Closed by mavasani** 2023-08-01 04:30 UTC
Labels: Area-DotNetAnalyzers.BannedApiAnalyzer
