### ISSUE TITLE
Rule precedence isn't clear with style rules.

### ISSUE THREAD

**Issue by AlfredoMS** [dotnet/roslyn-analyzers#4305] opened 2020-10-10 19:05 UTC
### Analyzer

any rule starting with IDE, but will use IDE0008 as a concrete example.

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

VS2019 Version 16.7.5

### Describe the bug

Precedence rules are not well documented, and actual results are unexpected.
According to documents:

```
 If you have multiple entries that are applicable to a specific rule ID, the following is the precedence order to choose the applicable entry:

    Severity entry for an individual rule by ID takes precedence over severity entry for a category.
    Severity entry for a category takes precedence over severity entry for all analyzer rules.
```
But for style rules, they can be defined as (usingIDE0008 as example):

```
# var preferences
csharp_style_var_elsewhere = false:silent
csharp_style_var_for_built_in_types = false:error
csharp_style_var_when_type_is_apparent = true:silent
```

I would expect this to be more specific rules, thus take precedence over more general rules, like the category base or the default for all analyzers `dotnet_analyzer_diagnostic.severity`

### Steps To Reproduce

In my editor config file I have (extracting only relevant portions)

```
[*.cs]
# Default settings
dotnet_analyzer_diagnostic.severity = error

# var preferences
csharp_style_var_elsewhere = false:silent
csharp_style_var_for_built_in_types = false:error
csharp_style_var_when_type_is_apparent = true:silent
```

When building I get this flagged as an error:
` var appointmentResult = await collections.Appointments.ReplaceDocument(appointment);`
Eventhough I expect this rule to be silent.

### Expected behavior

style rules should take precedence over specific rules even when using `dotnet_analyzer_diagnostic.severity = error` at the top of the document.
Compilations shouldn't flag any errors when using `var` except for built-in types

### Actual behavior

All style errors get marked as errors.

**Comment by mavasani** [comment] 2020-10-10 19:17
Duplicate of https://github.com/dotnet/roslyn/issues/44201. Specifying severity as part of code style options will soon be deprecated.

**Closed** 2020-10-10 19:19 UTC
