### ISSUE TITLE
CA1062 should not warn here

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#2632] opened 2019-06-25 23:31 UTC
```cs
    public partial class App
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            if (e?.Args.Length == 1)
            {
                var window = e.Args[0];
                this.StartupUri = new Uri($"Windows/{window}.xaml", UriKind.Relative);
            }

            base.OnStartup(e);
        }
    }
```

**Comment by mavasani** [comment] 2019-06-26 13:07
Verified this repros in 2.9.3, but not on https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.4-beta1.final

**Comment by mavasani** [comment] 2019-06-26 13:07
Duplicate of #2526

**Closed by mavasani** 2019-06-26 13:07 UTC
