### ISSUE TITLE
StackOverflowException on CA1812

### ISSUE THREAD

**Issue by bichuga** [dotnet/roslyn-analyzers#1747] opened 2018-07-26 22:59 UTC
#### Analyzer package
Microsoft.CodeQuality.Analyzers

#### Package Version
v2.6.2-beta1

#### Diagnostic ID
CA1812

#### Repro steps
1. Check out branch [users/lukesch/CA1812Overflow](https://o365exchange.visualstudio.com/O365%20Core/_git/bothell?path=%2Fsources%2Fdev%2FWorkflows%2Fsrc%2FWorkflowEngine%2FInfrastructure%2FServer%2FSql%2FSqlManagedObjects&version=GBusers%2Flukesch%2FCA1812Overflow)
2. Ensure CA1812 is enabled
3. Build [SqlManagedObjects](https://o365exchange.visualstudio.com/O365%20Core/_git/bothell?path=%2Fsources%2Fdev%2FWorkflows%2Fsrc%2FWorkflowEngine%2FInfrastructure%2FServer%2FSql%2FSqlManagedObjects&version=GBusers%2Flukesch%2FCA1812Overflow)

#### Expected behavior
Analysis completes. If you disable CA1812 the build and analysis will complete successfully.

#### Actual behavior
StackOverflowException 

Compiling C# files - e:\git\bothell\sources\dev\workflows\src\workflowengine\infrastructure\server\sql\sqlmanagedobjects\objd\amd64\internal.focus.workflowengine.server.sql.sqlmanagedobjects.dll
errors in directory e:\git\bothell\sources\dev\workflows\src\workflowengine\infrastructure\server\sql\sqlmanagedobjects e:\cxcache\.a\msbuild.corext.bq5vttwgtffr0bb9dhb6pa\v15.0\bin\roslyn\microsoft.csharp.core.targets(84,5) : error MSB6006: "csc.exe" exited with code -1073741571.
errors in directory e:\git\bothell\sources\dev\workflows\src\workflowengine\infrastructure\server\sql\sqlmanagedobjects errors found in parent: terminating pass 2

**Comment by mavasani** [comment] 2018-08-06 19:25
@bichuga Can you please provide a standalone repro project that does not require enlisting into office (and permissions required for it)? It would also help if you can provide the callstack or a dump file for the crash.

**Comment by mavasani** [comment] 2018-08-06 21:58
Verified this is dupe of https://github.com/dotnet/roslyn-analyzers/issues/1739, which has a smaller repro. Will send out a fix soon. Closing this one as a duplicate.

**Closed by mavasani** 2018-08-06 21:58 UTC
Labels: Area-Microsoft.CodeQuality.Analyzers, Bug
