### ISSUE TITLE
Can't Compile Because of CLSCompliant

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/roslyn-analyzers#4873] opened 2021-02-20 05:27 UTC
![image](https://user-images.githubusercontent.com/16697547/108584805-408ae600-7398-11eb-85c5-036c72ec64db.png)

### Analyzer

CA1014

### Analyzer source

Microsoft.CodeAnalysis.NetAnalyzers 

**Version**: 5.0.

### Describe the bug

I can't compile.

### Steps To Reproduce

Clone this repo:
https://github.com/MelbourneDeveloper/Trezor.Net

Switch branch to : UpgradeDevice.Net

Reset to commit: 2eb2d416ea65f970b9fef3738fb570e321421898

### Expected behavior

It compiles

### Actual behavior

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CA1014	Mark assemblies with CLSCompliant	Trezor.Net	C:\Code\Trezor.Net\src\Trezor.Net\CSC	1

**Comment by Youssef1313** [comment] 2021-02-20 07:37
In `CodeRules.ruleset`, you set `<Rule Id="CA1014" Action="Warning" />`, and you're treating warnings as errors. I suggest you completely delete the ruleset, and rely on either editorconfig or globalconfig

**Comment by Evangelink** [comment] 2021-02-21 09:14
As stated by @Youssef1313 the behavior is `undefined` when both `ruleset` and `.editorconfig` files are set.

@MelbourneDeveloper Could you please move to use only one and confirm the issue is fixed?

**Comment by MelbourneDeveloper** [comment] 2021-02-21 09:27
I've deleted the ruleset file. I didn't realise it was there. It does compile, but then again, this turns out to have been an intermittent problem so it's not a confirmation that the issue was fixed.

I suggest that the code analysers should fail if both ruleset and editor config files are supplied.

**Comment by Evangelink** [comment] 2021-02-22 20:17
> I've deleted the ruleset file. I didn't realise it was there. It does compile, but then again, this turns out to have been an intermittent problem so it's not a confirmation that the issue was fixed.

I will close this issue but feel free to reopen this or create a new issue if the problem isn't actually fixed.

> I suggest that the code analysers should fail if both ruleset and editor config files are supplied.

Yeah, it would totally make sense. Just wondering if we can detect that the `.editorconfig` contains rule related entries to avoid reporting only when detecting the file. @mavasani Are you ok with having such analyzer? Shall it be on roslyn's side?

**Closed by Evangelink** 2021-02-22 20:17 UTC
Labels: Bug
