### ISSUE TITLE
CA1416 After Upgrade from dotnet 4.84 to Dor Net 7

### ISSUE THREAD

**Issue by nbkgit** [dotnet/roslyn-analyzers#6543] opened 2023-03-23 09:52 UTC
I have a warning free  Visual Studio 2017 project With Vb Net and dot Net 4.84, which was upgraded to Visual Studio 2022 Dot Net 7

But i get for every Combit List and Label Object that i use a CA1416 Warning

![Screenshot 2023-03-23 102815](https://user-images.githubusercontent.com/65838508/227160966-729bd3ad-c841-4ec4-a4d1-972d87b18250.png)

All project options are fixed on windows and so i posted an error for visual studio, but they refereed me  to here https://developercommunity.visualstudio.com/t/CA1416-This-call-site-is-accessible-on-a/10297603#T-ND10313651

If i make a new Project with the same Nuget package, no warnings appears.

here is a screenshot of the project options, they all show that the app is only for windows

![Screenshot 2023-03-23 103629](https://user-images.githubusercontent.com/65838508/227162623-2764f24b-ddc3-4f2f-b327-da1d90b5c8e3.png)

I also add my vbproj file, if there is something a miss, i can't see any problem

[Nycomed.zip](https://github.com/dotnet/roslyn-analyzers/files/11049302/Nycomed.zip)

Besides ignoring the warning, is there a possibility to  get rid of all the warning

the microsoft page https://learn.microsoft.com/de-de/dotnet/fundamentals/code-analysis/quality-rules/ca1416

only writes a solution for C#, which doesn't work in vb Net

**Comment by buyaa-n** [comment] 2023-03-23 23:33
By design the analyzer only check if `SupportedOSPlatform( "platform")` `SupportedOSPlatform( "platform")` attributes applied to the API/type/assembly. When a project targeting windows (`<TargetFramework>net7.0-windows</TargetFramework>`) MSBuild would add assembly level attribute `<Assembly: System.Runtime.Versioning.SupportedOSPlatform("windows")>` to the generated `AssemblyInfo.vb` file which then consumed by the analyzer. I see your project is disabled generating AssemblyInfo.vb: `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`. [MSBuild team suggest to not disable it](https://github.com/dotnet/sdk/issues/14502#issuecomment-828805675), anyway as you have disabled it the attribute could not be added automatically and so you need to add it manually anywhere in you project source, [read more](https://learn.microsoft.com/de-de/dotnet/fundamentals/code-analysis/quality-rules/ca1416#tfm-target-platforms)

> only writes a solution for C#, which doesn't work in vb Net

Sorry that code samples are in C#, but the ways to handling/suppressing the warnings are same for VB.

**Comment by buyaa-n** [comment] 2023-03-23 23:35
Closing it as by design, feel free to comment if you have more questions

**Closed by buyaa-n** 2023-03-23 23:35 UTC
Labels: Questions

**Comment by nbkgit** [comment] 2023-03-24 16:31
no they aren't the same, adding `[SupportedOSPlatform("windows")]` will lead to an error, so the problem can't be resolved that way. Like i try to explain, i didn't do anything the program come after the upgrade out that way and i try to get rid of the warnings, but can't uznderstand where the problem lies, because nobody explains it properly. i will add GenerateAssemblyInfo and see what happens

**Comment by buyaa-n** [comment] 2023-03-24 16:38
Yes, the attribute syntax is different, of course it should be in VB syntax. I meant the way of handling it the same, adding an attribute. Please add `<Assembly: System.Runtime.Versioning.SupportedOSPlatform("windows")>` attribute for VB.

**Comment by nbkgit** [comment] 2023-03-24 17:18
the correct solution is, that Dot **Net 7 doesn't support windows 7**, which is seen in the picture, that should be on the website and also the code that you supplied,  as long as Vb Net is supported .I did search how to add it in Vb Nezt, but i coudn't find any mention of it, that is why a good documentation must provide it. But thanks for all your support

**Comment by bcheung4589** [comment] 2024-05-06 10:55
"good documentation" - thats going to be a big problem..

I still have this same stupid warning, and the overall design is so fkn stupid, I have to add the supression ON EVERY FUCKING LEVEL THE CODE IS USED BECAUSE I CANT SET THE FUCKING SEVERITY LEVEL IN VS2022. And yet, MS team doesnt give a fck.

Maybe its a idea to make VS2022 working properly? 

When you show the option, "Configure CA1416 severity", with options  None, Silent... What does this spec mean to MS? Why show it when it does NOTHING!!! Show menu items THAT WORK.

**Comment by nbkgit** [comment] 2024-05-06 13:06
The cause was in my case that i didn't specify the correct trget system and Dot Net 7 wasn't supported in Windows 7. If that is niot the case with you, you can flow control the by https://github.com/dotnet/roslyn-analyzers/issues/6543#issuecomment-1483096716 and so have in one vb net code multiple platform support.
