### ISSUE TITLE
False positive from RS1024 (Compare symbols correctly) when initializing a HashSet<ITypeSymbol>

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-analyzers#5246] opened 2021-07-15 21:54 UTC
### Analyzer

**Diagnostic ID**: RS1024: `Compare symbols correctly`

### Analyzer source

Package: Microsoft.CodeAnalysis.CSharp.Workspaces
**Version**: 3.10.0

### Describe the bug

This line produces the RS1024 diagnostic, even though we *do* specify to use the `SymbolEqualityComparer`:

```cs
private readonly HashSet<ITypeSymbol> alreadyCollected = new(SymbolEqualityComparer.Default);
```

**Comment by Youssef1313** [comment] 2021-07-16 19:52
This was fixed in https://github.com/dotnet/roslyn-analyzers/pull/4571. I'm not sure which version (if any) has the fix.

**Comment by Evangelink** [comment] 2021-08-06 20:51
@AArnott could you confirm the issue is fixed?

**Comment by AArnott** [comment] 2021-08-07 20:12
It still repros with 4.0.0-2.final (the latest on nuget.org.

**Comment by Evangelink** [comment] 2021-08-07 20:14
I have managed to see the same issue on roslyn-analyzer itself that's why I was asking this question.

**Comment by ryzngard** [comment] 2021-09-13 21:21
@mavasani is it just that we haven't released this fix yet?

**Comment by zivarah** [comment] 2021-11-30 15:37
I would appreciate confirmation on whether this has been fixed/released yet and, if so, what version contains the fix.

**Comment by 333fred** [comment] 2021-12-07 07:36
@mavasani I'm still seeing this. Have we released a version this this fix?

**Comment by Youssef1313** [comment] 2021-12-07 10:11
@333fred Are you using Microsoft.CodeAnalysis.Analyzers 3.3.3?

**Comment by Youssef1313** [comment] 2021-12-07 10:18
> It still repros with 4.0.0-2.final (the latest on nuget.org.)

@AArnott The analyzer comes from `Microsoft.CodeAnalysis.Analyzers` and the latest version is 3.3.3.

The Workspaces package you're referring to has the Analyzers package as a dependency, and it unfortunately doesn't reference the latest. So you have to explicitly install `Microsoft.CodeAnalysis.Analyzers` 3.3.3.

I opened https://github.com/dotnet/roslyn/pull/58154 on roslyn side to reference the latest package.

**Comment by 333fred** [comment] 2021-12-07 16:10
> @333fred Are you using Microsoft.CodeAnalysis.Analyzers 3.3.3?

I was not explicitly referencing the package, so I was using whatever version the O# roslyn dependency version pulls in (I think 3.3.2?).

**Comment by Youssef1313** [comment] 2021-12-07 16:21
@333fred If it was pulled from one of the other `Microsoft.CodeAnalysis.*` packages, then yes it would be 3.3.2. dotnet/roslyn#58154 should fix that.

**Comment by Youssef1313** [comment] 2021-12-07 16:23
@333fred I've also updating PostReleaseActivity.md in https://github.com/dotnet/roslyn-analyzers/pull/5757 to note that new versions should be used by dotnet/roslyn to avoid this kind of issues. I assume @JoeRobich and @mavasani follow these instructions when releasing a new version?

**Comment by Youssef1313** [comment] 2021-12-09 17:17
I believe this can be closed.

**Closed** 2021-12-10 02:05 UTC
Labels: Bug, Area-Roslyn.Diagnostics.Analyzers
