### ISSUE TITLE
CA1021 Try* exception not applied to explicit interface implementation

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn-analyzers#5853] opened 2022-02-07 09:56 UTC
### Analyzer

**Diagnostic ID**: [CA1021](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1021): `Avoid out parameters`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers 6.0.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/6.0.0)

### Describe the bug

Rule supports [exception for Try pattern methods](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1021#try-pattern-methods), but it is not applied to methods, which a part of explicit interface implementation.

### Steps To Reproduce

```cs
public interface ITry
{
    bool TrySomething(out string? something);
}
public class Try : ITry
{
    bool ITry.TrySomething(out string? something)
    {
        something = null;
        return false;
    }

    public bool TryAnything(out string? something)
    {
        something = null;
        return false;
    }
}
```
### Expected behavior

No `CA1021` reports for both methods

### Actual behavior

`CA1021` reported for `bool ITry.TrySomething(out string? something)`

**Comment by Youssef1313** [comment] 2022-02-13 21:53
I'm not able to reproduce this in main branch (NOT including the **currently not-yet-merged** PR: https://github.com/dotnet/roslyn-analyzers/pull/5876).

**Comment by MaceWindu** [comment] 2022-02-14 09:08
[ConsoleApp9.zip](https://github.com/dotnet/roslyn-analyzers/files/8059356/ConsoleApp9.zip)
also contains repro for #5854

**Closed** 2022-02-14 11:26 UTC
Labels: Area-Microsoft.CodeQuality.Analyzers, False_Positive, help wanted, Priority:3
