### ISSUE TITLE
Can't run roslyn-analyzers in VS or via xUnit

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn-analyzers#274] opened 2015-08-18 01:55 UTC
I've been working on #215 but I'm having some trouble testing.

I can build fine, but when I run and deploy to Visual Studio I get `FileNotFoundExceptions` in  `ActivityLog.xml`.

Here's the stack trace it includes:

```
System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.&
File name: &apos;Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;
 at Microsoft.CodeAnalysis.Editor.Implementation.Interactive.InertClassifierProvider.InertClassifier.GetClassificationSpans(SnapshotSpan span)
 at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext()
 at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()
 
 === Pre-bind state information ===&
LOG: DisplayName = Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35&#x000A; (Fully-specified)&
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/&
LOG: Initial PrivatePath = NULL&
Calling assembly : Roslyn.InteractiveEditorFeatures, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35.&
===&
LOG: This bind starts in LoadFrom load context.&
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().&
LOG: Using application configuration file: C:\Users\Student\AppData\Local\Microsoft\VisualStudio\14.0RoslynDev\devenv.exe.config&
LOG: Using host configuration file: &
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.&
LOG: Post-policy reference: Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35&
LOG: The same bind was seen before, and was failed with hr = 0x80070002.&
```

I think it's related to strong naming, but I'm not sure how to move forward.

I figured I'd just write tests first, but after installing `xunit.runner.visualstudio` and running the tests, I get another strong name exception:

```
Test Name:	Microsoft.CodeAnalysis.UnitTests.MetaAnalyzers.IgnoredReturnValueAnalyzerRuleTests.CSharp_VerifyDiagnostic
Test FullName:	Microsoft.CodeAnalysis.UnitTests.MetaAnalyzers.IgnoredReturnValueAnalyzerRuleTests.CSharp_VerifyDiagnostic
Test Source:	C:\Users\Student\Documents\GitHub\roslyn-analyzers\src\CodeAnalysis\Test\MetaAnalyzers\IgnoredReturnValueAnalyzerRuleTests.cs : line 18
Test Outcome:	Failed
Test Duration:	0:00:12.179

Result StackTrace:	
at Microsoft.CodeAnalysis.UnitTests.MetaAnalyzers.IgnoredReturnValueAnalyzerRuleTests.GetExpectedDiagnostic(String language, Int32 line, Int32 column, String analyzerTypeName, String missingLanguageName)
   at Microsoft.CodeAnalysis.UnitTests.MetaAnalyzers.IgnoredReturnValueAnalyzerRuleTests.GetCSharpExpectedDiagnostic(Int32 line, Int32 column, String analyzerTypeName, String missingLanguageName) in C:\Users\Student\Documents\GitHub\roslyn-analyzers\src\CodeAnalysis\Test\MetaAnalyzers\IgnoredReturnValueAnalyzerRuleTests.cs:line 46
   at Microsoft.CodeAnalysis.UnitTests.MetaAnalyzers.IgnoredReturnValueAnalyzerRuleTests.CSharp_VerifyDiagnostic() in C:\Users\Student\Documents\GitHub\roslyn-analyzers\src\CodeAnalysis\Test\MetaAnalyzers\IgnoredReturnValueAnalyzerRuleTests.cs:line 40
Result Message:	System.IO.FileLoadException : Could not load file or assembly 'Microsoft.CodeAnalysis.Analyzers, Version=1.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

```

![image](https://cloud.githubusercontent.com/assets/1249087/9320667/96c4abc0-452a-11e5-846c-ebbc6f572afb.png)

What's the best way for me to move forward?

**Comment by genlu** [comment] 2015-08-18 02:35
Not sure about the first problem, could you please provide more detail on how did you deploy the analyzer in VS?

The `System.IO.FileLoadException` when you ran tests in VS is likely due to `xunit.runner.visualstudio` can't handle fake signing. We are are trying to figure out a solution right now, meantime, you can do either of the following to run tests:
1. In cmd promt, MSBuild buildandtest.proj
2. In VS, Select a test project, set it as the startup project, and run with F5 or Ctrl+F5

**Comment by JoshVarty** [comment] 2015-08-18 03:24
The steps that got me to the first issue:

1. Fork master.
2. Run `cibuild.cmd` 
3. Open `src/Analyzers.sln`
4. Press F5 to deploy to VS.

A new Visual Studio opened, I got the `ActivityLog.xml` error and the stack trace above.

**Comment by genlu** [comment] 2015-08-18 04:17
I tried to follow your steps, but couldn't reproduce the exception. By the way, `Version=42.42.42.42` suggests that you might be adding an analyzer compiled against non-official build of assembly `Microsoft.CodeAnalysis.Workspaces` (from dotnet/Roslyn repo), which should not happen in Roslyn-analyzer, since all the projects reference Roslyn assemblies through nuget.org. Maybe @tmeschter knows what caused this.

**Comment by tmeschter** [comment] 2015-08-18 15:55
@JoshVarty The first issue indicates that your RoslynDev hive is corrupted in some way, most likely as a result of building/deploying extensions from dotnet/roslyn. I recommend shutting down VS, deleting `%localappdata%\Microsoft\VisualStudio\14.0RoslynDev`, and then rebuilding and deploying the analyzers. We should also consider deploying the analyzer VSIXs in dotnet/roslyn-analyzers to a different hive than RoslynDev, which should help avoid this issues in the future.

The second issue is almost certainly due to a bad interaction between fake signing and the shadow-copying done by the xunit.runner.visualstudio. It's possible that this is fixed in a newer version of xUnit; that is being looked into. In the meantime, the steps laid out by @genlu are the supported means for running and debugging unit tests.

**Comment by srivatsn** [comment] 2015-09-01 18:06
@tmeschter do we need to update to that version of xunit that has the fix for the issue that you mention?

**Closed** 2016-04-15 03:33 UTC
Labels: Area-Infrastructure, Bug, Up for Grabs
