### ISSUE TITLE
[Suggestion] Warn if the operands of a bitwise operation are both the type of an enum without [Flags]

### ISSUE THREAD

**Issue by jtschuster** [dotnet/roslyn-analyzers#6673] opened 2023-06-06 22:58 UTC
### Describe the problem you are trying to solve

I recently spent a long time working on an issue with a source generator, using test code that assumed an enum was a [Flags] enum. This led to issues further down the generator pipeline. Once I realized it didn't make sense to do bitwise 'or' on the enum values and used just one value the problem resolved itself. I think in a situation where there are bitwise operators on non-flag enums, it's more likely an error than intentional and a warning would be warranted. There definitely are situations where the order of the enum matters and it makes sense to do standard arithmetic, but bitwise operations seem to be only for flags.

### Describe suggestions on how to achieve the rule

An analyzer would warn on bitwise operations if the type of the operand expressions are both the same enum and that enum does not have the FlagsAttribute. I don't think a code-fix would make sense, since it's not always clear if the enum should be flags or if the usage was just based on a misunderstanding of the API.

### Additional context

None.

**Comment by Youssef1313** [comment] 2023-06-07 09:13
Duplicate of https://github.com/dotnet/runtime/issues/75412

**Closed by Youssef1313** 2023-06-07 09:13 UTC
