### ISSUE TITLE
Version 3.3.1 and non-sdk style projects messed up in Visual Studio error list

### ISSUE THREAD

**Issue by Ergamon** [dotnet/roslyn-analyzers#4416] opened 2020-11-06 20:42 UTC
**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.1 (Latest)

### Describe the bug

The latest NuGet package messes up with the inbuild error list of Visual Studio. 

The build process is not affected.

1. Open VS2019 - Create a new Console App (.NET Framework)

The default template will create a new project in the old csproj format.

2. Modify the Program.cs to have a warning, e.g. I used:

```
public static class Program
{
  public static void Main()
  {
    var test = new Test();
    test.Foo();
  }
}
 
public class Test
{
  [Obsolete("Do not use!")]
  public void Foo()
  {
  }
}
```
This will create a CS0618 warning in the error list. 

3. Add the FxCopAnalyzers NuGet package to the project
This will change the CS0618 warning to an error

Note: This behavior is only visible if you have the file open. As written build is not affected.

Currently I found 2 ways to get rid of this bug:
1. Convert the project to the SDK style csproj format
2. Downgrade to the previous release 3.3.0 which does not include this bug

**Comment by mavasani** [comment] 2020-11-06 20:44
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/4398#issuecomment-720662606

**Closed by mavasani** 2020-11-06 20:44 UTC
