### ISSUE TITLE
Partial methods generated (CommunityToolkit.Mvvm.ComponentModel)

### ISSUE THREAD

**Issue by robertodalmonte** [dotnet/roslyn-analyzers#5996] opened 2022-05-05 06:22 UTC
Using the CommunityToolkit.Mvvm.ComponentModel Version="8.0.0-preview3" 
you can declare a partial method when a property changes:

[ObservableProperty]
private string _name;

then you can write a method like this:
partial void OnNameChanged(string value)
{
}
and you must declare with the same parameter, use it or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029ba69a-6673-836c-c69e-0105061904ea
* Version Independent ID: fc793abc-cd23-d6c5-2915-89ef59ca6d41
* Content: [IDE0060: Remove unused parameter - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0060)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0060.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0060.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment] 2022-08-28 13:40
The original issue is about IDE0060 (in dotnet/roslyn) and is duplicate of https://github.com/dotnet/roslyn/issues/57814

**However,** there is a similar analyzer in roslyn-analyzers (CA1801). Instead of closing this issue as duplicate, it makes sense to see whether this scenario works for CA1801 or not.

**Comment by Youssef1313** [comment] 2022-08-30 06:29
CA1801 is deprecated. This issue can be closed as a duplicate of https://github.com/dotnet/roslyn/issues/57814

**Closed** 2022-08-30 06:48 UTC
Labels: Area-IDE, untriaged, :watch: Not Triaged, Pri2, dotnet-fundamentals/prod
