### ISSUE TITLE
Prevent Nuget library consumers from getting references to analyzers

### ISSUE THREAD

**Issue by scottrudy** [dotnet/roslyn-analyzers#1785] opened 2018-08-13 23:43 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.1

#### Severity 

4 - Minor loss of functionality with available work around

#### Problem

Downstream consumers of Nuget packages that use Microsoft.CodeAnalysis.FxCopAnalyzers will require the dependency assets by default. Able to work around the problem by explicitly [controlling dependency assets](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets). This requires setting `PrivateAssets` to a value of `all` in the project file, as the default of `contentfiles;analyzers;build` does not work.

```xml
<PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.1">
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

#### Repro steps

1. Create Nuget package as a .Net standard 2.0 library with a reference to Microsoft.CodeAnalysis.FxCopAnalyzers
1. Create a .Net project referencing the created Nuget package from the previous step
1. See the dependent libraries get loaded

#### Expected behavior

Downstream clients do not install Analyzer dependencies, because the project considers them private.

#### Actual behavior

Downstream clients install Analyzer dependencies

**Comment by sharwell** [comment] 2018-08-25 14:46
Duplicate of NuGet/Home#6279

**Closed by sharwell** 2018-08-25 14:46 UTC
