### ISSUE TITLE
NullReferenceException CSharpDiagnosticAnalyzerApiUsageAnalyzer

### ISSUE THREAD

**Issue by alexk8** [dotnet/roslyn-analyzers#2680] opened 2019-07-17 04:58 UTC
#### Analyzer package

Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer

#### Package Version

file Microsoft.CodeAnalysis.CSharp.dll version 3.100.119.28106

#### Diagnostic ID

VS Warning	AD0001

#### Repro steps

I've got no idea, I've only updated Visual Studio 2019 to latest 16.1.6

#### Expected behavior

no warnings in VS

#### Actual behavior

Warning	AD0001	**Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'**.	
```
	Microsoft.CodeAnalysis.CSharp.Analyzers	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: [myprojectname]
ISymbol: ApplicationDbContext (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.AddUsedNamedTypeCore(ITypeSymbol typeOpt, Builder builder, Boolean& hasAccessToTypeFromWorkspaceAssemblies)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.AddUsedNamedTypeCore(ITypeSymbol typeOpt, Builder builder, Boolean& hasAccessToTypeFromWorkspaceAssemblies)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.GetUsedNamedTypes(INamedTypeSymbol namedType, Compilation compilation, CancellationToken cancellationToken, Boolean& hasAccessToTypeFromWorkspaceAssemblies)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.<>c__DisplayClass11_0.<Initialize>b__1(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__40_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by mavasani** [comment] 2019-07-17 15:47
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/1888#issuecomment-454969167

**Comment by mavasani** [comment] 2019-07-17 15:48
To clarify, can you please add an explicit NuGet package reference to v2.6.3 of Microsoft.CodeAnalysis.Analyzers in your project?

**Closed by mavasani** 2019-07-17 15:47 UTC

**Comment by alexk8** [comment] 2019-07-18 01:22
It's been around for all day during coding and then I noticed that it's gone without extra actions.
It would take some time to try to investigate that, unfortunately I do not have such an opportunity at the moment.
I'll try to do that if it comes up or when I have some time
