### ISSUE TITLE
[17.8.0 Preview 2.0] Error AD0001 Analyzer 'Microsoft.CodeQuality.CSharp.Analyzers.Maintainability.CSharpAvoidDeadConditionalCode' threw an exception

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/roslyn-analyzers#6945] opened 2023-09-15 10:19 UTC
### Analyzer

Microsoft.CodeQuality.CSharp.Analyzers.Maintainability.CSharpAvoidDeadConditionalCode

### Analyzer source

Microsoft.CodeAnalysis.NetAnalyzers 8.0.0-preview.23420.2

### Describe the bug

After upgrading to 17.8.0 Preview 2.0 my solution fails to build with multiple AD0001 errors:

`Error AD0001 Analyzer 'Microsoft.CodeQuality.CSharp.Analyzers.Maintainability.CSharpAvoidDeadConditionalCode' threw an exception of type 'System.InvalidOperationException' with message 'Collection was modified; enumeration operation may not execute.'.`

I can confirm that the error does not occur (in Preview 2) when specifying Microsoft.CodeAnalysis.NetAnalyzers 8.0.0-preview.23364.2

### Steps To Reproduce

- Upgrade to Visual Studio 17.8.0 Preview 2 or specify Microsoft.CodeAnalysis.NetAnalyzers 8.0.0-preview.23420.2
- Attempt to build solution

### Expected behavior

- Solution builds

### Actual behavior

- Build fails with multiple AD0001 errors reported for Microsoft.CodeQuality.CSharp.Analyzers.Maintainability.CSharpAvoidDeadConditionalCode

**Comment by mavasani** [comment] 2023-09-15 10:45
Duplicate of #6929

**Closed by mavasani** 2023-09-15 10:45 UTC
