### ISSUE TITLE
Microsoft Code Analysis 2019 VSIX extension not signed correctly (Invalid Timestamp)

### ISSUE THREAD

**Issue by JamesEvolution** [dotnet/roslyn-analyzers#3248] opened 2020-01-28 11:02 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Repro steps

1. Download Microsoft Code Analysis 2019 VSIX from https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MicrosoftCodeAnalysis2019 (as recommended by VS)
2. Attempt to install VSIX extension
3. Digital Signature: Invalid Timestamp

#### Expected behavior
Correctly signed digital signature

#### Actual behavior
![image](https://user-images.githubusercontent.com/33928277/73258456-a15be500-41bd-11ea-91cf-ce1a7960be10.png)

**Comment by sharwell** [comment] 2020-01-31 14:57
@mavasani should we just unpublish that extension? I don't believe it's being updated, and isn't the recommended approach considering it does not integrate with the builds.

**Comment by JamesEvolution** [comment] 2020-01-31 15:08
@sharwell FYI, VS2019 is recommending this extension when you refactor stuff:
![image](https://user-images.githubusercontent.com/33928277/73549901-71ba1080-443b-11ea-922a-690597997b65.png)

**Comment by mavasani** [comment] 2020-01-31 16:16
@JamesEvolution That gold bar no longer shows in VS2019 16.4

@sharwell Yes, once we can ship the analyzers in the SDK, there is no point shipping it as an extension.

**Comment by JamesEvolution** [comment] 2020-01-31 16:25
@mavasani 
I'm on VS2019 16.4.1, and it does show:
![image](https://user-images.githubusercontent.com/33928277/73555849-383ad280-4446-11ea-9074-52b25c50bac7.png)

**Comment by mavasani** [comment] 2020-01-31 17:37
Ah sorry, I mean 16.5 - I just merged that PR post the 16.4 snap. If you try on latest 16.5 Preview drop, you should not see it.

**Comment by mavasani** [comment] 2020-05-05 20:19
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/3314 - we are soon planning to deprecate the VSIX extension.

**Closed by mavasani** 2020-05-05 20:19 UTC
Labels: Area-Infrastructure
