### ISSUE TITLE
Public API analyzer does not warn on missing API files 

### ISSUE THREAD

**Issue by Digmaster** [dotnet/roslyn-analyzers#2615] opened 2019-06-21 21:26 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.PublicApianalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/)

#### Package Version

 v2.9.3 (Latest)

#### Diagnostic ID

N/A

#### Repro steps

1. Add public API analyzer to a new solution, with some public members
2. Do not add PublicAPI.Unshipped.txt or PublicAPI.Shipped.txt to the solution
3. Run public API analyzers

#### Expected Behavior
Warning about missing PublicAPI files, or at very least analyzer functionality not related to PublicAPI files (EG RS0027).

#### Actual Behavior:
Analyzer silently fails with no warnings.

**Comment by mavasani** [comment] 2019-06-21 21:29
I believe this is by design, but I'd let @sharwell and @genlu chime in.

**Comment by sharwell** [comment] 2019-06-21 22:12
We could make a new diagnostic to report this case. If a user doesn't want the diagnostic for some reason, they can disable it.

**Comment by mavasani** [comment] 2019-06-21 22:13
@sharwell - What happens if we decide to add a new analyzer to this package, and the user only intends to use the package for new analyzer?

**Comment by sharwell** [comment] 2019-06-22 04:48
@mavasani then they would disable the others 😀

**Comment by mavasani** [comment] 2019-06-26 13:23
This will be tackled by https://github.com/dotnet/roslyn-analyzers/issues/2622. Closing as a duplicate.

**Closed by mavasani** 2019-06-26 13:23 UTC
Labels: Area-DotNetAnalyzers.PublicApiAnalyzer, help wanted
