### ISSUE TITLE
helpLinkUri should be specified for every analyzer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#1269] opened 2017-07-22 22:30 UTC
The `helpLinkUri` value is used to show information when a warning appears in the error list. Every analyzer should have a `helpLinkUri` specified which points to a help page that does not change over time.

**Comment by mavasani** [comment] 2017-11-10 17:46
We need to fix this for 15.5

**Comment by mavasani** [comment] 2017-11-15 23:39
@jinujoseph @333fred @sharwell We have over 100 violations of this rule in the Roslyn analyzers repo, mostly for our custom implemented rules. How do we want to handle these? Create a landing help page for the repo and point there?

**Comment by sharwell** [comment] 2017-11-16 17:01
@mavasani StyleCop Analyzers keeps the documentation in the repository, and links there. We could at least do that for the ones that don't have pages yet on docs.microsoft.com.

**Comment by jinujoseph** [comment] 2017-11-16 18:41
I agree, lets create a wiki link that we land people , it will be easy to manage and tweet .. we can think of moving this later to docs.microsoft.com cc @kuhlenh , @AnthonyDGreen

**Comment by mavasani** [comment] 2017-11-16 18:50
We already have documentation files per-analyzer package, for example https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.md. Each of these files list the implemented rule with basic description, category, default severity and hyperlink to official documentation (msdn links currently, which can be separately updated to docs.microsoft.com), for example CA1000 can point to https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.md#ca1000-do-not-declare-static-members-on-generic-types.

**Comment by mavasani** [comment] 2017-12-15 15:56
@jinujoseph Do you think we need to complete this prior to releasing 2.6.0 stable NuGet/VSIX? If we want the help link to point to docs.microsoft.com, then someone needs to update each and every rule as well as documentation.

**Comment by jinujoseph** [comment] 2017-12-15 20:24
docs.microsoft.com update will take time ... if we have landing wiki page for each of the rule which some information then we are good for 2.6 release

**Comment by mavasani** [comment] 2017-12-15 20:43
Thinking a bit more, help URI should probably take users directly to docs link, as our landing page cannot give much information. Users might end up just having to navigate through 2 links to reach where they want. We should discuss this with the team and decide.

**Comment by jinujoseph** [comment] 2017-12-15 20:44
@kuhlenh what do you think , can doc link be updated in reasonable time

**Comment by mavasani** [comment] 2017-12-15 20:48
Also see point 5 here: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Documenting%20your%20analyzers.md

**Comment by jinujoseph** [comment] 2017-12-15 21:42
ok , for 2.6 .. helplinks are either pointing to msdn or our landing page. We will switch to doc links once available

**Comment by mavasani** [comment] 2017-12-15 22:48
@jinujoseph The landing page links for our rules are of the following format: `https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.md#rs1001-missing-diagnostic-analyzer-attribute`

I think putting this as a help link prevents us from doing any of the following changes in future:
1. Moving the docs to a different location. Currently we have separated out these docs by the containing packages and kept them in src folder. This structure seems weird to me, I think all documentation should be inside the top level `docs` folder.
2. We cannot move the rules around to different packages in future, if required.
3. The hyperlink has the rule ID as well as title within it. We will not be able to change or update the title or the documentation for any rule, else the link will be broken.

I don't think any of this is preferable. I am instead proposing the following:
1. 2.6.0: Either of the below approaches:
   1. Least work: Retain existing msdn links for documented rules and leave null/missing hyperkink for the ones without documentation on msdn/docs.microsoft.com. Rules with missing hyperlink will trigger a bing search with language name, rule ID and title string, so users should still be able to find help.
   2. More work: Replace all msdn links with docs.microsoft.com, if they exist. Keep null/missing hyperkink for the ones without documentation on msdn/docs.microsoft.com
2. 2.7.0:
   1. Replace all existing msdn links with docs.microsoft.com links.
   2. For any new rules that we then have a docs.microsoft.com link, add these links.
   3. Figure our correct location and structure for our docs, and for our internal rules or new rules that don't have docs.microsoft.com links, ensure we have stable landing page hyperlinks that do not change in future.

**Comment by mavasani** [comment] 2017-12-15 22:52
I propose doing nothing here for 2.6.0 - users can still find help either by getting to msdn page (and then being redirected to docs.microsoft.com) OR by default bing search. We don't need to block the release on this and can avoid half baked changes in 2.6.0, and address this properly in 2.7.0. Thoughts?

**Comment by jinujoseph** [comment] 2017-12-15 22:58
alright , sounds reasonable to me . @kuhlenh @dotnet/roslyn-analysis  for any concern

**Comment by heejaechang** [comment] 2017-12-18 20:40
@jinujoseph FYI. the search goes to this by default (when uri is not specified) (http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Utilities/BrowserHelper.cs,17)

this is specialized query that should show links specialized for devs. 
if we want special behavior for certain links or query, we should contact them for such behavior.

tagging @srivatsn for contacts for these query. I can't find them from my email box.

**Comment by srivatsn** [comment] 2017-12-18 22:43
If the issue is that these links are not stable enough you can create aka.ms links pointing to these docs and change them later as needed. If the issue is that there's not much useful content yet for these rules then yes I agree that doing nothing is probably as atleast that'll result in a bing search.

**Comment by mavasani** [comment] 2019-02-12 19:57
I believe this is already fixed in this repo, except for security rules, which @dotpaul is tracking with a separate bug.

**Closed** 2019-07-01 20:22 UTC
Labels: 4 - In Review, Bug, Urgency-Soon
