### ISSUE TITLE
[VSIX] Analyzers fail to load with warning AD1000

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn-analyzers#1238] opened 2017-06-19 22:41 UTC
#### Analyzer package

All (Microsoft Code Analysis 2017 extension)

#### Analyzer

All

#### Repro steps

1. Install the extension
1. Open a solution

#### Expected behavior

Analyzers should load successfully and report warnings, if any

#### Actual behavior

All analyzers fail to load. I have 176 AD1000 warnings like this:

> An instance of analyzer Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpDisposeMethodsShouldCallBaseClassDisposeAnalyzer cannot be created from C:\USERS\TOM\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D3F43BA7\EXTENSIONS\4AGMZ4EW.THC\Microsoft.NetCore.CSharp.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by mavasani** [comment] 2017-06-19 22:43
@thomaslevesque Which version of VS do you have? This extension is only supposed to work against VS version 15.3.0 and higher (Microsoft.CodeAnalysis version 2.3.0 and higher).

**Comment by thomaslevesque** [comment] 2017-06-19 22:45
(@mavasani wow, you're fast... I had accidentally submitted the issue before I was done. I fixed it now.)

> This extension is only supposed to work against VS version 15.3.0 and higher

Ah, I see. I have VS 15.2. Shouldn't this prevent me from installing the extension?

**Comment by mavasani** [comment] 2017-06-19 23:04
> Ah, I see. I have VS 15.2. Shouldn't this prevent me from installing the extension?

We had initially marked the minimum VS version for the extension to be 15.3. However, if you haven't updated your vsinstaller.exe (the VSIX extension installer) and it is an earlier version, but have latest VS update, then it was blocking the install of the extension on 15.3. We did add a CA9999 diagnostic to the extension, that will fire detecting a version mismatch between extension and underlying version of Microsoft.CodeAnalysis.

**Comment by mavasani** [comment] 2017-06-19 23:05
Tagging @kuhlenh @jinujoseph for visibility. I am going to close this issue as by design. Please let us know if you face issues with the extension. Thanks for dogfooding it!

**Closed by mavasani** 2017-06-19 23:05 UTC

**Comment by thomaslevesque** [comment] 2017-06-19 23:07
Thanks for the quick reply @mavasani.

**Comment by jinujoseph** [comment] 2017-06-19 23:26
@thomaslevesque thanks for trying the vsix as well as nuget package , if you are curious about which rules are ported you can refer [here ](http://roslynanalyzersstatus.azurewebsites.net/) . Feel free to reach out if you have any questions

**Comment by thomaslevesque** [comment] 2017-09-16 11:55
I'm no longer seeing AD0001 errors with the extension, but it's still not reporting any warning...
Using the NuGet package, I'm getting tons of exceptions during build. Is there any version of the extension or package that is supposed to work?

**Comment by thomaslevesque** [comment] 2017-09-16 12:10
Ah, I just realized I had to enable IOperation. This should probably be documented somewhere, as it's far from obvious...
