### ISSUE TITLE
Code Metrics Fail When Using C# 9 Function Pointers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#5690] opened 2021-11-02 03:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-Metrics-Fail-When-Using-C-9-Functi/1567736)._

---
Create a C# project using .NET 5 or later
Add a unmanaged function pointer to the code
Running code metrics at this point will fail
Commenting out the unmanaged function pointer causes code metrics to work again.

In my recorded steps I run a successful code metrics with a unmanaged function pointer commented out first, then I uncomment it and run code metrics again where it will fail.

---
#### Feedback Bot on 11/1/2021, 01:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/1/2021, 10:11 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by DangerRoss** [comment] 2021-11-02 13:55
When I raised this on VS feedback I couldn't find a duplicate. However I just found this bug is already reported in this repo https://github.com/dotnet/roslyn-analyzers/issues/5511

**Comment by mavasani** [comment] 2021-11-02 13:56
Thanks @DangerRoss, closing this as a duplicate of #5511

**Closed by mavasani** 2021-11-02 13:56 UTC
Labels: Bug, help wanted, Area-CodeMetrics
