### ISSUE TITLE
Analyzer for CA1859 crashes with System.IndexOutOfRandeException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#6962] opened 2023-09-22 12:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Analyzer-for-CA1859-crashes-with-System/10473411)._

---
[severity:It bothers me. A fix would be nice]
Environment:
Visual Studio Preview, .NET 8 RC1

Problem:
In certain cases the analyzer for CA1859 seems to run into type inference issues and throws the following exception:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Analyzer.Utilities.AnalyzerOptionsExtensions.TryGetSyntaxTreeForOption(ISymbol symbol, SyntaxTree& tree)
   at Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer.<>c__DisplayClass9_1.<Initialize>b__4(ISymbol symbol)
   at Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer.Collector.HandleInvocation(IInvocationOperation op)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----
```
Workaround:
Casting the variable to its type seems to fix the error. 

Example:
```
public class TestClass
{
    public static void TestMethod()
    {
        var list1 = new List<string>();
        var list2 = new List<string>();
        var list3 = list1.Zip(list2);

        // Analysis works fine
        foreach (var value in (IEnumerable<(string First, string Second)>)list3)
        {
            Console.WriteLine(value.First.ToString());
            Console.WriteLine(value.Second.ToString());
        }

        // CA1859 crashes
        foreach (var value in list3)
        {
            Console.WriteLine(value.First.ToString());  // CA1859 crashes -> AD0001
            Console.WriteLine(value.Second.ToString()); // CA1859 crashes -> AD0001
        }
    }
}
```

---
#### Feedback Bot on 9/22/2023, 03:42 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment] 2023-09-22 13:14
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/6852

**Closed by mavasani** 2023-09-22 13:14 UTC
