### ISSUE TITLE
CA 1416 Should not be turned on by default for .Net 5 Projects.

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/roslyn-analyzers#4678] opened 2021-01-08 02:38 UTC
I converted a project that has worked on WinForms for 15 years, and now you decide to show a message wrongly that says 'This project is supprted on Windows 7.0 and later. I am on Windows 10, and I created a new .Net5 Class Library to hold my project:

Nuget
DataJuggler.Win.Controls

Git Hub:
https://github.com/DataJuggler/DataJuggler.Win.Controls

I completely converted this to .Net 5 before I realized you are showing anyone who looks in a designer file by default a message, and this error causes the designer to not open.

Please make this an opt in, not by default.

I really don't like a single one of your CA's, is there a way to turn them all off?

And since I am in the Rosylyn-Analyzers, Rosyln introduced a bug with regions.

Actually you have two bugs with regions.

1. Lines of code get indented one line to the left more than they should if you use regions. This worked in 2013 one of your engineers confirmed and told me it would be fixed in 2015. It never was.
2. Your search replace does not change region text. You have ignored this issue for several years.

Why did you get me hooked on regions in 2002, enough to write this VS package:

https://github.com/DataJuggler/Regionizer 

And then abandon love for regions by 2015.

End rant.

End Code Analyzers. My code is fine, its your compiler that needs refinement.

**Comment by mavasani** [comment] 2021-01-08 03:48
See https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysismode to disable all CA rules by default.

**Comment by DataJuggler** [comment] 2021-01-08 03:50
Thank you. I closed Visual Studio and reopened it and the issue went away.

Sorry to vent. 3 beers and a stolen election and I didn’t storm the white house, but I vented to you.

Less harm.

Thanks again

**Comment by Youssef1313** [comment] 2021-01-10 18:49
In the repository you linked, I see your TFM as `net5.0-windows`, so AFAIK, the warning shouldn't occur.

Tagging @buyaa-n

**Comment by DataJuggler** [comment] 2021-01-10 18:52
There is a bug now if you create a new Windows Forms .Net project, which is supposed to be for .Net 5, creates the new project as as .Net Core 3.1.

This might have something to do with the error. I have to change every new WinForms .Net project to .Net 5.

The error did go away when I closed Visual Studio so at least I know what to do. I have trained myself that is the first thing I do if any thing weird happens in VS.

**Comment by Youssef1313** [comment] 2021-01-10 19:18
@DataJuggler So the issue is that when you create a WinForms project from the template shown in the following image, the created project isn't .NET 5.0, but a .NET Core 3.1 app.

![image](https://user-images.githubusercontent.com/31348972/104132707-bc504680-5387-11eb-94aa-876e7265b921.png)

I verified this using 16.8.2, and it indeed looks like a bug. This needs to be redirected to the appropriate team.

**Comment by buyaa-n** [comment] 2021-01-11 19:16
> I verified this using 16.8.2, and it indeed looks like a bug.

I am not sure if .net5 is available in that version, when i create same project with VS preview version i see an option to choose target framework from .Net 5.0 or  .NET Core 3.1 app. 
![image](https://user-images.githubusercontent.com/45579687/104227114-bdbc5600-53fd-11eb-990a-c7efd74014fd.png)
Plus don't see any warnings for both targets, used Version 16.9.0 Preview 3.

> However, this shouldn't affect CA1416. The rule doesn't report any warnings if you target versions before .NET 5.0 (unless you specifiy dotnet_code_quality.enable_platform_analyzer_on_pre_net5_target=true in editorconfig).

That is right, it should not warn below 5.0 version, i don't see the warnings with with WinForms project targeting .NET Core 3.1, @DataJuggler it would be great if you could attach sample repro project or mention exact steps for repro

**Comment by DataJuggler** [comment] 2021-01-11 19:29
As I mentioned, once I closed Visual Studio and reopened it went away.

I am on the latest Visual Studio, 16.8.3. Is this the screen the option for Target Framework is on in the Preview version? (Just making sure I am looking in the right place).

I have seen the Target Framework option for other templates, but I do not see a place to enter Target Framework for a new .Net 5 WinForms project:

I am not sure if I can reproduce the issue or not.

[cid:image001.png@01D6E81D.C5EFC8D0]

**Comment by buyaa-n** [comment] 2021-01-11 19:36
> Is this the screen the option for Target Framework is on in the Preview version?

Yes in preview version

> I am not sure if I can reproduce the issue or not.

if you are not seeing this issue anymore could we close this issue?

**Comment by DataJuggler** [comment] 2021-01-11 19:38
Yes you can close it. Any idea when this preview feature will be released into the main Visual Studio?

Thank you. Sorry I vented.

**Comment by buyaa-n** [comment] 2021-01-11 20:12
> Yes you can close it. 

Thanks, closing

> Any idea when this preview feature will be released into the main Visual Studio?

Sorry i do not know that, but seems you can enable the preview features from options https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0#prerequisites

**Closed by buyaa-n** 2021-01-11 20:12 UTC
