### ISSUE TITLE
Public API codefix crash when attempt to add additional APi to list

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn-analyzers#2219] opened 2019-03-18 19:07 UTC
```
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(DocumentId documentId,SourceText newText)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyAdditionalDocumentTextChanged(DocumentId documentId,SourceText newText)
   at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---

```

**Comment by mavasani** [comment] 2019-03-18 19:09
I think there is a duplicate bug in Roslyn for this - most likely a crash in the code fix engine, not the code fixer itself. I will try to find the bug in Roslyn repo.

**Comment by genlu** [comment] 2019-03-18 19:22
So it NRE after trying to get the additional file using `Solution.GetDocument`. I'm not familiar with this part but `Solution.GetAdditionalFile` returns successfully.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs,1067

**Comment by genlu** [comment] 2019-03-18 19:26
Found the issue in roslyn 
https://github.com/dotnet/roslyn/issues/33644

**Comment by 333fred** [comment] 2019-03-18 21:47
That itself is a dupe of https://github.com/dotnet/roslyn/issues/33884.

**Comment by 333fred** [comment] 2019-03-18 21:47
Workaround is to close the unshipped api txt file when attempting to use the codefix.

**Comment by dibarbet** [comment] 2019-04-15 17:57
I'm getting the same issue but with a different stack trace.
Closing the unshipped API file doesn't help in this case (it wasn't even open).

```
System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.<>c__DisplayClass8_0.<TryGetSingleChangedText>b__1(DocumentId id)
   at System.Linq.ImmutableArrayExtensions.Any[T](ImmutableArray`1 immutableArray,Func`2 predicate)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.TryGetSingleChangedText(Solution oldSolution,ImmutableArray`1 operationsList)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```

**Closed** 2021-05-06 17:05 UTC
Labels: Area-DotNetAnalyzers.PublicApiAnalyzer, Bug, Urgency-Soon
