### ISSUE TITLE
CA2235 int is not serializable

### ISSUE THREAD

**Issue by bencyoung** [dotnet/roslyn-analyzers#2156] opened 2019-02-27 14:33 UTC
I have the latest public releases of the analyser packages:

```xml
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.0.2" IncludeAssets="Analyzers;Build" PrivateAssets="All" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.3" IncludeAssets="Analyzers;Build" PrivateAssets="All" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis" Version="2.10.0" IncludeAssets="Analyzers;Build" PrivateAssets="All" />
    <GlobalPackageReference Include="Microsoft.Net.Compilers" Version="2.10.0" IncludeAssets="Analyzers;Build" PrivateAssets="All" />
```

and I'm getting the error:

```
 error CA2235: Field LineNumber is a member of type LineInfo which is serializable but is of type int which is not serializable 
```

all related issues I've found have been closed, so I assume it's expected to be fixed in the most recent versions?

**Comment by mavasani** [comment] 2019-02-27 16:50
Most likely dupe of https://github.com/dotnet/roslyn-analyzers/issues/1712. Can you please try with 2.9.x preview packages from https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers?

**Comment by bencyoung** [comment] 2019-03-28 09:57
I can confirm I still get this with:

```
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.1.1-rc.114" IncludeAssets="Analyzers;Build" PrivateAssets="All" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.0" IncludeAssets="Analyzers;Build" PrivateAssets="All" />
    <GlobalPackageReference Include="Microsoft.Net.Compilers" Version="3.0.0-beta4-final" IncludeAssets="Analyzers;Build" PrivateAssets="All" />
```

**Comment by mavasani** [comment] 2019-03-28 10:57
Can you please provide a repro?

**Comment by bencyoung** [comment] 2019-03-28 12:01
This one reproduces it for me. 

[BuildIssue.zip](https://github.com/dotnet/roslyn-analyzers/files/3017787/BuildIssue.zip)

dotnet is 2.2.103
VS is 15.9.7

**Comment by uandrei** [comment] 2019-05-01 13:24
Just updated our product on the 2.9.2 of the FxCopAnalyzers and still have this issue

**Comment by mavasani** [comment] 2019-05-03 21:18
@bencyoung @uandrei I am unable to repro the issue for the below test with version 2.9.2 of the analyzer package. CA2235 does not fire for the integer field.

```csharp
using System;

[Serializable]
public class B
{
    public B(int intParam, C cParam)
    {
        this.IntField = intParam;
        this.UserDefinedTypeField = cParam;
    }

    internal int IntField;

    internal C UserDefinedTypeField;
}

public class C
{
}
```

![repro](https://user-images.githubusercontent.com/10605811/57166197-46bc6680-6dae-11e9-8062-b2ca53dfe1c3.png)

**Comment by mavasani** [comment] 2019-05-03 23:37
I believe I found a repro: https://github.com/dotnet/roslyn-analyzers/issues/2381#issuecomment-489261148. Also have a PR out to fix it...

**Closed** 2019-05-07 19:52 UTC
