### ISSUE TITLE
NRT support for CA1062

### ISSUE THREAD

**Issue by sungam3r** [dotnet/roslyn-analyzers#4230] opened 2020-09-26 22:13 UTC
```c#
        #nullable enable

        [TestCase(typeof(int))]
        [TestCase(typeof(string))]
        public void CheckType(Type type)
        {
            Assert.NotNull(type.Name);  // CA1062	In externally visible method 'void MyClass.CheckType(Type type)', validate parameter 'type' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.	
        }
```

Actually this warning **may** be treated as false positive. I know that this method can still be called with `null`, for example just `CheckType(null!)`, but I think that it is worth to modify CA1062 analyzer to take NRT into consideration.

**Comment by mavasani** [comment] 2020-09-26 22:27
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/3218

**Closed by mavasani** 2020-09-26 22:27 UTC
