### ISSUE TITLE
Separate CA1704 for single letter identifiers

### ISSUE THREAD

**Issue by FreeAndNil** [dotnet/roslyn-analyzers#5473] opened 2021-09-14 09:06 UTC
### Analyzer

**Diagnostic ID**: [CA1704](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1704)

### Describe the improvement

The current implementation of #443 (#1111) also checks for single-letter identifiers.
This check should be separated in an own diagnostic ID so that people can decide whether the want warnings for those cases or not.

### Describe suggestions on how to achieve the rule

The existing analyzer will provide a new diagnostic ID for those cases.

### Additional context

See discussion at the end of #1111 with @pakdev & @mavasani

**Comment by Youssef1313** [comment] 2022-12-28 19:10
Duplicate of #5183

**Closed by Youssef1313** 2022-12-28 19:10 UTC
Labels: Feature Request, Area-Text.Analyzers, help wanted
