### ISSUE TITLE
Suppressed in code with SuppressMessageAttribute do not working

### ISSUE THREAD

**Issue by xmarshal** [dotnet/roslyn-analyzers#2235] opened 2019-03-21 04:38 UTC
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.3

#### Diagnostic ID

Any

#### Repro steps

1. Compile projetc with any CA issue
2. Select Supress in Source 

#### Expected behavior
diagnostic issue suppressed in code with SuppressMessageAttribute
#### Actual behavior
diagnostic issue suppressed in code with pragma

**Comment by genlu** [comment] 2019-03-27 00:40
@xmarshal Just to clarify, are you using ErrorList in Visual Studio to suppress the diagnostics? 
@heejaechang This behavior is by design, right?

**Comment by xmarshal** [comment] 2019-03-27 02:23
@genlu I use "Microsoft.CodeAnalysis.FxCopAnalyzers", use Resharper, use VS sugession and use ErrorList, for all methods I can't supress in Source with SuppressMessageAttribute

**Comment by Gav-Brown** [comment] 2019-04-20 20:46
@xmarshal For Visual Studio this will be resolved by dotnet/Roslyn#17218

**Comment by mavasani** [comment] 2019-06-24 05:01
@Gav-Brown is correct. Resolving as external.

**Closed by mavasani** 2019-06-24 05:01 UTC
