### ISSUE TITLE
Analyzer driver threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#1247] opened 2017-07-03 07:20 UTC
#### Repro steps

1. Open Project System.sln at this commit: https://github.com/dotnet/project-system/commit/1e03b3e1de78e1f1ebc37f622c04c2b73747a4e8.
2. Turn on Full Solution Analysis

#### Actual behavior

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0002	Analyzer driver threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: specialType'.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests		1	Active	Analyzer driver threw the following exception:
'System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: specialType
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSpecialType(SpecialType specialType)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.GetDefaultParameterValue(SyntaxNode syntax, ParameterSymbol parameter, ThreeState enableCallerInfo, LocalRewriter localRewriter, Binder binder, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.AppendMissingOptionalArguments(SyntaxNode syntax, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, Boolean expanded, Binder binder, ArrayBuilder`1 missingParameters, ArrayBuilder`1 argumentsBuilder)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.BuildArgumentsInEvaluationOrder(SyntaxNode syntax, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, Boolean expanded, ImmutableArray`1 argsToParamsOpt, ImmutableArray`1 arguments, Binder binder)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeArgumentsInEvaluationOrder(Binder binder, SyntaxNode syntax, ImmutableArray`1 arguments, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, Boolean expanded, ImmutableArray`1 argsToParamsOpt, Boolean invokedAsExtensionMethod)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.<>c__DisplayClass26_0.<DeriveArguments>b__0(BoundExpression n)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.DeriveArguments(BoundExpression boundNode, Binder binder, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, ImmutableArray`1 boundArguments, ImmutableArray`1 argumentNamesOpt, ImmutableArray`1 argumentsToParametersOpt, ImmutableArray`1 argumentRefKindsOpt, ImmutableArray`1 parameters, Boolean expanded, SyntaxNode invocationSyntax, Boolean invokedAsExtensionMethod)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Microsoft.CodeAnalysis.Semantics.IHasArgumentsExpression.get_ArgumentsInEvaluationOrder()
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitInvocationExpression(IInvocationExpression operation)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitVariableDeclaration(IVariableDeclaration operation)
   at Microsoft.CodeAnalysis.Semantics.VariableDeclaration.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitVariableDeclarationStatement(IVariableDeclarationStatement operation)
   at Microsoft.CodeAnalysis.CSharp.BoundLocalDeclaration.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitBlockStatement(IBlockStatement operation)
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(OperationVisitor visitor)
   at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(IOperation operation)
   at Microsoft.CodeAnalysis.Semantics.OperationExtensions.DescendantsAndSelf(IOperation operation)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationsToAnalyze(ImmutableArray`1 operationBlocks)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
-----
```

**Comment by mavasani** [comment] 2017-07-03 07:58
@genlu - did you fix this recently? Do you have the issue number?

**Comment by mavasani** [comment] 2017-07-03 07:59
Found it - dupe of https://github.com/dotnet/roslyn/issues/20330

**Closed by mavasani** 2017-07-03 07:59 UTC
