### ISSUE TITLE
DeclarePublicAPI doesn't handle VB autoproperties

### ISSUE THREAD

**Issue by Pilchie** [dotnet/roslyn-analyzers#1082] opened 2016-11-01 00:34 UTC
#### Analyzer package

Roslyn.Diagnostics.Analyzers

#### Analyzer

Example: DeclarePublicAPIAnalyzer

#### Repro steps

```VB
Public Class C
    Public Property P As Integer
End Class
```
#### Expected behavior
Should report this as public API

#### Actual behavior
It does not

#### NOTES
This happens because we only look at methods, and the analyzer engine doesn't pass us accessors that are `IsImplicitlyDeclared`.

**Comment by mavasani** [comment] 2016-11-01 00:36
I am sure there is a dupe of this already, can't find it now

**Comment by mavasani** [comment] 2017-04-15 00:13
The underlying compiler bug was resolved as by design: https://github.com/dotnet/roslyn/issues/11258

We need to identify a way to workaround this in the analyzer.

**Comment by mavasani** [comment] 2019-07-01 19:25
This has been fixed by @CyrusNajmabadi

**Closed by mavasani** 2019-07-01 19:25 UTC
Labels: Bug
