### ISSUE TITLE
CA1822 raises for custom TheoryAttribute

### ISSUE THREAD

**Issue by Crown0815** [dotnet/roslyn-analyzers#5110] opened 2021-05-18 12:22 UTC
### Analyzer

**Diagnostic ID**: [CA1822](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822): `Mark members as static`

### Analyzer source

**VisualStudio**: Built-in CA analyzers, `dotnet --version 5.0.201`
```
Microsoft Visual Studio Professional 2019
Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional
```

### Describe the bug

I am using a custom `Theory` attribute based on the `Theory` attribute in the `NUnit` framework. I am not inheriting from the `Theory` attribute but reimplementing it with small changes. When I use the new attribute I get the CA1822 warning on my test methods. 

It appears to me like a duplicate of #2785 but I am not 100% certain since that issue was closed as being not reproducible almost 2 years ago.

### Steps To Reproduce

1. Add project set up as follows, e.g. `Testproject.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0"/>
  </ItemGroup>

</Project>
```

2. Add a test class set up as follows, e.g. `Tests.cs`
```c#
using System;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using NUnit.Framework.Internal.Builders;

namespace TestProject
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public class OtherTheoryAttribute : CombiningStrategyAttribute, ITestBuilder, IImplyFixture
    {
        public OtherTheoryAttribute() : base(
            new CombinatorialStrategy(),
            new ParameterDataProvider(new DatapointProvider(), new ParameterDataSourceProvider()))
        {
        }
    }

    public class Tests
    {
        [OtherTheory]
        public void Test1()
        {
            Assert.Pass();
        }
    }
}
```

### Expected behavior

No warning on the test method

### Actual behavior

Warning on the test method (see image below)
![image](https://user-images.githubusercontent.com/36126706/118650090-59166b00-b7e4-11eb-8eca-9da7780ef877.png)

## Additional context

Nothing relevant that I am aware of.

**Comment by Youssef1313** [comment] 2021-05-18 13:53
Related to (or duplicate of): https://github.com/dotnet/roslyn-analyzers/issues/4995.

**Comment by louis-z** [comment] 2021-05-25 00:04
I can look into it, if no one else has.

**Comment by mavasani** [comment] 2021-05-25 02:05
Yes, please do

**Closed** 2021-06-28 09:40 UTC
Labels: Area-Microsoft.CodeQuality.Analyzers, Bug, False_Positive, help wanted
