### ISSUE TITLE
false positive CA2235

### ISSUE THREAD

**Issue by fgenolini** [dotnet/roslyn-analyzers#1712] opened 2018-06-06 09:14 UTC
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers, version [2.6.1](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.1)

#### Analyzer

MarkAllNonSerializableFields

#### Repro steps

1. Upgrade from 2.6.0 to 2.6.1 using NuGet package manager on Visual Studio 2017 15.7.3
1. Rebuild C# .Net standard 2.0 class library that previously had 0 warnings
1. false positive for CA2235 for types with [Serializable] attribute that contain data members (not properties) also annotated with [Serializable] or scalar types (where [Serializable] is implied)

#### Expected behavior

0 warnings, just like 2.6.0 reported

#### Actual behavior

false positives on CA2235

**Comment by mavasani** [comment] 2018-06-06 12:37
@fgenolini Can you please provide a simple repro code snippet?

**Comment by mavasani** [comment] 2018-06-06 12:49
Never mind, I missed the part that this is for `C# .Net standard 2.0 class library` - I can repro it now.

**Comment by mavasani** [comment] 2018-06-06 12:52
Likely due to the fact that the analyzer was written for NetFramework, and has [this](https://github.com/dotnet/roslyn-analyzers/blob/2858e1048ea2d4738bd94af33ad44855b291140f/src/Microsoft.NetFramework.Analyzers/Core/SerializationRulesDiagnosticAnalyzer.cs#L274) workaround, which iiss likely failing for NetStandard projects. We will need to move the analyzer to NetCore analyzers package, and add unit test(s) for th scenario.

**Comment by bordecal** [comment] 2018-08-02 17:16
I am encountering similar problems when running against .NET Standard 2.0 libraries.  To make it extra interesting, the fields in question are actually _static_ string fields, which should presumably be ignored entirely by this rule.  (The problem is present in both 2.6.1 and 2.6.2-beta1.)

**Comment by mavasani** [comment] 2018-08-09 20:44
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/1758

**Comment by mavasani** [comment] 2018-08-09 20:45
Note that the fix will be in 2.9.XXX packages.

**Closed by mavasani** 2018-08-09 20:44 UTC
Labels: 4 - In Review, Area-Microsoft.NetCore.Analyzers, Area-Microsoft.NetFramework.Analyzers, Bug
