### ISSUE TITLE
Rule CA2255 is conceptually broken and needs to be removed.

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/roslyn-analyzers#5756] opened 2021-12-07 01:54 UTC
### Analyzer

**Diagnostic ID**: [CA2255](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2255)

### Describe the improvement

The diagnostic describes the `ModuleInitializer` attribute as being only for application initialization and "advanced code generator scenarios."  But the most obvious use case for this feature is nothing of the sort: this was practically tailor-made for *plugin registration.*

Upon migrating from .NET 5 to .NET 6, every single plugin project is being harassed by this new analyzer.  It needs to stop existing, as it betrays a fundamental misunderstanding of the way `ModuleInitializer` is being used in real-world code.

### Describe suggestions on how to achieve the rule

Delete CA2255 entirely.

**Comment by CyrusNajmabadi** [comment] 2021-12-07 01:59
Closing out.  This was due to decision here https://github.com/dotnet/runtime/issues/43328, from convo here: https://github.com/dotnet/runtime/pull/43268

@jeffhandley As to if we want to open this back up.  But, AFAICT, this is expected and intentional.  Code needs to be explicitly opt in and suppress this, making the statement that it knows what it is doing and can accept the downsides laid out here with this feature.

**Closed by CyrusNajmabadi** 2021-12-07 01:59 UTC

**Comment by sharwell** [comment] 2021-12-07 02:01
@masonwheeler My recommendation is to add a .props file to the NuGet package which adds a module initializer, and disable CA2255 there.

**Comment by masonwheeler** [comment] 2021-12-07 02:15
> Closing out. This was due to decision here [dotnet/runtime#43328](https://github.com/dotnet/runtime/issues/43328), from convo here: [dotnet/runtime#43268](https://github.com/dotnet/runtime/pull/43268)

Please reopen.  That decision does not appear to have even *considered* plugins as a possible use case.  It's easy to come to the wrong conclusion when starting from a bad premise.

**Comment by CyrusNajmabadi** [comment] 2021-12-07 02:22
> If you're using a module initializer, that's precisely what you want. 

Unless it causes a problem.  If so, this analyzer notifies you of that.  If you do, however, think your use case is appropriate and a non-issue, then suppression of the analyzer is the appropriate way to go.  This fits with all analyzers that attempt to prevent mistakes, but which may catch use cases that are totally appropriate.

**Comment by sharwell** [comment] 2021-12-07 02:25
> > Closing out. This was due to decision here [dotnet/runtime#43328](https://github.com/dotnet/runtime/issues/43328), from convo here: [dotnet/runtime#43268](https://github.com/dotnet/runtime/pull/43268)
> 
> Please reopen. That decision does not appear to have even _considered_ plugins as a possible use case, and the rationale given -- that it can keep stuff from being linked out by the linker -- is a bit silly. If you're using a module initializer, _that's precisely what you want._ If your assembly contains so many unrelated elements that this becomes a real issue, it's probably a sign that the assembly should be split up.
> 
> It's easy to come to the wrong conclusion when starting from a bad premise.

I would suggest creating a new issue in dotnet/runtime with this request (that repository is where the analyzer in question was designed and any changes would need to be approved there before being implemented in this repository), and update the text of the proposal to include the new consideration of the issues linked in the discussion above.

**Comment by masonwheeler** [comment] 2021-12-07 02:27
> If you do, however, think your use case is appropriate and a non-issue, then suppression of the analyzer is the appropriate way to go.

Not when you have the legitimate use case in dozens of places and there doesn't appear to be any way to disable this misbegotten analyzer globally.  You're telling me I need to do this on every usage *and every future usage!*  I'm saying that's crazy.  It's not my fault that the people who created this didn't understand the use cases.

Again, please reopen.

**Comment by CyrusNajmabadi** [comment] 2021-12-07 02:28
@masonwheeler Please see https://github.com/dotnet/roslyn-analyzers/issues/5756#issuecomment-987508958

**Comment by CyrusNajmabadi** [comment] 2021-12-07 02:30
> Not when you have the legitimate use case in dozens of places and there doesn't appear to be any way to disable this misbegotten analyzer globally. 

Could you clarify why the solutions provided offline are not sufficient here? Can you not put the appropriate suppression in your editorconfig or global analyzer config files?

**Comment by masonwheeler** [comment] 2021-12-07 02:48
@sharwell [Done.](https://github.com/dotnet/runtime/issues/62472)
