### ISSUE TITLE
GenerateDocumentationAndConfigFiles does not work on linux

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-analyzers#4587] opened 2020-12-17 02:25 UTC
The tool located [here](https://github.com/dotnet/roslyn-analyzers/tree/master/src/Tools/GenerateDocumentationAndConfigFiles) relies on windows specific line endings to work correctly and was disabled in linux builds in https://github.com/dotnet/roslyn-analyzers/pull/4444. We should fix this and enable validation on linux builds

**Comment by Evangelink** [comment] 2020-12-17 09:50
@jmarolf I can't find anything windows specific in these files. Could it be something that was fixed in between versons?

**Comment by Youssef1313** [comment] 2021-02-04 15:29
@Evangelink I feel it's the calls to `AppendLine`. It may be adding `Environment.NewLine` (which could be either `\r\n` or `\n`). But then it compares that with repo files (which are using `\r\n`). Hence, the comparison fails and the tool would think that files are outdated. We may consider replacing `AppendLine()` with `Append("\r\n")`.

**Comment by Youssef1313** [comment] 2021-02-04 17:30
Alright, My previous comment isn't correct (I don't know why exactly :smile:)

The CI failure for Linux is caused by a multi-line fullDescription in sarif files. See diff between Windows and Linux:

![image](https://user-images.githubusercontent.com/31348972/106931114-ea267200-671e-11eb-82ba-c0877732a980.png)

**Comment by Evangelink** [comment] 2021-02-04 17:52
Ahaha I did the exact same thing in another company for comparing sarif files... I went with normalizing to `\n`.

**Comment by Youssef1313** [comment] 2021-02-04 18:13
@Evangelink Sounds good.

**Comment by Evangelink** [comment] 2021-02-04 18:15
Well that's what I hacked but I don't know if that's really the good way forward.

**Comment by jmarolf** [comment] 2021-02-04 18:27
I think normalizing on \n is the right choice here. Thanks for taking a look!

**Closed** 2021-02-08 04:25 UTC
Labels: Area-Infrastructure, Bug, help wanted
