### ISSUE TITLE
NullReferenceException with CA1825

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn-analyzers#1446] opened 2017-12-06 01:16 UTC
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers, version [2.6.0-beta2]

#### Analyzer

CA1825 Avoid zero-length array allocaitons

#### Repro steps
1. Clone the ScreenToGif repository from https://github.com/NickeManarin/ScreenToGif
2. Open, restore packages and install the above nuget analyzer package.
3. Enable full solution analysis and run it.
4. Navigate to the only instance of CA1825 and click the warning location to see if there is a fix.
#### Expected behavior
The quick info either show lightbulb/show potential fixes or it doesn't.
#### Actual behavior
An exception was thrown
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetType(SyntaxNode declaration)
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.ConvertToArrayEmpty(<Unknown Parameters>)
   at async Microsoft.NetCore.Analyzers.Runtime.AvoidZeroLengthArrayAllocationsFixer.<>c__DisplayClass3_0.<RegisterCodeFixesAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by mattscheffer** [comment] 2017-12-06 01:16
@mavasani

**Comment by 333fred** [comment] 2017-12-06 01:28
This is likely a dupe of https://github.com/dotnet/roslyn-analyzers/issues/1298.

**Comment by mavasani** [comment] 2017-12-06 05:05
I have merged the PR fixing that issue. @mattscheffer Kindly validate once we have a new myget package on https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers

**Comment by mavasani** [comment] 2017-12-12 17:39
@mattscheffer Please re-open if it repros on beta2 package.

**Closed by mavasani** 2017-12-12 17:39 UTC
Labels: Area-Microsoft.CodeAnalysis.Analyzers, Bug
