### ISSUE TITLE
CA1827 Throws an exception in fixer if invoke `Count` without parethesis

### ISSUE THREAD

**Issue by dovisutu** [dotnet/roslyn-analyzers#3179] opened 2019-12-21 11:00 UTC
**Version Used**: 
2.9.8
**Steps to Reproduce**:

1. Enter the following code in a vb code file: (or equivalent cs file)
```vb
Module B
    Sub K(args As String())
        If args.Count = 0 Then Return ' CA1827: Count() is used where Any() could be used instead to improve performance.
                                      ' CA1829: Use the "Length" property instead of Enumerable.Count().
    End Sub
End Module
```
2. See that both CA1827 and CA1829 are triggered.
3. Hover on the `args.Count = 0` and click on `show possible fixers`

**Expected Behavior**:
both CA1827(DoNotUseCountWhenAnyCouldBeUsed) and CA1829(UsePropertyInsteadOfCountMethodWhenAvailable)'s fixers will show up.
**Actual Behavior**:
Visual Studio shows that `BasicDoNotUseCountWhenAnyCouldBeUsedFixer` have reached a exception as follows:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.WithTrailingTrivia[TSyntax](TSyntax node,IEnumerable`1 trivia)
   at async Microsoft.NetCore.Analyzers.Performance.DoNotUseCountWhenAnyCanBeUsedFixer.DoNotUseCountWhenAnyCanBeUsedCodeAction.GetChangedDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
and the shown CA1827 fixer doesn't work at all. Sometimes the CA1829 fixer doesn't show up, probably jammed by the broken CA1827 fixer.

**Comment by jinujoseph** [comment] 2020-01-08 20:16
cc @mavasani

**Comment by mavasani** [comment] 2020-01-08 20:44
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/3087

**Closed by mavasani** 2020-01-08 20:44 UTC
