### ISSUE TITLE
CA1801 ignores use in deep collection initializer

### ISSUE THREAD

**Issue by flcdrg** [dotnet/roslyn-analyzers#1084] opened 2016-11-16 04:22 UTC
#### Analyzer package

Microsoft.Maintainability.Analyzers

#### Analyzer

ReviewUnusedParameters

#### Repro steps

The following code triggers CA1801 on the count parameter of the `TheMethod` method:

    using System.Collections.Generic;

    namespace ClassLibrary4
    {
        public class Class1
        {
            public void TheMethod(int count)
            {
                var testParams = new OtherClass(new List<int[]> { new[] { count } });
            }
        }

        public class OtherClass
        {
    #pragma warning disable CA1801 // Review unused parameters
            public OtherClass( List<int[]> intses)
    #pragma warning restore CA1801 // Review unused parameters
            {
            }
        }
    }

#### Expected behavior

Analyzer could not flag this as a problem.

#### Actual behavior

error CA1801: Parameter count of method TheMethod is never used. Remove the parameter or use it in the method body.

**Comment by mavasani** [comment] 2016-11-16 04:50
I think there is an existing IOperation bug for this.

**Comment by mavasani** [comment] 2017-04-15 00:09
Dupe of https://github.com/dotnet/roslyn/issues/8884#issuecomment-217131239

**Closed by mavasani** 2017-04-15 00:09 UTC
