### ISSUE TITLE
CA1014: Cannot be silenced

### ISSUE THREAD

**Issue by bdquig** [dotnet/roslyn-analyzers#5149] opened 2021-06-11 10:59 UTC
I have CA1014 silenced in my .editorconfig, but they keep showing up in my warning list.

I have the following line in my .editorconfig at the root of my source folder:
dotnet_diagnostic.CA1014.severity = silent

**Comment by Youssef1313** [comment] 2021-06-12 09:14
@bdquig Does your project have any code files in it?

This issue can happen when you have only a `csproj` without any `.cs` files.

See https://github.com/dotnet/roslyn/issues/51868

**Comment by bdquig** [comment] 2021-06-15 00:40
I have a solution with over 30 projects.  only 1 has no .cs files.  all projects are showing the warning

**Comment by Youssef1313** [comment] 2021-06-15 11:54
Does adding any dummy `.cs` file to this project fixes the warning?

- If it fixes it, then the issue could be closed as duplicate of dotnet/roslyn#51868 (you may want to add a comment there that the issue affects all projects.
- If it doesn't fix it, then it may be easier to investigate if you can share a repro.

**Comment by Evangelink** [comment] 2022-07-12 09:49
Ping @bdquig

**Comment by Youssef1313** [comment] 2022-12-12 19:19
@bdquig Can you please confirm?

**Comment by Youssef1313** [comment] 2022-12-14 18:03
This is also possibly fixed with https://github.com/dotnet/roslyn-analyzers/pull/4402, so please confirm you are on the latest NetAnalyzers version.

**Comment by mavasani** [comment] 2022-12-14 18:52
I think we should close this out and let the customer reopen if they can still reproduce it

**Closed** 2022-12-14 18:56 UTC
Labels: Bug, Need More Info, Area-Microsoft.CodeQuality.Analyzers, help wanted
