### ISSUE TITLE
CA2016: Forward cancellation token codefix is incorrect

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4842] opened 2021-02-12 20:40 UTC
See https://github.com/dotnet/efcore/issues/22667

cc: @carlossanlop 

given a type that contains overloads like this:
```csharp

public class C{
  public ValueTask<object?> FindAsync(params object?[]? keyValues) {}
  public ValueTask<object?> FindAsync(object?[]? keyValues, CancellationToken cancellationToken)
}
```

and is called like this:
```csharp
async Task M(string[] args, CancellationToken token)
{
    var c = new C();
    var result = await c.FindAsync(5);
}
```

## Actual

today CA2016 suggests this as a codefix:
```csharp
async Task M(string[] args, CancellationToken token)
{
    var c = new C();
    var result = await c.FindAsync(5, cancellationToken: token); // Error CS1503 Argument 1: cannot convert from 'int' to 'object?[]?'
} 
```

## Expected

if items at the previous call site was part of a `params` array then the codefix should wrap those elements inside a `new object[]` expression

```csharp
async Task M(string[] args, CancellationToken token)
{
    var c = new C();
    var result = await c.FindAsync(new object?[] { 5 }, token);
}
```

an alternative could be 
```csharp
async Task M(string[] args, CancellationToken token)
{
    var c = new C();
    var result = await c.FindAsync(new [] { (object?)5 }, token);
}
```

**Comment by jmarolf** [comment] 2021-02-12 21:30
We may want to change the analyzer behavior to only fire in situations where we are calling a method with a cancellation token as an optional parameter with a special list of known framework apis where the two method signatures are considered semantically equivalent.

**Comment by sharwell** [comment] 2021-02-12 21:40
I believe the analyzer here is correct. The code fix should be updated to account for the case where the original parameter list is:

```
..., params T[] values
```

and the new parameter list is:

```
..., T[] values, CancellationToken cancellationToken
```

**Comment by jmarolf** [comment] 2021-02-12 21:55
I see, we just want to make sure that the codefix does the right thing. I mis-read the issue

**Comment by Youssef1313** [comment] 2021-02-13 16:31
> I believe the analyzer here is correct. The code fix should be updated to account for the case where the original parameter list is:
> 
> ```
> ..., params T[] values
> ```
> 
> and the new parameter list is:
> 
> ```
> ..., T[] values, CancellationToken cancellationToken
> ```

While this is interesting case to test and make sure it's working, the case meant for EF Core is different.

The old signature is

```
..., params T[] values
```

and the new is:

```
..., CancellationToken cancellationToken, params T[] values
```

**Comment by arminatwork** [comment] 2021-04-22 13:06
> > I believe the analyzer here is correct. The code fix should be updated to account for the case where the original parameter list is:
> > ```
> > ..., params T[] values
> > ```
> > 
> > 
> > and the new parameter list is:
> > ```
> > ..., T[] values, CancellationToken cancellationToken
> > ```
> 
> While this is interesting case to test and make sure it's working, the case meant for EF Core is different.
> 
> The old signature is
> 
> ```
> ..., params T[] values
> ```
> 
> and the new is:
> 
> ```
> ..., CancellationToken cancellationToken, params T[] values
> ```

this not working

got me error say:
**AggregateException: One or more errors occurred. (The key value at position 0 of the call to 'DbSet<TEntity>.Find' was of type 'CancellationToken', which does not match the property type of 'int'.)**

**Comment by carlossanlop** [comment] 2021-04-22 20:13
I think the extra `params` keyword may be causing the problem. I thought the analyzer was smart enough to only fire when the `CancellationToken` instance was in the last position. Not sure why this is the case.

I'll take a look.

**Comment by arminatwork** [comment] 2021-04-22 21:04
@carlossanlop 
hi man

Well, it's going to make a mistake to me.
I put **CancellationToken** in the last parameter but he's going to miss it again.

so if have a params object, should **CancellationToken** put in the first parameter of method
it's going to make a error to me again

**Comment by carlossanlop** [comment] 2021-04-22 21:26
So looking into this more deeply, I don't think this is an issue with CA2016. This is an issue with allowing value types to get automatically [boxed](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing) because of the `params object[]` parameter.

I cannot seem to repro the case where you are getting an error. Can you please share a code snippet?

This code works fine and shows no errors:

```cs
using System;
using System.Threading;
using System.Threading.Tasks;

namespace N
{
    class C
    {
        static async Task MyAsync(string id, CancellationToken ct)
        {
            await MethodAsync(CancellationToken.None, id); // This is using the second overload correctly (which takes a ct as first parameter)
            await MethodAsync(id, CancellationToken.None); // This is not showing any errors because we are boxing the struct, causing the first overload to be used
            await MethodAsync(o: id, ct: ct); // This is using the second overload correctly (named parameters force using ct as the first parameter)
        }
        static Task<int> MethodAsync(params object[] o) { Console.WriteLine(o); return Task.FromResult(1); }
        static Task<int> MethodAsync(CancellationToken ct, params object[] o) { Console.WriteLine($"{ct} {o}"); return Task.FromResult(2); }
    }
}
```

**Comment by arminatwork** [comment] 2021-04-22 21:41
@carlossanlop Thanks for feedback

well I do passing 2 parameter to params object[] with CancellationToken
this code:
for example User.FindAsync(new object[] { userId, roleId}, cancellationToken);

got me error say : CancellationToken is not a parameter

**Comment by jmarolf** [comment] 2021-04-22 21:59
```csharp
User.FindAsync(new object[] { userId, roleId}, cancellationToken);
```

What is the definition of `FindAsync`? does it compile? [CS0231](https://docs.microsoft.com/dotnet/csharp/misc/cs0231) should be triggered for a method that has a params array anywhere but in the final position.

**Comment by arminatwork** [comment] 2021-04-22 22:10
@jmarolf 
well I said error in the last comment:\

in this issues is my problem [FindAsync rough edges when passing CancellationToken](https://github.com/dotnet/efcore/issues/22667)

**Comment by mavasani** [comment] 2021-04-29 16:42
@arminatwork @jmarolf Are we good to close this issue?

**Comment by arminatwork** [comment] 2021-04-29 16:47
> @arminatwork @jmarolf Are we good to close this issue?

Well no
I don't think the problem is solved!

**Comment by jmarolf** [comment] 2021-04-29 16:55
I'll update the bug with a description of the issue so its clear what the issue is.

**Comment by jmarolf** [comment] 2021-04-29 17:15
updated with a repo @arianmotamedi is my description of the problem correct?

**Comment by arianmotamedi** [comment] 2021-04-29 19:10
> updated with a repo @arianmotamedi is my description of the problem correct?

I think you tagged the wrong person :)

**Comment by jmarolf** [comment] 2021-04-29 20:45
:( woops @arminatwork is my description of the problem correct?

**Comment by arminatwork** [comment] 2021-04-29 20:57
> I'll update the bug with a description of the issue so its clear what the issue is.

Ok👍

**Comment by arminatwork** [comment] 2021-04-29 20:59
> updated with a repo @arianmotamedi is my description of the problem correct?

What do you mean?

**Comment by jmarolf** [comment] 2021-04-29 21:02
well I am updating a bug on others behalf I wanted to make sure the expected/actual was correct just to be safe.

**Comment by arminatwork** [comment] 2021-04-30 20:33
@jmarolf 
well
Has the problem been solved?

**Closed** 2021-08-02 23:09 UTC
Labels: Area-Microsoft.NetCore.Analyzers, Bug
