### ISSUE TITLE
False positive for CA1508

### ISSUE THREAD

**Issue by TaffarelJr** [dotnet/roslyn-analyzers#5128] opened 2021-05-24 16:03 UTC
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)
**Version**: [SDK 5.0.202](https://dotnet.microsoft.com/download/dotnet/5.0)

_AND_

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)
**Version**: 5.0.3 (Latest)

Replicated in both.

### Describe the bug

My GitHub repo was building fine a few months ago. I haven't pushed any changes to it; but recently something changed with the analyzer that triggers a false positive. My automated builds stopped working ([see here](https://github.com/TaffarelJr/onion-seed/actions)), and I get the same error when I build locally.

The project in GitHub is using the built-in analyzers.
Locally, I tried switching to the NuGet package - but I still get the same error.

### Steps To Reproduce

1. Clone https://github.com/TaffarelJr/onion-seed
2. Use the `codecov-action-1.5.0` branch (I've bypassed the error in `master`)
3. Open the `*.sln` file in the root of the project
4. Build

### Expected behavior

Successful build. It was working 3-4 months ago.

### Actual behavior

![image](https://user-images.githubusercontent.com/5290662/119374174-834daa00-bc76-11eb-9869-835d6b6143a2.png)

| Severity | Code | Description | Project | File | Line | Suppression | State |
|---|---|---|---|---|---|---|---|
| Error | CA1508 | 'min is IComparable comparableMin' is always 'true'. Remove or refactor the condition(s) to avoid dead code. | OnionSeed | .\onion-seed\src\OnionSeed\System\ComparableExtensions.cs | 88 | Active |

This is a fairly simple scenario: `min` is type `object`. It's perfectly reasonable to test if it's an `IComparable`, and if so then forward to a different overload of the method; otherwise throw an exception.

### Additional Context

I don't know if this is related to #4408.

**Comment by TaffarelJr** [comment] 2021-05-24 17:25
Oops - I just found #5011 and #5100, which also look to be the same issue.

**Comment by jmarolf** [comment] 2021-06-10 16:45
closing as duplicate of #5011

**Closed by jmarolf** 2021-06-10 16:45 UTC
