### ISSUE TITLE
CA1508 false positive on null-conditional

### ISSUE THREAD

**Issue by SebastianSchumann** [dotnet/roslyn-analyzers#3865] opened 2020-07-15 12:28 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 

#### Diagnostic ID

[CA1508](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1508)

#### Repro steps

    var foo = (Foo?)Parse() ?? default;

That's all the code that's needed. I tried this `Parse`-implementation and `Foo`-enum to reproduce the issue:

    public static object Parse() => null;

    public enum Foo
    {
        None
    }

Error Message: `Error CA1508: '(Foo?)Parse()' is never 'null'. Remove or refactor the condition(s) to avoid dead code.`
But it will be null...

#### Expected behavior

Do not report CA1508 on that case.

#### Actual behavior

CA1508 is reported.

**Comment by mavasani** [comment] 2020-11-07 00:47
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/4415, which should be fixed when https://github.com/dotnet/roslyn-analyzers/pull/4358 is merged.

**Closed by mavasani** 2020-11-07 00:47 UTC
