### ISSUE TITLE
CA1821: remove empty finalizers fires on non-empty finalizers

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn-analyzers#1176] opened 2017-04-28 20:42 UTC
Running this on Roslyn, it's flagging this as non-empty:

https://github.com/dotnet/roslyn/blob/dac379741525f359062f8d3133412deedc7e9c1e/src/Interactive/Features/Interactive/Core/InteractiveHost.cs#L227-L230

It's definitely not non-empty.

**Comment by jinujoseph** [comment] 2017-05-02 17:29
@333fred once this is fixed ...this needs to be reenabled [here](https://github.com/dotnet/roslyn/pull/19062/files)

**Comment by 333fred** [comment] 2017-05-12 23:31
I have been unable to repro this locally. I'm going to close this out and submit a PR to re-enable the rule, we'll reopen if we see any further issues.

**Comment by 333fred** [comment] 2017-05-17 18:09
The root cause of this is that when running in OOP or CLI contexts, the IOperation being passed is actually a `BoundSequencePointWithSpan`, which is a result of https://github.com/dotnet/roslyn/issues/17861. Changing c# to use highest breaks a bunch of other analyzers, so I'm going to convert this analyzer to a syntax analyzer for now.

**Comment by mavasani** [comment] 2017-05-25 23:22
Is this bug still open just to track converting it back to an operation analyzer?

**Comment by jinujoseph** [comment] 2017-05-25 23:49
I think we can close this ...opened another issue to track all the analyzers which will need to be converted to operation

**Closed by jinujoseph** 2017-05-25 23:49 UTC
