### ISSUE TITLE
CA1812 (Avoid uninstantiated internal classes) should be aware of indirect instantiation

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#1160] opened 2017-04-25 13:46 UTC
#### Analyzer package

Example: Microsoft.CodeQuality.Analyzers

#### Analyzer

CA1812: Avoid uninstantiated internal classes

#### Repro steps

1. Declare an internal type
1. Use Json.NET to directly or indirectly deserialize an instance of the type

#### Expected behavior

CA1812 is not reported.

#### Actual behavior

CA1812 is reported if the only instantiations of the type occur through Json.NET.

**Comment by 333fred** [comment] 2017-04-26 01:17
@sharwell I'm really not a fan of this, for a couple of reasons. First, we don't have a Json.NET dependency at the moment, and in order to determine if a Json.NET class is using a class, we'll have to take a dependency. Second, I'm _really_ against special casing only Json.NET. There are many other libraries out there that will instantiate classes without us being able to obviously detect it, such as the sqlite libraries, any ORM, DI frameworks, etc, too many for us to try and detect all of them. Giving one of them special treatment seems wrong to me, and when I write code that uses these libraries, I would honestly expect to see the false positive and explicitly need to disable the check. Tagging @dotnet/analyzer-ioperation for other opinions.

**Comment by heejaechang** [comment] 2017-04-26 01:30
agree on @333fred 

I don't believe that is author's job. user should either just suppress that rule or turn that rule off.

**Comment by sharwell** [comment] 2017-04-26 02:53
I changed this to a feature request. I am anticipating the community will end up requesting this type of functionality, with Json.NET being the most widely/heavily used instance of this. Maybe we don't have to do anything right now, but I foresee an eventual need to handle this situation in a flexible manner that adapts to common libraries over time if we want to make this a generally useful and accurate diagnostic.

**Comment by jinujoseph** [comment] 2017-04-26 03:06
I am going to close this out in favor of @333fred's assessment. We can reconsider this if we see a compiling reason from community.

**Comment by 333fred** [comment] 2017-04-26 03:16
@jinujoseph I'm going to reopen this so we have a place to talk about how we could approach this feature. I do think it's a good idea, we just make it generally applicable.

**Comment by heejaechang** [comment] 2017-04-26 03:25
more generic fix will be not reporting diagnostic if it is ever referenced anywhere then.

**Comment by sharwell** [comment] 2017-04-26 04:14
@heejaechang Having worked in two industries where indirect instantiation through a widely used library that isn't currently considered by this analyzer was a regular occurrence, I can confidently say that users will find the current approach "frustratingly limited". If this diagnostic is important enough to be valuable to users who don't use indirect instantiation, then it's also important enough to find a way to handle this case too.

**Comment by 333fred** [comment] 2017-04-26 17:28
One option here would be to create some kind of `IndirectInstantiation` attribute that library authors could apply to methods that indirectly instantiate type parameters. We'd want this to be fairly flexible, able to handle multiple type parameters, passing the `Type` as a regular parameter, etc. We'd probably want this attribute to exist in the BCL as well, so everyone doesn't have to take a dependency on an analyzer package. Does anyone know if we have an attribute like this already?

**Comment by nguerrera** [comment] 2017-04-26 17:42
This is the same problem that is faced by .NET Native's linker. Libraries can provide rd.xml files that indicate how composing with them impacts reachability. https://msdn.microsoft.com/en-us/library/dn600639(v=vs.110).aspx

It would be interesting if the analyzer could consume the same runtime directive data to help eliminate false positives.

**Comment by mavasani** [comment] 2017-04-26 17:52
Yes, that seems like another good approach. Additional files/options is generally a good approach for such configuration of the analyzers. One other common request is to allow the end user to customize the accessibility of symbols being analyzed by FxCop analyzers. We should probably design this in a generic fashion for all our analyzers - similar to StyleCop's json configuration file.

**Comment by heejaechang** [comment] 2017-04-26 18:29
hmmm.. if it is to give a way for author to remove diagnostic (or not report - whatever we call it, at the end, so that users don't get the diagnostic), what is the configure-ability buy users here?

do we expect users to change the configuration? if so, how about we just let users to use suppression?

I am saying this since ,if end result is same (diagnostic not shown to users), I would prefer things to stick to just one method (supression) rather than inventing several ways. since, if end result is same, I believe most people will just stick to one way.

if the configuration is just to give author a way to not report/remove diagnostics, I agree with @sharwell  that analyzer should just simply not report that diagnostic.

...

but my preference would be not even doing those and let users to suppress either the rule or the occurrences themselves. 

we provide easy way to suppress, if needed, we can provide bulk suppression, so I don't believe it is that much ask to users.

**Comment by 333fred** [comment] 2017-04-26 18:34
@heejaechang I think the idea here is to make this analyzer "just work", and not provide false positives to the user. While users can certainly suppress the rule (and likely will have to in some cases, since there will be scenarios where a user depends on an older version of a library that wouldn't have the proposed attribute/xml), anything we can do to make our analyzers less noisy will improve the experience and reduce the likelyhood it'll be ignored. The less the end users have to think about whether an analyzer is telling them the truth, the more they'll trust them.

**Comment by heejaechang** [comment] 2017-04-26 18:38
@333fred yep. I understand. 

what I am saying is
we either NOT do that (no builtin knowledge on specific libs) or do what Sam said (built in knowledge)

rather than inventing new thing to not show diagnostics to users.

**Comment by 333fred** [comment] 2017-04-26 18:43
My point, though, is that built-in knowledge is untenable. We can't possibly go through all the major libraries for things that indirectly instantiate parameters via reflection, that's way too fragile for us and would require a _lot_ of work. In order to do this feature correctly, we need to move the work of informing the compiler of indirect instantiation to library maintainers. I, for one, don't intend on watching Json.NET for every new function call and adding it to our whitelist as soon as a new version is published, much less every other serialization library, ORM, DI framework, etc.

**Comment by heejaechang** [comment] 2017-04-26 18:46
@333fred so we shift responsibility to the library author and it is okay for them to take the responsibility of maintaining those for all different rules?

**Comment by 333fred** [comment] 2017-04-26 20:12
I think so, yeah. I don't think there's any other viable option. We can write an analyzer to suggest that library authors do this to help people realize they should.

**Comment by cristianmad** [comment] 2017-05-02 13:37
Another use case would be the usage of Prism's PubSub events. We have a few applications with a relative large number of PubSub events and this rules triggers for each of them (even if they are actually being instantiated behind the scenes by the event aggregator). 

I agree with the rule, but it would be nice to have an elegant way of avoiding these false positives without actually disabling the rule in each file or per-project/solution.

Thanks

**Comment by mavasani** [comment] 2019-07-01 20:12
Duplicate of https://github.com/dotnet/roslyn/issues/30172

I believe the correct design here is to use the new [DiagnosticSuppressor API](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticSuppressor.cs#L8). Each framework that uses custom framework-specific means for instantiating types should author and ship suppressors with the package.

**Closed by mavasani** 2019-07-01 20:12 UTC
Labels: 0 - Backlog, Discussion, False_Positive, Feature Request
