### ISSUE TITLE
Incorrect CA1854 refactoring

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#6468] opened 2023-01-31 14:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-CA1854-refactoring/10264567)._

---
I use C# code (Net7/C#11) similar to this, implementing a counter using a dictionary:
        
```
var dic = new Dictionary();
foreach (var c in "mississippi")
    if (dic.ContainsKey(c))
        dic[c]++;
    else
        dic[c] = 1;
```
Visual Studio 2022 Professional (17.4.4) suggests a refactoring:
Message	CA1854	Prefer a 'TryGetValue' call over a Dictionary indexer access guarded by a 'ContainsKey' check to avoid double lookup

but refactored code has different behavior. Original code has a side effect on dic[c] using ++ operator, but in refactored code, operator ++ on int variable extracted using dic.TryGetValue has no effect (VS actually reports Message IDE0059 Unnecessary assignment of a value to 'value' after refactoring)

```
foreach (var c in "mississippi")
  if (dic.TryGetValue(c, out int value))
      value++;
  else
      dic[c] = 1;
```

Even if I'm supposed to pay attention to refactorings, actually in large projects, once I've checked that few refactorings of a given type are Ok, I tent to apply them globally afterwards...

On a side note, this refactoring has another problem: it always use a variable named 'value' regardless of the existence of a variable with the same name in a surrounding scope.

---
#### Feedback Bot on 31/1/2023, 08:29 AM: 

(private comment, text removed)
#### Feedback Bot on 31/1/2023, 08:05 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment] 2023-01-31 14:42
I believe we have tracking issues/PRs for both the issues mentioned here.

**Comment by Youssef1313** [comment] 2023-01-31 15:58
I'm going to close as a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/6390

This issue looks exactly the same.

**Closed by Youssef1313** 2023-01-31 15:58 UTC
