### ISSUE TITLE
FxCop rule CA1704: Identifiers should be spelled correctly

### ISSUE THREAD

**Issue by Jm-Fox** [dotnet/roslyn-analyzers#2000] opened 2019-01-11 21:14 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

Example: v2.6.2

#### Diagnostic ID

Example: [CA1704](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1704-identifiers-should-be-spelled-correctly?view=vs-2017)

#### Repro steps

1. Clone https://github.com/Jm-Fox/NetCoreCodeAnalysis
2. Open CodeAnalysis.sln (I used VS 2017.9)
3. In the solution explorer, right click on Solution 'CodeAnalysis' (2 projects) and select Analyze > Run Code Analysis on Solution

#### Expected behavior

A CA1704 issue is expected on the type CodeAnalysis.Ca1722Exception in the NetCore project.

#### Actual behavior

No CA1704 issue is found on the NetCore project.

#### Priority
This is moderately important to me and my employer. Having identifiers spelled correctly is important to writing readable and maintainable code.

See also #1948

**Comment by mavasani** [comment] 2019-02-23 18:54
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/443

**Closed by mavasani** 2019-02-23 18:54 UTC
