### ISSUE TITLE
Is CA2009 (Do not call ToImmutableCollection) a reliability rule?

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#4330] opened 2020-10-14 08:55 UTC
Looking at the [Reliability rules documentation](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/reliability-warnings) we can see that it states:

> Reliability rules support library and application reliability, such as correct memory and thread usage. 

But `CA2009` looks more like a [Usage rule](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/usage-warnings) to me.

**Comment by sharwell** [comment] 2020-10-19 22:27
I believe it's a performance rule

**Comment by carlossanlop** [comment] 2020-10-23 20:52
@mavasani @sharwell is it a breaking change to move a rule to a different category?

**Comment by mavasani** [comment] 2020-10-23 21:01
It has bunch of additional things to consider:

1. We have sequential ID ranges allocated to each category, and changing category for an existing rule ID would mean adding holes in the range: https://github.com/dotnet/roslyn-analyzers/blob/41b4ee4eda3d416a9531081885d6c75840609533/src/Utilities/Compiler/DiagnosticCategoryAndIdRanges.txt#L5-L22
2. You will need to edit the rule doc page and also move around the rule ID entry in bunch of indices in CA rules documentation: https://docs.microsoft.com/contribute/dotnet/dotnet-contribute-code-analysis#contribute-docs-for-caxxxx-rules
3. This can theoretically be a minor breaking change if users used category based diagnostic configuration entries in their editorconfig: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-options#scope. However, it is unlikely that someone would be broken by this and see this as an issue. 

In general, I prefer to not change category unless we see a good reason, but seems fine to do if we are ready to do the above work.

**Comment by mavasani** [comment] 2021-02-02 17:56
Closing this as by design, do not seem we have a good reason for taking a breaking change here.

**Closed by mavasani** 2021-02-02 17:56 UTC
Labels: Area-Microsoft.NetCore.Analyzers
