### ISSUE TITLE
Microsoft.CodeQuality.VisualBasic.Analyzers crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#6846] opened 2023-08-09 18:45 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftCodeQualityVisualBasicAnalyz/10433809)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:Version 17.8.0 Preview 6.0]
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: CareLink
ISymbol: TimeZoneExtensions (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer.HasEqualityOperator(INamedTypeSymbol type)
   at Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer._Closure$__._Lambda$__7-0(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----

Suppress the following diagnostics to disable this analyzer: CA2224	CareLink	C:\Users\PaulM\Source\Repos\CareLink\src\CareLink\CareLink.vbproj	1	Active
```

---
#### Feedback Bot on 8/9/2023, 04:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment] 2023-08-13 09:59
This was fixed in https://github.com/dotnet/roslyn-analyzers/pull/6782

**Comment by Youssef1313** [comment] 2023-08-13 10:00
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/6778

**Closed by Youssef1313** 2023-08-13 09:59 UTC
