### ISSUE TITLE
CA1200 is not suppressed by category

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#5852] opened 2022-02-07 07:33 UTC
er the documentation, this scenario is supposed to work as far as I understand:

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#scope

> When you configure the severity level for multiple rules with a single entry, either for a *category* of rules or for *all* rules, the severity only applies to rules that are [enabled by default](https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md). To enable rules that are disabled by default, you must either:
>
> - Add an explicit `dotnet_diagnostic.<rule ID>.severity = <severity>` configuration entry for each rule.
> - In .NET 6+, enable a category of rules by setting [\<AnalysisMode\<Category>>](../../core/project-sdk/msbuild-props.md#analysismodecategory) to `All`.
> - Enable *all* rules by setting [\<AnalysisMode>](../../core/project-sdk/msbuild-props.md#analysismode) to `All` or by setting [\<AnalysisLevel>](../../core/project-sdk/msbuild-props.md#analysislevel) to `latest-All`.

The documentation rule we have is CA1200 and it's enabled by default:

https://github.com/dotnet/roslyn-analyzers/blob/60eb13c44c366205e5a4dec195404477009c41de/src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif#L60

Repro:

https://github.com/Youssef1313/category-suppression

**Comment by mavasani** [comment] 2022-02-07 10:31
@Youssef1313 This is a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5077#issuecomment-829898574. Unfortunately, not much we can do here - `AnalysisMode`/`AnalysisLevel` and category based editorconfig severity configuration do not work together nicely. A better approach would be to not use category based editorconfig configuration, but instead use `AnalysisMode<%Category%>`: https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#analysismodecategory. Can you see if that workaround resolves this issue?

**Comment by Youssef1313** [comment] 2022-02-07 10:48
@mavasani Thanks. Can the docs be updated to reflect this?

cc @gewarren

**Comment by gewarren** [comment] 2022-02-07 23:44
I am seeing another issue related to categories. The defaults for the Globalization rules are:

![image](https://user-images.githubusercontent.com/24882762/152890471-08a3963b-c46c-423d-9d60-fbaa99e6595f.png)

If you set the Globalization category severity to error in .editorconfig (`dotnet_analyzer_diagnostic.category-Globalization.severity = error`), not all of the rules are affected. In fact, the 3 rules that aren't affected are the 3 that are warnings by default:

![image](https://user-images.githubusercontent.com/24882762/152890690-5ac60847-8554-4469-adec-fcfb5941460d.png)

This is without setting any AnalysisMode, AnalysisLevel, or AnalysisModeGlobalization properties in a `net6.0` project. So the category-based control seems completely broken!

**Comment by mavasani** [comment] 2022-02-08 06:21
@gewarren It seems the default severities for all the rules (your first screenshot) seem to be wrong. The correct defaults are in: https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md  

![image](https://user-images.githubusercontent.com/10605811/152929593-450df57f-0ddb-4d5f-b5be-b16f6395deab.png)

Based on these defaults, the set of unaffected rules after setting `dotnet_analyzer_diagnostic.category-Globalization.severity = error` are all the ones that are disabled by default, which is indeed by design (see the `Important` note here: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-options#scope)

**Comment by mavasani** [comment] 2022-02-08 06:23
@gewarren Are you able to create a repro for the issue in your first screenshot (wrong default severities) and file a bug in Roslyn repo? You want to tag @jmarolf as this seems to be an issue with editorconfig UX.

**Comment by Youssef1313** [comment] 2022-02-08 06:25
@mavasani I believe I have an open issue for EditorConfig UI already

**Comment by Youssef1313** [comment] 2022-02-08 06:31
https://github.com/dotnet/roslyn/issues/54495 It was claimed to be fixed, but I'm not sure it's indeed fixed. @jmarolf can you take a look and re-open https://github.com/dotnet/roslyn/issues/54495 if necessary?

**Comment by gewarren** [comment] 2022-02-08 16:51
> @gewarren Are you able to create a repro for the issue in your first screenshot (wrong default severities) and file a bug in Roslyn repo? You want to tag @jmarolf as this seems to be an issue with editorconfig UX.

I logged https://github.com/dotnet/roslyn/issues/59371.

**Closed** 2022-12-10 16:56 UTC
Labels: Resolution-By Design
