### ISSUE TITLE
Microsoft.CodeQuality.Analyzers crashed with InvalidOperationException

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#1704] opened 2018-05-26 06:42 UTC
#### Analyzer package

Example: Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

DisposableFieldsShouldBeDisposed

#### Repro steps

I don't have a repro:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Usage.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'.	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests		1	Active	Analyzer 'Microsoft.CodeQuality.Analyzers.Exp.Usage.DisposableFieldsShouldBeDisposed' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests
ISymbol: SetValue_ThrowsKeyNotFoundException (Method)

System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.GetCachedAbstractValue(IOperation operation)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitInstanceReference(IInstanceReferenceOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.InstanceReferenceExpression.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitInvalid(IInvalidOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseInvalidOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitAssignmentOperation(IAssignmentOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitSimpleAssignment(ISimpleAssignmentOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseSimpleAssignmentExpression.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitObjectOrCollectionInitializer(IObjectOrCollectionInitializerOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.VisitObjectOrCollectionInitializer(IObjectOrCollectionInitializerOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseObjectOrCollectionInitializerExpression.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitInvalid(IInvalidOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseInvalidOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitInvalid(IInvalidOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseInvalidOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitSymbolInitializer(ISymbolInitializerOperation operation, ISymbol initializedSymbol, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitVariableInitializer(IVariableInitializerOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseVariableInitializer.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitVariableDeclarator(IVariableDeclaratorOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.BaseVariableDeclarator.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitVariableDeclaration(IVariableDeclarationOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseVariableDeclaration.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitArray(IEnumerable`1 operations, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.DefaultVisit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.OperationVisitor`2.VisitVariableDeclarationGroup(IVariableDeclarationGroupOperation operation, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.BaseVariableDeclarationGroupOperation.Accept[TArgument,TResult](OperationVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.VisitCore(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Visit(IOperation operation, Object argument)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowOperationVisitor`2.Flow(IOperation statement, BasicBlock block, TAnalysisData input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.PointsToDataFlowOperationVisitor.Flow(IOperation statement, BasicBlock block, IDictionary`2 input)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Flow(BasicBlock block, TAnalysisData data)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.Run(ControlFlowGraph cfg)
   at Microsoft.CodeAnalysis.Operations.DataFlow.DataFlowAnalysis`3.GetOrComputeResultCore(ControlFlowGraph cfg)
   at Microsoft.CodeAnalysis.Operations.DataFlow.PointsToAnalysis.PointsToAnalysis.GetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, DataFlowAnalysisResult`2 nullAnalysisResultOpt, Boolean pessimisticAnalysis)
   at Microsoft.CodeQuality.Analyzers.Exp.DisposeAnalysisHelper.TryGetOrComputeResult(ImmutableArray`1 operationBlocks, IMethodSymbol containingMethod, Boolean trackInstanceFields, ControlFlowGraph& cfg, DataFlowAnalysisResult`2& disposeAnalysisResult, DataFlowAnalysisResult`2& pointsToAnalysisResult, ImmutableDictionary`2& trackedInstanceFieldPointsToMap)
   at Microsoft.CodeQuality.Analyzers.Exp.Usage.DisposableFieldsShouldBeDisposed.<>c__DisplayClass7_0.<Initialize>b__3(OperationBlockStartAnalysisContext operationBlockStartContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__47`6.<ExecuteBlockActionsCore>b__47_2(ValueTuple`5 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

**Comment by 333fred** [comment] 2018-05-26 17:48
@mavasani, looks like this is occurring during points to analysis on the managed unit tests?

**Comment by mavasani** [comment] 2018-05-27 01:09
Yes, I will investigate.

**Comment by mavasani** [comment] 2018-08-07 15:20
Dupe of https://github.com/dotnet/roslyn-analyzers/issues/1735

**Closed by mavasani** 2018-08-07 15:20 UTC
