### ISSUE TITLE
CA2000 False Positive on IDisposable return

### ISSUE THREAD

**Issue by jvilimek** [dotnet/roslyn-analyzers#2392] opened 2019-04-26 16:08 UTC
#### Analyzer package

Used nuget package: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.2

#### Diagnostic ID

Example: [CA2000](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope)

#### Repro steps

1. Open attached [ConsoleAppTestCa2000.zip](https://github.com/dotnet/roslyn-analyzers/files/3122098/ConsoleAppTestCa2000.zip) project
2. Hit build
3. Error occurs (based on Microsoft.NetCore.Analyzers analyzer)

#### Expected behavior
No error as the object is disposed in the main method + the rule CA2000 is defined under Microsoft.Analyzers.ManagedCodeAnalysis and not Microsoft.NetCore.Analyzers analyzer
#### Actual behavior
Throws an warning/error on line 23 in program.cs

#### Suspicious behavior

There is Microsoft.NetCore.Analyzers rule applied in this full .NET 4.7.1 project. Note, that the rule CA2000 is under "Microsoft.Analyzers.ManagedCodeAnalysis" analyzers section.

**Comment by mavasani** [comment] 2019-04-26 20:41
Likely a dupe of https://github.com/dotnet/roslyn-analyzers/issues/2361. Can you please check if the issue repros with our latest package: https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.3-beta1.19226.1+513b9bc4

**Comment by jvilimek** [comment] 2019-04-29 07:24
Hi there and thanks for response. With the 2.9.3-beta1-19226 version it is OK. Any idea, when 2.9.3 will be out for public nuget? Or should we use this pre-release version?

**Comment by mavasani** [comment] 2019-05-03 14:31
@jvilimek Hoping to release it very soon. Just waiting to push some more bug fixes...

**Closed** 2019-05-03 14:31 UTC
Labels: Area-Microsoft.NetCore.Analyzers, Bug, Resolution-Duplicate
