### ISSUE TITLE
Microsoft Code Analysis 2019 Extension does no work with Visual Studio 2019, 16.4.2

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/roslyn-analyzers#3132] opened 2019-12-24 08:13 UTC
I have installed the latest version of **Microsoft Code Analysis 2019** extension in **visual studio 2019 version 16.4.2** but it does not work while nuget package is working fine.

Thank you.

**Comment by mavasani** [comment] 2020-05-05 20:19
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/3314 - we are soon going to deprecate this extension.

**Closed by mavasani** 2020-05-05 20:19 UTC
