### ISSUE TITLE
Exclude Unit Test method from CA1707

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3705] opened 2020-06-02 17:03 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

[CA1707](https://docs.microsoft.com/visualstudio/code-quality/ca1707)

Unit Test methods should be okay if their names contains underscores.
This convention is widely used and it should be okay if the analyzer excludes any method that is annotated by any of the following attributes:

- `[Fact]` or `[Theory]` => (xunit)
- `[Test]` => (nunit)
- `[TestMethod]` => (mstest)

If this is approved, I'll start working on it (shouldn't be hard 😄).

**Comment by mavasani** [comment] 2020-06-02 17:07
This is duplicate of https://github.com/dotnet/roslyn-analyzers/issues/1354, which was resolved as by-design.

**Closed** 2020-06-02 17:19 UTC
