### ISSUE TITLE
AvoidDeadConditionalCode slows down build

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#4960] opened 2021-03-19 14:42 UTC
![image](https://user-images.githubusercontent.com/1640096/111797568-92f0f100-88c9-11eb-8f67-81c6120caa87.png)

Small project.

Repro: https://github.com/DotNetAnalyzers/WpfAnalyzers/tree/768fea89c90b27fd052d778f065852f49275bc70

**Comment by Youssef1313** [comment] 2021-03-19 16:41
Related: https://github.com/dotnet/roslyn-analyzers/issues/4914

**Comment by Youssef1313** [comment] 2022-12-12 19:52
Duplicate of #4914

**Closed by Youssef1313** 2022-12-12 19:52 UTC
Labels: Bug, Area-Microsoft.CodeQuality.Analyzers
