### ISSUE TITLE
[Analyzer Suggestion - Performance] Avoid Enum.Parse if possible

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3717] opened 2020-06-08 15:34 UTC
Enum.Parse uses reflection, so it's slow and can noticeable affect performance.

A scenario that I came across personally was in a Chess class library.

**A little background about the game**

A chess board has 8 columns (named files and are letters from 'A' to 'H'), and 8 rows (named ranks and are numbers from 1 to 8). So, here are the names for each square:

![image](https://user-images.githubusercontent.com/31348972/84048941-395bad80-a9ac-11ea-95e5-da0ba149f7e4.png)

I represented the files by an enum:

```
enum File
{
A, B, C, D, E, F, G, H
}
```

I had a method that parses the file by taking a character as argument and does the following:

```csharp
private static File ParseFile(char file)
{
    file = char.ToUpper(file);
    if (file < 'A' || file > 'H')
    {
        throw new ArgumentOutOfRangeException(nameof(file));
    }
    Enum.TryParse(file.ToString(), out File tempFile);
    return tempFile;
}
```

That was making the game really **noticeably** slow when I tried it as an **end-user**.

In my specific case, the fix is straight-forward :`return (File)(file - 'A');` (Certainly, a CodeFixProvider won't be able to offer such a solution)

1. An analyzer to point out the developers to consider an alternative solution would be helpful IMO.
2. As for the codefix, things might get tricky, I'm not sure if it's worth having a codefix. But, if a codefix will be added it can do a chain of if-else if-else if-etc..

However, doing so will violate the OCP. If a new item is added to the enum, a developer needs to add it to the if chain. A workaround on that is to add the Enum.Parse call in the last else clause. That way, it combines both benefits, performance in most of the cases, and keeping the OCP. Or simply, offer the analyzer as a suggestion without a codefix, and let that up to the developer to think about.

**Comment by svick** [comment] 2020-06-10 10:55
Looking at [the current implementation](https://source.dot.net/#System.Private.CoreLib/Enum.cs,7ef4c46032079d2b), as far as I can tell, it doesn't use any expensive reflection (after some one-time initialization) and all the code seems quite optimized. And a quick microbenchmark shows that `Enum.TryParse` on .Net 5 (preview) executes in ~140 ns and allocates no heap memory (in comparison with .Net Framework 4.8, where it takes ~370 ns and allocates 112 B).

I don't think those are characteristics of a method that should be generally discouraged, especially not if the suggested alternative is as unappealing as a chain of if-else if.

**Comment by mavasani** [comment] 2020-06-10 11:09
@stephentoub @bartonjs to comment. If valid, this issue should be transferred to dotnet/runtime repo.

**Comment by stephentoub** [comment] 2020-06-10 11:16
I don't think this iis worth pursuing.

**Comment by mavasani** [comment] 2020-06-10 11:44
Thanks @stephentoub! @Youssef1313 I am closing the issue as by design

**Closed by mavasani** 2020-06-10 11:44 UTC
Labels: Resolution-By Design
