### ISSUE TITLE
CA1829:Use Length/Count property instead of Count() when available false positive

### ISSUE THREAD

**Issue by stap123** [dotnet/roslyn-analyzers#5449] opened 2021-09-05 13:14 UTC
**Diagnostic ID**: [CA1829](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1829)

This rule shows as a warning when `Count()` is used inside an EF Core queries `.Select` block. But if you apply the fix and use the `Count` property the query then breaks.

Is there some way to stop this happening because currently this rule suggesting that I break my app?

**Comment by mavasani** [comment] 2021-09-13 15:29
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5299

**Closed by mavasani** 2021-09-13 15:29 UTC
