### ISSUE TITLE
Port FxCop rule CA2151: FieldsWithCriticalTypesShouldBeCriticalFxCopRule

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#527] opened 2015-11-21 21:39 UTC
**Title:** #N/A

**Description:**

#N/A

**Proposed analyzer:** System.Runtime

**Notes:**

**Comment by srivatsn** [comment] 2015-12-02 08:41
Dupe of #630

**Closed by srivatsn** 2015-12-02 08:41 UTC
Labels: FxCop Port, Needs Review
