### ISSUE TITLE
Public API checker seems to ignore readonly properties in VB

### ISSUE THREAD

**Issue by amcasey** [dotnet/roslyn-analyzers#821] opened 2016-01-27 18:48 UTC
I added a new public readonly property to the public type `VisualBasicScript`:

```
Public Shared ReadOnly Property DefaultFormatter As ObjectFormatter = New VisualBasicObjectFormatter()
```
1. The analyzer doesn't prompt me to add an entry to the public API file.
2. If I add it myself, I get an error:

```
1>vbc : error RS0017: Symbol 'Shared Microsoft.CodeAnalysis.VisualBasic.Scripting.VisualBasicScript.DefaultFormatter.get -> Microsoft.CodeAnalysis.Scripting.Hosting.ObjectFormatter' is part of the declared API, but is either not public or could not be found
```

**Comment by amcasey** [comment] 2016-01-27 18:48
FYI @mavasani

**Comment by mavasani** [comment] 2016-05-11 22:28
This seems to be due to the fact that VB compiler marks the accessors of readonly/writeonly properties with no body as ImplicitlyDeclared symbols, unlike the C# compiler which marks the getter for ArrowExpression property as not implicitly declared. Analyzer driver skips callbacks for all implicitly declared symbols, and the analyzer never gets a callback for these accessors.

I'll file a bug on compiler layer and add skipped unit test for DeclarePublicApiAnalyzer.

**Comment by mavasani** [comment] 2016-10-04 23:49
Compiler bug was resolved by design - we need to fix the analyzer.

**Closed** 2019-04-24 00:15 UTC
Labels: 4 - In Review, Area-Roslyn.Diagnostics.Analyzers, Bug
