### ISSUE TITLE
CA1720 should not warn here

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#2731] opened 2019-07-31 09:25 UTC
```cs
public static void M(int obj) { }
```

**Comment by GammaFour** [comment] 2019-08-13 00:17
Yeah, I have an issue with this also.  This line throws a warning:

```
        public async Task<IActionResult> PostStampedProposedOrder([FromBody] object @object)
        {

```
If I've gone to the trouble of prefacing the variable name with an @, it means I understand the rule and have explicitly overrriden it.  This error should be suppressed for names beginning with @.

**Comment by mavasani** [comment] 2019-08-22 22:43
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/1823

**Closed by mavasani** 2019-08-22 22:43 UTC
