### ISSUE TITLE
Analyzers can't be created because assembly Microsoft.CodeAnalysis.Analyzers is not found

### ISSUE THREAD

**Issue by cremor** [dotnet/roslyn-analyzers#2340] opened 2019-04-15 11:06 UTC
#### Analyzer package
[Microsoft.CodeAnalysis.Analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers)

#### Package Version
1.1.0 and 2.10.0 (which doesn't exist yet). See below for explanation of why those two versions are affected.

#### Diagnostic ID
CS8032	An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticDescriptorCreationAnalyzer cannot be created from C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.codeanalysis.analyzers\1.1.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll: Die Datei oder Assembly "Microsoft.CodeAnalysis.Analyzers, Version=**1.1.0.0**, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.

Sometimes this `CSharpDiagnosticDescriptorCreationAnalyzer` also searches for version 2.10.0.0 instead of 1.1.0.0. I'm unsure when this happens.

CS8032	An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerFieldsAnalyzer cannot be created from C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.codeanalysis.analyzers\1.1.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll: Die Datei oder Assembly "Microsoft.CodeAnalysis.Analyzers, Version=**2.10.0.0**, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.

The CS8032 that complains about a missing version 2.10.0.0 is also thrown for `CSharpFixerWithFixAllAnalyzer`, `CSharpRegisterActionAnalyzer` and `CSharpReportDiagnosticAnalyzer`.

The error message would be "Could not load file or assembly..." in english.

In addition to those 5 CS8032 errors I also get 3 AD0001 `TypeInitializationException` errors:

AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpImmutableObjectMethodAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpImmutableObjectMethodAnalyzer' threw an exception.'

They have the same root cause (can't load assemblies).

#### Repro steps
1. Create a new ASP.NET Core 2.2 Web API project.
2. Run it.
3. Close Visual Studio and reopen it.
4. Repeat step 3 until the error list shows warnings (for me it just happend on the second try on a new project, but it might need more tries).

#### Expected behavior
No errors/warnings should be shown.

#### Actual behavior
The error list shows warnings (see "Diagnostic ID" section).

#### Additional information
I know that 1.1.0 is an extremely old version, but I neither installed it myself nor am I referencing it in my project file. The usage must be implicit from the .NET Core SDK. But since I'm targeting .NET Core 2.2 this also doesn't explain the very old version. My `NuGetFallbackFolder` also doesn't contain any other version of `Microsoft.CodeAnalysis.Analyzers`.

I have no idea why it searches for version 2.10.0.0 since the newest version on NuGet right now is  2.9.1.

I'm using Visual Studio 2017 version 15.9.11.

Output of `dotnet --info`:
<details>
  <summary>Click to expand</summary>
.NET Core SDK (gemäß "global.json"):
 Version:   2.2.106
 Commit:    aa79b139a8

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.106\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by mavasani** [comment] 2019-04-15 13:09
@cremor .NETCore SDK does not add references to any analyzer packages. You are likely referencing this analyzer package either transitively (for e.g. if you are referencing Microsoft.CodeAnalysis NuGet package, it pulls in this analyzer package as a references OR if your project is referencing another project that has a reference to this analyzer package, and does not set PrivateAssets, then analyzer references flow transitively). I would recommend resolving this issue by adding a direct reference to Microsoft.CodeAnalysis.Analyzers version 2.9.x to your project OR tracking down which package is transitively pulling in this analyzer package and preventing that.

**Comment by cremor** [comment] 2019-04-17 08:16
> .NETCore SDK does not add references to any analyzer packages.

If that's the case, why does Visual Studio show analyzer dependencies right after creating a new ASP.NET Core 2.2 Web API project?

![grafik](https://user-images.githubusercontent.com/116314/56270568-ba941900-60f6-11e9-9c34-f8ea73744458.png)

Also, I could just reproduce the analyzer error messages from this empty Web API project and have updated the repro steps above accordingly. So this is definetely not coming from some other package or project reference.

**Comment by mavasani** [comment] 2019-04-17 21:56
@cremor Ah, that is good to know - I wasn't aware that `Microsoft.NET.Sdk.Web` shipped analyzers. I think the assembly load issue that you are seeing is a duplicate of https://github.com/dotnet/roslyn/issues/32226, which was fixed in VS2019 RTW. Would you be able to check if the issue still repros for you on VS2019?

**Comment by cremor** [comment] 2019-04-18 05:41
I don't have VS2019 installed right now. Might be a few weeks until I install it and can test.

But even if this is fixed in VS2019, does this mean that there is no plan to fix this in VS2017?

**Comment by mavasani** [comment] 2019-06-18 05:59
@cremor Yes, it is unlikely to be backported unless it is a critical crash/perf issue. Closing the issue here. Please open an issue on Roslyn repo if it still reproduces on VS2019 for you

**Closed by mavasani** 2019-06-18 05:59 UTC
Labels: Area-Microsoft.CodeAnalysis.Analyzers, Questions, Resolution-Duplicate, Resolution-External
