### ISSUE TITLE
Do not issue CA1835 when overriding Stream methods

### ISSUE THREAD

**Issue by NN---** [dotnet/roslyn-analyzers#4345] opened 2020-10-20 10:14 UTC
### Analyzer

**Diagnostic ID**: [CA1835](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1835)

### Describe the improvement

The diagnostic warning CA1835 appears when you implement your own Stream.

```cs
class MyStream : Stream
{
  // CA1835 
  public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
  {
    ...
  }

  // CA1835 
  public override async Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
  {
    ... 
  }
}
```

**Comment by carlossanlop** [comment] 2020-10-21 21:58
THanks for opening an issue, @NN--- . Do you mean it shows up above a method signature instead of an invocation?

**Comment by NN---** [comment] 2020-10-22 04:53
Yes.

**Comment by Evangelink** [comment] 2020-12-21 16:47
@NN--- Could you please try again with the latest version of the analyzers? I cannot reproduce using your example on `master` not on the released analyzers. Maybe there is an extra call or something you trimmed from your example.

**Comment by NN---** [comment] 2020-12-21 17:12
Is the latest published with .NET 5 ?

**Comment by NN---** [comment] 2020-12-21 18:35
Trying with .NET 5.

I have a stream wrapper and have a warning on invocation.
Can this be recognized as a special case ?

```
abstract class AStream : Stream
    {
        private Stream _stream;

        protected AStream(Stream stream) => _stream = stream;

        public override async Task<int> ReadAsync(
            byte[] buffer,
            int offset,
            int count,
            CancellationToken cancellationToken) =>
			//	Warning	CA1835	Change the 'ReadAsync' method call to use the 'Stream.ReadAsync(Memory<byte>, CancellationToken)' overload
            await _stream.ReadAsync(buffer, offset, count, cancellationToken).ConfigureAwait(false);
    }
```

**Comment by Evangelink** [comment] 2020-12-22 17:05
Thanks for the test and the new code snippet. The warning is not raised on the `ReadAsync` override but on the call (last line of code). I don't see any problem with that, could you please explain why do you think there is a problem? You could replace `buffer, offset, count` with `buffer.AsMemory(offset, count)`.

@carlossanlop Could you confirm that I am not saying something stupid here?

**Comment by NN---** [comment] 2020-12-22 17:08
My intent is to make a Stream wrapper, therefore I want to forward to the exact method signature.

**Comment by Evangelink** [comment] 2020-12-22 17:10
I would suggest to suppress the issue in this case then. But I will let @carlossanlop decide.

**Comment by carlossanlop** [comment] 2021-01-04 18:21
@NN--- since your intention is to explicitly call the wrapped method with the same signature, the best approach is to suppress the message, as @Evangelink suggested, because the analyzer does not know that you actually want to call the obsolete `ReadAsync/WriteAsync` methods.
Let us know if you have any more questions. I'm closing this since it's a Won't Fix.

**Closed by carlossanlop** 2021-01-04 18:21 UTC
Labels: Area-Microsoft.NetCore.Analyzers, Need More Info
