### ISSUE TITLE
Metrics.exe gives different results for lines of code

### ISSUE THREAD

**Issue by ltsstar** [dotnet/roslyn-analyzers#2017] opened 2019-01-17 14:40 UTC
#### Analyzer package

https://github.com/dotnet/roslyn-analyzers/tree/master/src/Tools

#### Package Version

Built from source from this repo

#### Expected behavior

Return (arguably) 2 or 4 lines of code

#### Actual behavior

Metrics.exe returns 16 lines of code.

![image](https://user-images.githubusercontent.com/1613646/51325814-13a7ce80-1a6e-11e9-8501-db388cb9af38.png)

**Comment by mavasani** [comment] 2019-01-17 14:45
Lines of code metric is now (i.e. in Metrics.exe and Dev16 onwards) directly derived from number of source code lines for that method, including doc comments. If you intend to get the _effective lines_, which is number of IL instructions of IOperations in source, you need to use the legacy mode for building Metrics.exe: https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017#legacy-mode

**Comment by mavasani** [comment] 2019-01-17 14:47
Closing by design as discussed with @ltsstar offline. The above Code metrics window screenshot is from Dev15, which uses IL based code metrics computation.

**Closed by mavasani** 2019-01-17 14:47 UTC

**Comment by mavasani** [comment] 2019-09-23 18:10
Update: https://github.com/MicrosoftDocs/visualstudio-docs/issues/3979
