### ISSUE TITLE
CSC : error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.AssigningSymbolAndItsMemberInSameStatement' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#2906] opened 2019-10-03 20:49 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.5 (Latest)

#### Diagnostic ID

N/A.

I ma getting the following error when running build in Visual studio:

`CSC : error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.AssigningSymbolAndItsMemberInSameStatement' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
`

Building the same project from the command line works just fine.

**Comment by mavasani** [comment] 2019-10-03 20:50
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2889. Can you try with the myget package mentioned in that issue?

**Closed by mavasani** 2019-10-03 20:50 UTC
