### ISSUE TITLE
Analyzer warnings and errors are not displayed for non-clean builds

### ISSUE THREAD

**Issue by craigktreasure** [dotnet/roslyn-analyzers#5045] opened 2021-04-20 19:14 UTC
### Analyzer

**Diagnostic ID**: [CA2013](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2013): `Do not use ReferenceEquals with value types`

### Analyzer source

I'm seeing the same behavior in both the SDK and the NuGet package.

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.202](https://dotnet.microsoft.com/download/dotnet/5.0)

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.3

### Describe the bug

I have created a min-repro at [craigktreasure/dotnet-analyzers-repro](https://github.com/craigktreasure/dotnet-analyzers-repro#repeatbuildomitswarnings) in the `RepeatBuildOmitsWarnings` project.

### Steps To Reproduce

1. `git clone https://github.com/craigktreasure/dotnet-analyzers-repro.git`
2. `cd dotnet-analyzers-repro/RepeatBuildOmitsWarnings`
3. `dotnet build`
4. `dotnet build`
5. `dotnet clean`
6. `dotnet build`

### Expected behavior

Warnings and errors should be shows on each build.

### Actual behavior

Warnings and errors are only shows on the first clean build.

## Additional context

Having the warnings or errors disappear on a subsequent build makes it difficult to reliably enforce policies and has led to confusion for myself and others. I'd really prefer it were consistent.

**Comment by jmarolf** [comment] 2021-04-20 20:58
duplicate of https://github.com/dotnet/msbuild/issues/3046

**Closed by jmarolf** 2021-04-20 20:58 UTC
