### ISSUE TITLE
'An item with the same key has already been added' when generating metrics in command line

### ISSUE THREAD

**Issue by fforjan** [dotnet/roslyn-analyzers#2272] opened 2019-04-02 23:37 UTC
#### Analyzer package

Example: [Microsoft.CodeAnalysis.Metrics](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Metrics/)

#### Package Version

Example: v2.9.1

#### Repro steps

1. Run the program in command line :
"C:\Users\ISYS36005\TFSWorkspaces\Dev\Source\packages\SchneiderElectric.Software.CodeMetrics.2.0.0\Metrics\metrics.exe" /project:"C:\Users\ISYS36005\TFSWorkspaces\Dev\Source\Ourproject\OurProject.csproj" /OUT:"C:\Users\ISYS36005\TFSWorkspaces\Dev\Source\Ourproject\bin\Debug\\SimCentral.Client.Shared.dll.CodeMetrics.xml"

#### Expected behavior
it should generate the code metrics and if failing, give more details about what is wrong !
#### Actual behavior
Loading OurProject.csproj...
Computing code metrics for OurProject.csproj...
An item with the same key has already been added.

**Comment by fforjan** [comment] 2019-04-02 23:54
I tried with  legacy version, 2.9.0 and 2.6.1 beta and same result

**Comment by fforjan** [comment] 2019-04-03 03:48
I have isolated the issue.
It seems we had a merge issue at one stage when a project reference was duplicated.
Note that Visual Studio do not complain about this, where as I think it should ??

You can reproduce the issue by looking at the attached solution.

Note that I had to add a post-build step as msbuild /t:Metrics doesn't work
[IssueGithub.zip](https://github.com/dotnet/roslyn-analyzers/files/3036792/IssueGithub.zip)

**Comment by fforjan** [comment] 2019-04-03 03:52
I have isolated the issue.
It seems we had a merge issue at one stage when a project reference was duplicated:
![image](https://user-images.githubusercontent.com/601810/55451764-3df72b80-5589-11e9-8cec-b7e159d34a7c.png)

Note that Visual Studio do not complain about this, where as I think it should ??

You can reproduce the issue by looking at the attached solution.
[IssueGithub.zip](https://github.com/dotnet/roslyn-analyzers/files/3036799/IssueGithub.zip)

Note that I had to add a post-build step as msbuild /t:Metrics doesn't work

**Comment by mavasani** [comment] 2019-04-15 13:59
I believe this is a duplicate of https://github.com/dotnet/roslyn/issues/24991. Code metrics is using MSBuild workspace to load the project/solution, and I believe you can reproduce this same exception on your provided project via a simple console application with the repro steps in https://github.com/dotnet/roslyn/issues/24991. Resolving this as a duplicate.

**Closed by mavasani** 2019-04-15 13:59 UTC
Labels: Area-CodeMetrics, Bug
