### ISSUE TITLE
Code Analysis misses many issues .net framework CA catches

### ISSUE THREAD

**Issue by Jm-Fox** [dotnet/roslyn-analyzers#1948] opened 2018-12-26 20:33 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.2

#### Diagnostic ID

Only in .net framework:
* [CA2237](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2237-mark-iserializable-types-with-serializableattribute?view=vs-2017)
* [CA2210](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2210-assemblies-should-have-valid-strong-names)
* [CA2000](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope?view=vs-2017)
* [CA1822](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1822-mark-members-as-static?view=vs-2017)
* [CA1811](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1811-avoid-uncalled-private-code?view=vs-2017)
* [CA1801](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801-review-unused-parameters?view=vs-2017)
* [CA1722](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1722-identifiers-should-not-have-incorrect-prefix?view=vs-2017)
* [CA1721](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1721-property-names-should-not-match-get-methods?view=vs-2017)
* [CA1716](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1716-identifiers-should-not-match-keywords?view=vs-2017)
* [CA1711](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1711-identifiers-should-not-have-incorrect-suffix?view=vs-2017)
* [CA1709](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1709-identifiers-should-be-cased-correctly?view=vs-2017)
* [CA1704](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1704-identifiers-should-be-spelled-correctly?view=vs-2017)
* [CA1405](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1405-com-visible-type-base-types-should-be-com-visible?view=vs-2017)
* [CA1303](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1303-do-not-pass-literals-as-localized-parameters?view=vs-2017)
* [CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2017)
* [CA1031](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1031-do-not-catch-general-exception-types?view=vs-2017)
* [CA1020](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1020-avoid-namespaces-with-few-types?view=vs-2017)
* [CA1017](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1017-mark-assemblies-with-comvisibleattribute?view=vs-2017)
* [CA1016](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1016-mark-assemblies-with-assemblyversionattribute?view=vs-2017)
* [CA1014](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1014-mark-assemblies-with-clscompliantattribute?view=vs-2017)
* [CA1004](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1004-generic-methods-should-provide-type-parameter?view=vs-2017)

Only in .net core*:
* [CA2229](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2229-implement-serialization-constructors?view=vs-2017)

*I do not mind new CA issues being introduced to .net core; in fact I support it. However, old CA issues being lost is not acceptable to my employer.

#### Repro steps

1. Clone https://github.com/Jm-Fox/NetCoreCodeAnalysis
2. Open CodeAnalysis.sln (I used VS 2017.9)
3. In the solution explorer, right click on **Solution 'CodeAnalysis' (2 projects)** and select **Analyze** > **Run Code Analysis on Solution**
4. Compare CA results for each project (they have identical code)

#### Expected behavior

Each CA warning should appear twice: once in the .net framework 4.6.1 project and once in the .net core project.

#### Actual behavior

Many CA warnings appear only in the .net framework 4.6.1 project.

#### Other notes

I don't have a proper repro for [CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2017), but this is another one that appears to be missing in .net core that is fairly important.

I apologize if this is documented elsewhere or is expected behavior. In my research so far I have not been able to find anything that explains why CA for .net core isn't 1:1 with CA for .net framework.

These issues not showing up in CA for .net core is very important to both me and my employer. Not having automated checks like disposing of IDisposables along all paths can lead to bugs in production if not caught in code review, and this is not something we can reasonably ask our code reviewers to catch 100% of the time without CA assistance.
Also the repro I have given is just a sample of CA inconsistencies I found by accident. I have no reason to believe there aren't other CA issues that are missing in .net core, and given what I've seen I expect that I'm missing some.

#### Other questions

1. Is the nuget package supposed to be a 1:1 replacement for CA in .net framework?
2. If so, when can one expect these inconsistencies to be ironed out?

**Comment by sharwell** [comment] 2019-01-02 16:48
- CA2237: This is implemented; specific deviations can be filed as individual bugs
- CA2210: See #532
- CA2000: This is already implemented; specific deviations can be filed as individual bugs
- CA1822
- CA1811
- CA1801
- CA1722
- CA1721
- CA1716
- CA1711
- CA1709
- CA1704
- CA1405
- CA1303
- CA1062
- CA1031
- CA1020
- CA1017
- CA1016
- CA1014
- CA1004

**Comment by sharwell** [comment] 2019-01-02 16:58
@mavasani I summarized the state of impacted rules above.

**Comment by Jm-Fox** [comment] 2019-01-03 16:03
Thanks for the summary. Is there any action required from me, such as filing individual bugs?

**Comment by sharwell** [comment] 2019-01-03 16:08
@Jm-Fox from the steps above, it sounds like the reproducer case (run against a reference repository) would be enough to show the various differences you found, but it doesn't give a good way to know which ones are the most important to you. It might take us a while to get these differences itemized since the process for filing bugs like this is not automated. If you find specific cases that are especially relevant to your projects, it would be good to go ahead and file individual issues for those.

**Comment by mavasani** [comment] 2019-01-03 17:02
Thanks @sharwell @Jm-Fox for all the investigations/reports here. We are striving very hard to ensure compatibility between legacy FxCop and FxCop analyzers, especially for rules which are deemed as important to port based on the current dotnet framework guidelines. We are going to schedule testing cycles in the coming months to run both legacy FxCop and FxCop analyzers over real world code and identify differences and work towards fixing them. As @sharwell mentioned above, if you do find any differences that are super important to you OR block migration to FxCop analyzers, kindly file individual issues, with a note on its priority.

Tagging @vatsalyaagrawal @jinujoseph as well so we can cost/schedule this testing effort.

**Comment by MelbourneDeveloper** [comment] 2019-02-18 04:38
Yep, many of the fundamental issues are missing.

**Comment by mavasani** [comment] 2019-06-26 21:27
Closing this issue as the recommendation is to file separate issues for each rule OR comment on existing issues for a rule.

**Closed by mavasani** 2019-06-26 21:27 UTC
Labels: Bug, Urgency-Soon
