### ISSUE TITLE
CA1812 and CA1852 have limited use

### ISSUE THREAD

**Issue by geeknoid** [dotnet/roslyn-analyzers#6542] opened 2023-03-21 23:35 UTC
### Analyzer

**Diagnostic ID**: [CA1852](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1852)
**Diagnostic ID**: [CA1812](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1812)

### Describe the improvement

CA1812 reports unused internal types, while CA1852 recommends to seal internal types. Both diagnostics immediately terminate without doing any work if they are used on an assembly that has an instance of InternalsVisibleTo. In real applications, the majority of the application's assemblies will have this attribute in order to enable testing. As a result, the diagnostics are generally ineffective and will therefore not have the benefit they could. 

### Describe suggestions on how to achieve the rule

Provide an option to enable customers to override this behavior and force the analyzers to run even when IVT is present. In reality, the level of false positives will likely be quite low since IVT is mostly used for testing, and tests don't tend to be the unique consumer of an internal type.

**Comment by Youssef1313** [comment] 2023-03-24 07:47
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5973

**Closed by Youssef1313** 2023-03-24 07:47 UTC
