### ISSUE TITLE
No analyzer to warn against assigning an async lambda to an Action

### ISSUE THREAD

**Issue by wizofaus** [dotnet/roslyn-analyzers#3196] opened 2020-01-11 01:46 UTC
I finally realised a reason why some of my unit tests were behaving oddly today - it was because I had the pattern:
```
DoSomething(async foo => 
{ 
   Assert.NotNull(await foo.Bar());
});
```
But DoSomething actually accepted an `Action<Foo>` that it called synchronously.  I'm not sure the exact details of how this is supposed to work internally but what definitely occurs is that while the Assert causes an exception to be thrown and the rest of the lambda doesn't execute, nothing actually catches the exception, and the assert is never reported.
In fact in general exceptions thrown from async lambdas that have been assigned to `Action<>`s and executed synchronously seem to get swallowed.  Given the obvious danger of this, surely there's a case for detecting it with a code analyzer?  I can't think of any case where I'd want to use this (instead I provided a new version of DoSomething that accepted a Func<Task, Foo>, and the assert causes the expected behaviour).

**Comment by sharwell** [comment] 2020-01-11 01:57
This is reported as [VSTHRD100](https://github.com/microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD100.md) by the [Microsoft.VisualStudio.Threading.Analyzers](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers) analyzer package.

**Comment by wizofaus** [comment] 2020-01-11 02:06
Thanks - I just added that to my project and sure enough I get a warning "Avoid using async lambda for a void returning delegate because any exceptions not handled by the delegate will crash the process".  Apparently this was a known issue as long ago as 2013, surprised it's only come to my attention now.
Interestingly enough while I don't observe any crashing, it's definitely that case when running Xunit tests at any rate that such exceptions are simply ignored on Windows/Mac (and the tests pass) whereas on Linux they seem to cause the xunit runner to hang.
Is there a plan to move this analyzer into NetCore.Analyzers or one of non-VisualStudio ones?

**Comment by sharwell** [comment] 2020-01-11 02:11
That analyzer package is intended for general use (with or without the supporting library). We are considering adding it as a reference from the FXCop analyzers package so it's brought in automatically.

**Comment by sharwell** [comment] 2020-01-11 02:11
Duplicate of #1576

**Closed by sharwell** 2020-01-11 02:11 UTC
