### ISSUE TITLE
CA2007 does not produce a warning in the VS Error List and text editor.

### ISSUE THREAD

**Issue by Tum4ik** [dotnet/roslyn-analyzers#3599] opened 2020-05-04 11:07 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

Example: [CA2007](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007?view=vs-2019)

#### Repro steps

1. Install v2.9.9
2. Write some async method and call some other async method without using `ConfigureAwait`. Warning is produced:
![image](https://user-images.githubusercontent.com/21317790/80959421-74981900-8e0f-11ea-9851-bc78ce123ea4.png)

3. Install v3.0.0
4. The warning has disappeared from the text editor and Error List, however it is still present in the build output:
![image](https://user-images.githubusercontent.com/21317790/80959821-42d38200-8e10-11ea-962b-cc4804972165.png)
 

#### Expected behavior
The warning has to be present in the VS text editor and Error List.

#### Actual behavior
The warning is not present in the VS text editor and Error List.

**Comment by mavasani** [comment] 2020-05-04 12:36
Can you please try to close and reopen VS?

**Comment by Tum4ik** [comment] 2020-05-04 13:18
@mavasani Hi,
Yes, I tried. It is actually continuing second or even third day for me. So, even the PC reboot does not help. Only downgrading to the version 2.9.9 helps.

**Comment by mavasani** [comment] 2020-05-04 14:27
Interesting, I cannot repro what you are indicating. I do see CA2007 from intellisense:

![image](https://user-images.githubusercontent.com/10605811/80976701-99bd6500-8dd8-11ea-8bd9-a88c992cf0d3.png)

**Comment by Tum4ik** [comment] 2020-05-04 14:58
Oh..! It is ReSharper. Somehow it suppresses the warning. I have disabled it now and the warning is working as expected. I will try identify the exact problem.

**Comment by mavasani** [comment] 2020-05-04 15:17
Thanks, closing this issue...

**Closed by mavasani** 2020-05-04 15:17 UTC

**Comment by Tum4ik** [comment] 2020-05-04 15:24
Sorry, but this is not the end. It seems problem is in `<TargetFramework>netstandard2.1</TargetFramework>`

**Comment by mavasani** [comment] 2020-05-04 15:27
@Tum4ik I am unable to reproduce your issue even after switching the target framework of netstandard2.1.

I would suggest that you try to create a small standalone repro/project and attach it to this issue.

**Comment by Tum4ik** [comment] 2020-05-04 15:39
yep, I am also not able to make it working again anyhow. It seems it is my environment and/or cache problem.

**Comment by Tum4ik** [comment] 2020-05-04 16:27
Here is repro project.
[ClassLibrary1.zip](https://github.com/dotnet/roslyn-analyzers/files/4575849/ClassLibrary1.zip)

**Comment by Tum4ik** [comment] 2020-05-04 16:30
Here is how it behaves:
![2020-05-04_19-25-12](https://user-images.githubusercontent.com/21317790/80989546-bfc92080-8e3d-11ea-9c50-ced8a48cb394.gif)

**Comment by mavasani** [comment] 2020-05-04 19:49
Thanks @Tum4ik. However, that project does not build locally for me. Also it seems to be based on the legacy project system. Can you try with a new SDK style project? I also recommend that you restart VS after upgrading your analyzer packages.

**Comment by Tum4ik** [comment] 2020-05-04 20:22
> Can you try with a new SDK style project?
Could you tell me pls how I can do that? I'm not aware of that.

**Comment by mavasani** [comment] 2020-05-04 20:45
https://docs.microsoft.com/en-us/nuget/resources/check-project-format should have some documentation to help you get started. Creating a new .netstandard/.netcore C# project in VS should also default to SDK style project file.

**Comment by Tum4ik** [comment] 2020-05-04 21:00
oh... I see now... I wonder how it could happen. But I use the correct style for my real project and it behaves like described above (incorrect).

**Comment by Tum4ik** [comment] 2020-05-04 21:08
Here is the correct SDK style project.
[ClassLibrary1.zip](https://github.com/dotnet/roslyn-analyzers/files/4577476/ClassLibrary1.zip)

**Comment by Tum4ik** [comment] 2020-05-07 14:21
Also CA1307 behaves in the same way.
