### ISSUE TITLE
CA1801: False report for constuctor with expression body

### ISSUE THREAD

**Issue by adamralph** [dotnet/roslyn-analyzers#1783] opened 2018-08-13 14:58 UTC
#### Analyzer package

[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

Example: v2.6.1

#### Diagnostic ID

[CA1081](https://msdn.microsoft.com/en-us/library/ms182268.aspx)

#### Repro steps

1. Clone/download this commit: https://github.com/adamralph/bullseye/tree/1.1.0-rc.2
1. Build the solution inside Visual Studio

#### Expected behavior

There is no warning for this line: https://github.com/adamralph/bullseye/blob/1.1.0-rc.2/Bullseye/Internal/TargetWithoutInput.cs#L11

#### Actual behavior

CA1801 is shown for that line:

| Severity | Code   | Description                                                                                        | Project                  | File                                                               | Line | Suppression State |
|----------|--------|----------------------------------------------------------------------------------------------------|--------------------------|--------------------------------------------------------------------|------|-------------------|
| Warning  | CA1801 | Parameter action of method .ctor is never used. Remove the parameter or use it in the method body. | Bullseye(netstandard2.0) | C:\code\adamralph\bullseye\Bullseye\Internal\TargetWithoutInput.cs | 11   | N/A               |

#### Notes

If the constructor is changed to a block body, the warning no longer appears.

**Comment by mavasani** [comment] 2018-08-13 15:00
Dupe of https://github.com/dotnet/roslyn-analyzers/issues/1606. Note that the issue was in the underlying compiler/analyzer API, which has been fixed in Visual Studio 15.8 release. Can you try the analyzer package against latest VS 15.8 Preview?

**Closed by mavasani** 2018-08-13 15:00 UTC

**Comment by adamralph** [comment] 2018-08-14 12:04
Thanks @mavasani. I've confirmed the bug is fixed in 15.8 preview 5.
