### ISSUE TITLE
PureAttribute in another assembly ignored by DoNotIgnoreMethodResultsAnalyzer CA1806 during the build

### ISSUE THREAD

**Issue by rcatley** [dotnet/roslyn-analyzers#3265] opened 2020-02-04 11:33 UTC
#### Analyzer package

[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

v2.9.8 (Latest)

#### Diagnostic ID

[CA1806](https://docs.microsoft.com/visualstudio/code-quality/ca1806-do-not-ignore-method-results)

#### Repro steps

1. There is a method 'PureMethod' marked as [Pure] which is implemented in another assembly (assembly B).
2. In project A, include nuget package analyzer and reference to assembly B.
3. In project A call method 'PureMethod' and do not use the returned value.
4. Compile project A 

#### Expected behavior
Compilation Warning.

#### Actual behavior
No Warning from build.
IntelliSense with the affected file open, does show the warning.

Looking at https://github.com/dotnet/roslyn/issues/35104, the current behavior might be the expected.
This seems like a similar issue to https://github.com/dotnet/roslyn-analyzers/issues/2215, although the workaround in https://github.com/dotnet/roslyn-analyzers/pull/2585 doesn't look like an approach that could be applied.
Is there an approach available to address this within the analyzers?

**Comment by Evangelink** [comment] 2020-10-01 14:15
I have been able to reproduce the issue with v2.9.8 and can confirm the issue is fixed in v3.3.0 so I am going to close this issue.

**Closed by Evangelink** 2020-10-01 14:15 UTC
Labels: Bug, Resolution-Fixed, Verified
