### ISSUE TITLE
CSharpAsAndNullCheckDiagnosticAnalyzer throws NullReferenceException

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-analyzers#1629] opened 2018-03-06 18:38 UTC
VS 15.7 Preview 1 (27505.0.d15.7)

```
git clone https://github.com/Microsoft/VSSDK-Analyzers.git
cd vssdk-analyzers
git co de48b204a79a0429569de5cabbee11b3444f1ac5
src\Microsoft.VisualStudio.SDK.Analyzers.sln
```

The error list indicates an analyzer has thrown a NullReferenceException.

The analyzer throws while analyzing [this line](https://github.com/AArnott/VSSDK-Analyzers/blob/de48b204a79a0429569de5cabbee11b3444f1ac5/src/Microsoft.VisualStudio.SDK.Analyzers/VSSDK002PackageRegistrationMatchesBaseTypeAnalyzer.cs#L68):

> 
	Analyzer 'Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Microsoft.VisualStudio.SDK.Analyzers		1	Compiler	Active
> Analyzer 'Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.SDK.Analyzers
SyntaxTree: d:\git\VSSDK-Analyzers\src\Microsoft.VisualStudio.SDK.Analyzers\VSSDK001DeriveFromAsyncPackageAnalyzer.cs
SyntaxNode: return; [ReturnStatementSyntax]@[3290..3297) (68,16)-(68,23)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.GetLeftmostCondition(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by mavasani** [comment] 2018-03-06 18:40
Thanks @AArnott. This is dupe of https://github.com/dotnet/roslyn/issues/25237. Closing as external.

**Closed by mavasani** 2018-03-06 18:40 UTC
Labels: Bug, Resolution-External
