### ISSUE TITLE
Build failures due to CSharpDiagnosticAnalyzerApiUsageAnalyzer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#1803] opened 2018-09-04 11:40 UTC
#### Analyzer package

Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer

#### Package Version

v2.6.1

#### Expected behavior

Build succeeds. 

#### Actual behavior

https://ci.appveyor.com/project/sharwell/stylecopanalyzers/build/1.0.3466

```
CSC : error AD0001: Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\projects\stylecopanalyzers\StyleCop.Analyzers\StyleCop.Analyzers.Test.CSharp7\StyleCop.Analyzers.Test.CSharp7.csproj]
```

**Comment by mavasani** [comment] 2018-09-04 12:53
Dupe of https://github.com/dotnet/roslyn-analyzers/issues/1711

**Comment by mavasani** [comment] 2018-09-04 15:03
Re-opening as @sharwell mentioned the failing build didn't have any error types, which was the cause of the crash in #1711.

**Comment by alphaleonis** [comment] 2018-09-11 15:01
We also get a whole heap of these warnings after upgrading to VS 15.8.  Haven't been able to make a simple repro however, but I'm guessing you're on top of this?  Any timeline for a fix?

**Comment by mavasani** [comment] 2018-10-04 23:15
I have a repro:

```
namespace N
{
    internal delegate void MyDelegate();
}
```

**Closed** 2018-10-04 23:44 UTC
Labels: Area-Microsoft.CodeAnalysis.Analyzers, Bug

**Comment by adamralph** [comment] 2021-05-06 12:45
In which version was this fixed?

I'm [using 2.10.0](https://github.com/Particular/NServiceBus/blob/d39fa22d4894f87fe3b8c6d6e0569c55770f8946/src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj#L14) and I'm [having this problem](https://github.com/Particular/NServiceBus/pull/6051/checks?check_run_id=2518127665).

**Comment by adamralph** [comment] 2021-05-06 12:51
FWIW, I've confirmed that 2.4.0 does _not_ contain this bug, so I've reverted to that version.

FYI although 2.6.1 contains this bug, I didn't want to revert to 2.6.0 because 2.6.1 must be fixing some _other_ bugs, and 2.6.1 is [listed as the supported version](https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2019) in the 2.6.x range.

I can't upgrade past `2.10.0` because my analyzer needs to support VS 2017.
