### ISSUE TITLE
CA1812 fails (VB)

### ISSUE THREAD

**Issue by oahrens** [dotnet/roslyn-analyzers#2396] opened 2019-04-28 21:03 UTC
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.2

#### Diagnostic ID

[CA1812](https://docs.microsoft.com/de-de/visualstudio/code-quality/ca1812-avoid-uninstantiated-internal-classes?view=vs-2019)

#### Repro steps
Try this code snippet:
  ```
Partial Public NotInheritable Class Role

    <SuppressUnmanagedCodeSecurity()>
    Private NotInheritable Class SafeNativeMethods

        Private Sub New()
        End Sub

        <DllImport("advapi32.dll", CharSet:=CharSet.Unicode, BestFitMapping:=False, ThrowOnUnmappableChar:=True, SetLastError:=True)>
        Friend Shared Function LogonUserW(<[In](), MarshalAs(UnmanagedType.LPWStr)> ByVal valUserName As String,
                                          <[In](), [Optional](), MarshalAs(UnmanagedType.LPWStr)> ByVal valUserDomain As String,
                                          <[In](), [Optional]()> ByVal valUserPassword As IntPtr,
                                          <[In](), MarshalAs(UnmanagedType.U4)> ByVal valLogonType As ELogOnType,
                                          <[In](), MarshalAs(UnmanagedType.U4)> ByVal valLogonProvider As ELogOnProvider,
                                          <Out()> ByRef refToken As SafeTokenHandle) As <MarshalAs(UnmanagedType.Bool)> Boolean
        End Function


    End Class

End Class
```

#### Expected behavior
The rule is not violated.

#### Actual behavior
The rule is violated.

**Comment by Evangelink** [comment] 2019-11-28 16:42
I might be missing something but in the example provided `SafeNativeMethods` isn't used anywhere so the issue looks valid to me. I have tried to create a new instance of this class and call `LogonUserW`, doing so the error goes away.

Could you please let us know if I have missed the intent of your example?

**Comment by Youssef1313** [comment] 2020-05-31 07:54
@Evangelink This is **indeed** a false positive IMO, this class acts as a static class. But in VB.NET, there is no `Shared` (static) classes. An alternative is a `Module`, but it's still different than a class.

However, I'm not sure how the behavior of this rule should be corrected. Should it if all the methods are `Shared` and the ctors are `Private`, then don't emit the warning?

This issue also seem like a duplicate of #1878

@mavasani @sharwell

**Comment by Evangelink** [comment] 2020-06-02 13:01
@Youssef1313 I might still be missing something but the class is private and in the code snippet provided isn't used anywhere at all so I don't see why the rule should not report any issue. If there was at least one use of it and the issue was reporting, in this case yes there could be some false-positive. But that's not the repro given here.

**Comment by Youssef1313** [comment] 2020-06-04 16:08
@Evangelink Oh I missed that the class here is private.
The thing that can still make this issue valid if the class **is not** instantiated, but the Shared Function is called somewhere. (I haven't tried to do that)

**Comment by Evangelink** [comment] 2020-07-20 08:57
Duplicates of #1878

**Closed by Evangelink** 2020-07-20 08:57 UTC
