### ISSUE TITLE
Write on-boarding document for Roslyn-Analyzer Package 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1310] opened 2017-10-05 00:04 UTC
https://github.com/dotnet/sdk/issues/1086 

mention 
https://stackoverflow.com/questions/45678861/whats-the-latest-version-of-roslyn-my-analyzer-can-target-if-i-support-vs2015/45680699#45680699

**Comment by mavasani** [comment] 2017-11-16 17:55
@jinujoseph @kuhlenh Who should take this up?

**Comment by thebothead** [comment] 2017-12-05 19:56
This ticket has not moved in a while.  Any updates here?

**Comment by thebothead** [comment] 2017-12-05 20:02
For anyone waiting for this I found this article as well:
https://carlos.mendible.com/2017/08/24/net-core-code-analysis-and-stylecop/

**Comment by mavasani** [comment] 2017-12-05 20:07
@thebothead If you are looking for specific version of analyzer package to install for given VS version, please see https://github.com/dotnet/roslyn-analyzers/#recommended-version-of-analyzer-packages.

**Comment by jinujoseph** [comment] 2017-12-05 20:20
cc @kuhlenh

**Comment by kuhlenh** [comment] 2017-12-05 21:32
@mavasani do you have the final list of analyzers that we're having on-by-default?

**Comment by mavasani** [comment] 2017-12-05 22:09
> do you have the final list of analyzers that we're having on-by-default?

NuGet or VSIX? We are not changing the defaults for NuGet (unless we get feedback about noise), but we should surely enable more in VSIX.

**Comment by mavasani** [comment] 2019-07-01 20:23
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2026

**Closed by mavasani** 2019-07-01 20:23 UTC
Labels: Documentation, Urgency-Soon
