### ISSUE TITLE
New version 3.3.1 is adding a *.GeneratedMSBuildEditorConfig.editorconfig to each project.

### ISSUE THREAD

**Issue by JuanMejiaVelez** [dotnet/roslyn-analyzers#4456] opened 2020-11-24 07:20 UTC
### Analyzer

**Diagnostic ID**: [CA2013](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2013): `Do not use ReferenceEquals with value types`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100-rc.2](https://dotnet.microsoft.com/download/dotnet/5.0)

_OR_

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.1 (Latest)

### Describe the bug

After updating to version 3.3.1 or clean installing the 3.3.1 nuget package each project generates a new file added to the repo that matches the project name plus "GeneatedMSBuildEditorConfig.editorconfig" I could not find any official mention of this as an expected change from the new version, but in other projects the generation of these files has been regarded as a bug.

**Comment by JuanMejiaVelez** [comment] 2020-11-24 07:30
Related bug on Roslyn
[https://github.com/dotnet/roslyn/issues/48430](https://github.com/dotnet/roslyn/issues/48430)

**Comment by chsienki** [comment] 2020-11-24 23:47
This will be fixed in an upcoming version via https://github.com/dotnet/roslyn/pull/48781

**Closed by chsienki** 2020-11-24 23:47 UTC

**Comment by DenisLaky** [comment] 2021-02-24 17:01
@chsienki Issue appears when adds the Microsoft.CodeAnalysis.NetAnalyzers package. Is this the expected behaviour?

**Comment by chsienki** [comment] 2021-02-24 17:31
@DenisLaky Yes, it occurs with any non SDK project that references a package that requests msbuild data.

The package you mention is known to request it, so will create the file on earlier builds of roslyn that don't have the fix.

**Comment by DenisLaky** [comment] 2021-02-24 19:30
@chsienki Thank you, Is it safe to disable autogeneration via  GenerateMSBuildEditorConfigFile parameter ?    

`<GenerateMSBuildEditorConfigFile>false</GenerateMSBuildEditorConfigFile>
`

**Comment by znakeeye** [comment] 2023-12-20 15:30
> @chsienki Thank you, Is it safe to disable auto generation via GenerateMSBuildEditorConfigFile parameter ?
> 
> `<GenerateMSBuildEditorConfigFile>false</GenerateMSBuildEditorConfigFile> `

Did you ever figure out if it was safe to disable auto generation?

Turns out that the generated path is very, very long. In our case, we reached the 260 character limit which broke NuGet Restore... (Enabling long paths is a viable workaround too.)
