### ISSUE TITLE
CA1801: Unused parameters rule firing on event handlers

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#1223] opened 2017-06-01 01:23 UTC
#### Analyzer package

2.3.0-beta1

#### Analyzer

CA1810: Review unused parameters

#### Repro steps

```csharp
        public DebugPageControl()
        {
            InitializeComponent();
            DataContextChanged += DebugPageControlControl_DataContextChanged;
        }

        void DebugPageControlControl_DataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
```

#### Expected behavior
No warnings because this is an event handler and needs to have this shape.

#### Actual behavior
Warning that'll need to be suppressed.

**Comment by mavasani** [comment] 2017-06-01 01:32
@333fred just fixed this bug today

**Comment by 333fred** [comment] 2017-06-01 06:37
Dupe of https://github.com/dotnet/roslyn-analyzers/issues/1218, should be fixed with the same pr that closed that.

**Closed by 333fred** 2017-06-01 06:37 UTC
